<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Inquiryand Amendment</name>
   <tag></tag>
   <elementGuidId>d79c8710-253b-4ce3-84b9-b30a79278e44</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='InquiryAndAmendmentValidation']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#InquiryAndAmendmentValidation</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Inquiry and Amendment&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e9e0d4ba-74bc-4c44-8352-538070a1b6ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gb-hover-side confirmation-link</value>
      <webElementGuid>219cf997-05af-4572-9ca8-47ba33f63d49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>InquiryAndAmendmentValidation</value>
      <webElementGuid>06501245-8a7b-40ba-9f16-e4decf50587d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>InquiryAndAmendmentValidation</value>
      <webElementGuid>1796c2d2-bea2-4a0b-af2b-323315d09d4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>return loadIframe('ifrm1', this.href);</value>
      <webElementGuid>ccf51baf-6208-4465-8cd8-25792bbe7c15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Inquiry
									and Amendment </value>
      <webElementGuid>c72d5ec7-9ea0-4faa-ac15-51e655d6d4b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;InquiryAndAmendmentValidation&quot;)</value>
      <webElementGuid>e1ba3438-d918-4209-84f4-de096f89a661</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='InquiryAndAmendmentValidation']</value>
      <webElementGuid>55033f6d-33db-41bb-96fd-6a4380f985d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sidebarCustomer']/ul/li/a</value>
      <webElementGuid>f8f96f1c-77fc-4bdc-9d15-613d0b6a4f4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Inquiry
									and Amendment')]</value>
      <webElementGuid>be3e5c3f-bd1d-4bcf-9077-8ef9fd9ad64d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Client'])[1]/following::a[1]</value>
      <webElementGuid>1f79f0ff-9388-4c9a-8113-f17e012444d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dashboard'])[1]/following::a[2]</value>
      <webElementGuid>3604f869-5551-42e1-87d2-5b85eb597725</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'InquiryAndAmendmentValidation')]</value>
      <webElementGuid>36e3bb8a-2aa6-46fa-b40d-52dc725045c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/div/ul/li/a</value>
      <webElementGuid>5233517f-a0c9-426b-82f0-7c0de38e333c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'InquiryAndAmendmentValidation' and @id = 'InquiryAndAmendmentValidation' and (text() = ' Inquiry
									and Amendment ' or . = ' Inquiry
									and Amendment ')]</value>
      <webElementGuid>2c864d4b-6630-4f65-99b4-e5c64b211d07</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
