<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_i_swal2-success-ring (1)</name>
   <tag></tag>
   <elementGuidId>5fbb799e-b2cb-4d73-a032-8bedec813196</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@class='swal2-content']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.swal2-success-ring</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.swal2-success-ring</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b7b5b3e7-499c-4058-863b-a1618cf559be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>swal2-success-ring</value>
      <webElementGuid>1c274da3-36d5-4859-853f-e4da0b4308f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;body&quot;)/div[@class=&quot;swal2-container swal2-center swal2-fade swal2-shown&quot;]/div[@class=&quot;swal2-popup swal2-modal swal2-show&quot;]/div[@class=&quot;swal2-header&quot;]/div[@class=&quot;swal2-icon swal2-success swal2-animate-success-icon&quot;]/div[@class=&quot;swal2-success-ring&quot;]</value>
      <webElementGuid>14f22574-086e-469a-afd7-b0a25ee3dfcf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='body']/div[4]/div/div/div[5]/div[2]</value>
      <webElementGuid>404bd927-3d50-47a8-baa3-c8295bd51354</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div[5]/div[2]</value>
      <webElementGuid>e2e22bf4-6483-42d2-a401-4c246b7bdfa4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
