<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_i_swal2-success-ring</name>
   <tag></tag>
   <elementGuidId>26a16111-34ad-4b84-932c-358ac4042473</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body[@id='body']/div[4]/div/div/div[5]/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.swal2-success-ring</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.swal2-success-ring</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e712bf29-a178-476b-a639-3d8175e2fd40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>swal2-success-ring</value>
      <webElementGuid>6b96d6c0-0fb9-4f75-b7bc-6796b1a2b70a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;body&quot;)/div[@class=&quot;swal2-container swal2-center swal2-fade swal2-shown&quot;]/div[@class=&quot;swal2-popup swal2-modal swal2-show&quot;]/div[@class=&quot;swal2-header&quot;]/div[@class=&quot;swal2-icon swal2-success swal2-animate-success-icon&quot;]/div[@class=&quot;swal2-success-ring&quot;]</value>
      <webElementGuid>2209aac4-c1d7-47d1-88b5-415c38aaab89</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='body']/div[4]/div/div/div[5]/div[2]</value>
      <webElementGuid>3d175826-437d-42fb-b94b-15da16f15de5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div[5]/div[2]</value>
      <webElementGuid>f87dea57-c3b7-4106-8259-9ca2c87989e3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
