<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Active_mdi mdi-magnify</name>
   <tag></tag>
   <elementGuidId>88e6d4e4-d062-4633-94b0-443b286f4f72</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tbody[@id='tableCusViewBody']/tr/td[9]/a/span/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.mdi.mdi-magnify</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[title=&quot;View Customer&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>4e242717-7ac5-4127-be98-a4db5bd74441</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mdi mdi-magnify</value>
      <webElementGuid>f88e08b5-f2a7-4fa8-9ed2-35f9bac7d7c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tableCusViewBody&quot;)/tr[@class=&quot;odd&quot;]/td[@class=&quot;td-actions&quot;]/a[@class=&quot;action-icon btn&quot;]/span[@class=&quot;icon text-gray-700 ml-auto&quot;]/i[@class=&quot;mdi mdi-magnify&quot;]</value>
      <webElementGuid>3f1e0608-ba8e-4a2e-8984-c5fd28ef7f4e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='tableCusViewBody']/tr/td[9]/a/span/i</value>
      <webElementGuid>8a2f8669-53a5-4bba-b88b-20c3ee7b6442</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/span/i</value>
      <webElementGuid>06052aba-7f3a-467d-8c79-82bd7f844770</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
