<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_YES_healthDeclaration</name>
   <tag></tag>
   <elementGuidId>641c2611-5a12-41e7-bd9e-5b450a1e5ae7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='healthDeclarationNo']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#healthDeclarationNo</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#healthDeclarationNo</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b906b8dd-ba43-4475-80e2-a16b624af2a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>acfeae34-8215-4297-8bf4-e95bbf68961c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input gb-border-fcs</value>
      <webElementGuid>becc216a-8f97-433b-99ef-2704c5a37b49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>770ccae7-5e37-40f3-b7d6-6989ca973700</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>isGoodCondition();</value>
      <webElementGuid>a94508b3-cacd-435b-8fd8-e9157edff189</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>healthDeclarationNo</value>
      <webElementGuid>b0c84746-c50d-4d0d-8966-ada6cdf759d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>healthDeclaration</value>
      <webElementGuid>258b6ffe-b749-4ff0-b0f4-e59116dc6497</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;healthDeclarationNo&quot;)</value>
      <webElementGuid>1f31059d-51b9-4c5a-bccc-9dc7cbd20d06</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='healthDeclarationNo']</value>
      <webElementGuid>c5684ecd-4597-4962-96ed-140d1c36b44e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='9']/div/div/div[2]/div[3]/input</value>
      <webElementGuid>ac8e40c1-0414-40cc-801c-0b8aa3794b9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/div/div[2]/div[3]/input</value>
      <webElementGuid>db7362ce-c251-4eef-b43c-73bde1b1a25d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'healthDeclarationNo' and @name = 'healthDeclaration']</value>
      <webElementGuid>d856db83-3447-47d6-8c1f-7377300beaad</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
