<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_--Select--NAPrimarySecondary</name>
   <tag></tag>
   <elementGuidId>2c8888b2-5102-4dfc-b533-74309f98e117</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='cboBeneficiary1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cboBeneficiary2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#cboBeneficiary2</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>587076cf-1ce2-4751-a474-b66046aff3d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cboBeneficiary2</value>
      <webElementGuid>f2ff7c98-75b4-4284-97ce-73455a670819</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>3a92dac3-b911-4f83-a4e1-e6303369d2ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>validateBeneficiary(2)</value>
      <webElementGuid>732feabe-cd83-42d7-826d-9e54346f0226</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> form-select required gb-border-fcs font-9</value>
      <webElementGuid>fdb3c008-e52b-4501-ad4f-7c769dc23b61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>--Select--N/APrimarySecondary </value>
      <webElementGuid>1fdd2771-0582-4ce5-b69d-be810770cc65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cboBeneficiary2&quot;)</value>
      <webElementGuid>53bbe6d0-db9a-4dcd-bba8-2c70632bf54f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='cboBeneficiary2']</value>
      <webElementGuid>b541e664-807d-477d-8477-e23a2ffdafe2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='row2']/div/div[6]/div/div/select</value>
      <webElementGuid>8d0a0daa-6aca-40d5-9fa4-b6912b03d0ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remarks:'])[1]/following::select[11]</value>
      <webElementGuid>768b5712-3e79-4f6b-82b1-22db0d9e5d3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Additional Beneficiary If any'])[1]/preceding::select[4]</value>
      <webElementGuid>7d1fd882-e01e-4dac-a020-3549d0818e57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Client Risk Assessment'])[2]/preceding::select[4]</value>
      <webElementGuid>d35a551d-cf81-46aa-a701-32d5cd413984</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div[6]/div/div/select</value>
      <webElementGuid>77630703-8224-4db4-af1f-74d61e1dcde3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'cboBeneficiary2' and (text() = '--Select--N/APrimarySecondary ' or . = '--Select--N/APrimarySecondary ')]</value>
      <webElementGuid>f07322ba-0797-43e0-afb7-9a9fc024ace8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
