<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_--Select--GLIP 1GLIP 2IPPaglambo</name>
   <tag></tag>
   <elementGuidId>cf9169ef-d359-4d0f-963b-a7ddcbc7661e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='cboIndivClassification']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cboIndivClassification</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#cboIndivClassification</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>5421d5e6-e9f3-44de-a48c-a042e1bc784a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cboIndivClassification</value>
      <webElementGuid>b29c3df7-0553-40f9-863a-d88866867d78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>IndivClassification();</value>
      <webElementGuid>2595b953-6882-4364-8301-dc833ab2fd5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-select gb-border-fcs select2 font-11</value>
      <webElementGuid>57149067-97d1-4874-b94b-2b9b36628dca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>select2</value>
      <webElementGuid>55680cc0-5bed-4519-95de-7babd5d77ba7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>--Select--GLIP 1GLIP 2IPPaglambo</value>
      <webElementGuid>e55eb388-2e99-4461-b30f-bfd9cd99beb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cboIndivClassification&quot;)</value>
      <webElementGuid>cb41c312-e1bc-4586-9af3-7607fd392cc9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='cboIndivClassification']</value>
      <webElementGuid>f4d35e74-f1ba-420d-a182-f6420df609db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='8']/div/div/div/div[4]/div/div/select</value>
      <webElementGuid>7484d040-3344-4079-92b2-38466081022b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total Score:'])[1]/following::select[1]</value>
      <webElementGuid>d8336f76-7e67-41f7-a0f4-3af30c83fe49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Health Declaration'])[1]/preceding::select[2]</value>
      <webElementGuid>c878e9da-dfbc-42cf-a8b7-1cda7aad894c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='YES'])[13]/preceding::select[2]</value>
      <webElementGuid>53de081b-10c7-43a3-80ef-9be978704ec3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/div/div/div[4]/div/div/select</value>
      <webElementGuid>7e0c6134-24d9-469d-a2c8-020795e78c85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'cboIndivClassification' and (text() = '--Select--GLIP 1GLIP 2IPPaglambo' or . = '--Select--GLIP 1GLIP 2IPPaglambo')]</value>
      <webElementGuid>2eb4c133-d822-4484-ae26-5e7205d1cbca</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
