<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Antonino (Ayusan)Bagong Anyo (Pob.)B_a9711d</name>
   <tag></tag>
   <elementGuidId>734827a4-a8d5-4bef-b608-5303047471e3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='cboPhyAddBarangay']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cboPhyAddBarangay</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#cboPhyAddBarangay</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>17c92757-9bf7-40e7-ba52-fdc68d9c1809</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cboPhyAddBarangay</value>
      <webElementGuid>ab895222-fe7d-4aea-907b-015b6acefc40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-select gb-border-fcs font-11</value>
      <webElementGuid>347fc7ab-8173-4d83-9b5a-970716117019</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Antonino (Ayusan)Bagong Anyo (Pob.)Bayanihan (Pob.)Bulakin IBulakin IiBungoyCabatangDagatanKinabuhayanMaligaya (Pob.)ManggahanPinagdanlayanPutolSan MateoSanta LuciaSilanganan (Pob.)</value>
      <webElementGuid>910433c5-a63f-4415-9e0c-b292c780b727</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cboPhyAddBarangay&quot;)</value>
      <webElementGuid>2c915f80-dc56-46f4-a952-64ee46284ef7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='cboPhyAddBarangay']</value>
      <webElementGuid>2842fbfb-4243-4dd7-b8b3-ba8daf1d5d30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='2']/div/div/div/div[6]/div/div/select</value>
      <webElementGuid>3adb0124-8fe9-4d8d-b6e0-f3fe7bb52fb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Business Address'])[1]/preceding::select[1]</value>
      <webElementGuid>31717c80-3f8c-448b-860f-1917eb5e6b49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/select</value>
      <webElementGuid>e2f50dfd-683f-447b-8d22-269e6bf8466f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'cboPhyAddBarangay' and (text() = 'Antonino (Ayusan)Bagong Anyo (Pob.)Bayanihan (Pob.)Bulakin IBulakin IiBungoyCabatangDagatanKinabuhayanMaligaya (Pob.)ManggahanPinagdanlayanPutolSan MateoSanta LuciaSilanganan (Pob.)' or . = 'Antonino (Ayusan)Bagong Anyo (Pob.)Bayanihan (Pob.)Bulakin IBulakin IiBungoyCabatangDagatanKinabuhayanMaligaya (Pob.)ManggahanPinagdanlayanPutolSan MateoSanta LuciaSilanganan (Pob.)')]</value>
      <webElementGuid>56257f82-7f59-4fe4-9440-a1ef530f849f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
