<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_--Select--EmploymentSalariesIncome f_b99596_1</name>
   <tag></tag>
   <elementGuidId>80e950c1-7baa-4968-90d0-a63e5f350962</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='cboKYCSourceOfIncome']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cboKYCSourceOfIncome</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#cboKYCSourceOfIncome</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>ff492345-d6ba-498c-bbd1-19fed27fbc3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cboKYCSourceOfIncome</value>
      <webElementGuid>bfe7ac85-28c8-4111-9a88-010d166c1353</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>checksourceOfFund();</value>
      <webElementGuid>610c4c04-1138-4e31-8fe6-3c84772e39a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-select gb-border-fcs font-11</value>
      <webElementGuid>b7c35c57-e612-4dd1-a41a-2f2506869e88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>--Select--Employment/SalariesIncome from businessInheritanceOthersProceeds from investmentRemittancesRetirement/Pension</value>
      <webElementGuid>26367c65-9365-402d-90c0-db7d89deda2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cboKYCSourceOfIncome&quot;)</value>
      <webElementGuid>190d103c-38d8-4b10-be2f-cfca18826364</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='cboKYCSourceOfIncome']</value>
      <webElementGuid>3386117c-cc43-4964-bb72-f11df47e2d91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='7']/div/div/div/div[3]/div/div/select</value>
      <webElementGuid>782d9470-ee4b-4d12-b9f3-75cfab03b801</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div/div/div[3]/div/div/select</value>
      <webElementGuid>849ec8b3-b118-4703-b1ab-89e6a26e3169</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'cboKYCSourceOfIncome' and (text() = '--Select--Employment/SalariesIncome from businessInheritanceOthersProceeds from investmentRemittancesRetirement/Pension' or . = '--Select--Employment/SalariesIncome from businessInheritanceOthersProceeds from investmentRemittancesRetirement/Pension')]</value>
      <webElementGuid>9ea8b41e-b27a-4264-91ba-7fec7256c005</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
