<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_--Select--Below 1,000 pesos1001 - 3,_8e7891</name>
   <tag></tag>
   <elementGuidId>7de80c1c-67de-49b8-a0ec-9490018ea26f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='cboHouseholdMonthlyInc']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cboHouseholdMonthlyInc</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#cboHouseholdMonthlyInc</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>92eba7c7-567e-4d65-9163-e1da343a68c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cboHouseholdMonthlyInc</value>
      <webElementGuid>420ad4b0-4a44-4b77-a3cd-c2593a94715a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-select gb-border-fcs font-11</value>
      <webElementGuid>258604c3-e993-4bdb-812e-e7a6a4129157</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>--Select--Below 1,000 pesos1001 - 3,000 pesos3001 - 5,000 pesos5001 - 8,000 pesos8001 - 10,000 pesos10001 - 15,000 pesosAbove 15,000 pesos</value>
      <webElementGuid>d912a05c-5c92-4342-af1f-a97344d49696</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cboHouseholdMonthlyInc&quot;)</value>
      <webElementGuid>a5cc2f22-c26d-4fe2-b9f5-3f0e970b13db</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='cboHouseholdMonthlyInc']</value>
      <webElementGuid>0e4de0cd-7150-46c9-a819-ae405414e595</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='7']/div/div/div/div[5]/div/div/select</value>
      <webElementGuid>e6b411d2-d137-4e40-9c7f-b4f957b11339</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AMLA watchlist? :'])[1]/preceding::select[1]</value>
      <webElementGuid>4f25c0e2-f0e3-4844-8831-008c9d1a7f22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div/div/div[5]/div/div/select</value>
      <webElementGuid>f0ed57f9-c49a-49aa-a838-7bfcf77aed50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'cboHouseholdMonthlyInc' and (text() = '--Select--Below 1,000 pesos1001 - 3,000 pesos3001 - 5,000 pesos5001 - 8,000 pesos8001 - 10,000 pesos10001 - 15,000 pesosAbove 15,000 pesos' or . = '--Select--Below 1,000 pesos1001 - 3,000 pesos3001 - 5,000 pesos5001 - 8,000 pesos8001 - 10,000 pesos10001 - 15,000 pesosAbove 15,000 pesos')]</value>
      <webElementGuid>8d6d7644-7d5e-41ae-b2c4-dad10e002b1b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
