<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_--Select--No Formal EducationElement_aa261c</name>
   <tag></tag>
   <elementGuidId>07674168-9fbf-4fa8-9961-bda5ccf24553</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='cboSpouseEducationalLevel']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cboSpouseEducationalLevel</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#cboSpouseEducationalLevel</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>01d717e6-1ce3-421c-9ca0-4edb24dd6136</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cboSpouseEducationalLevel</value>
      <webElementGuid>e1ae5656-a065-4b2f-855e-aa3a83f099ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>3546f32a-0c0c-405b-9897-cbebe5b2c581</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-select gb-border-fcs font-11</value>
      <webElementGuid>2ea7f730-7ef6-419f-8156-fcd96d36487c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>--Select--No Formal EducationElementary UndergraduateElementary GraduateHigh School UndergraduateHigh School GraduateVocationalAssociate DegreeCollege UndergraduateCollege GraduateMaster's DegreeDoctorate Degree</value>
      <webElementGuid>efd0d0e1-37d3-439d-917f-8a2da3b7669d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cboSpouseEducationalLevel&quot;)</value>
      <webElementGuid>e4323926-711e-4222-9634-33c06b5b3537</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='cboSpouseEducationalLevel']</value>
      <webElementGuid>c4b02edb-8b25-46f3-a6a5-460c8ea4836d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='5']/div/div/div[2]/div[2]/div/div[6]/div/div/select</value>
      <webElementGuid>346bfdb9-8abf-462a-b619-b5c09438d864</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[6]/div/div/select</value>
      <webElementGuid>ea407cbb-aefc-469c-9063-7ad3e5e11b13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'cboSpouseEducationalLevel' and (text() = concat(&quot;--Select--No Formal EducationElementary UndergraduateElementary GraduateHigh School UndergraduateHigh School GraduateVocationalAssociate DegreeCollege UndergraduateCollege GraduateMaster&quot; , &quot;'&quot; , &quot;s DegreeDoctorate Degree&quot;) or . = concat(&quot;--Select--No Formal EducationElementary UndergraduateElementary GraduateHigh School UndergraduateHigh School GraduateVocationalAssociate DegreeCollege UndergraduateCollege GraduateMaster&quot; , &quot;'&quot; , &quot;s DegreeDoctorate Degree&quot;))]</value>
      <webElementGuid>fff09718-c018-43e3-85b8-41f06f92220b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
