<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_--      Select      --Abra - CAR (Co_3be376</name>
   <tag></tag>
   <elementGuidId>8d5c2170-7a8e-4dec-a211-7af208d9d6d2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='cboPhyProvince']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cboPhyProvince</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#cboPhyProvince</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>3b575227-bd65-4dd5-a02b-1cd16351c09e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cboPhyProvince</value>
      <webElementGuid>e84cd12c-e283-44fb-9985-4e44e49dd622</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-select gb-border-fcs font-11</value>
      <webElementGuid>a9c18dab-6a5d-4712-aeef-7427c213dafd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>--      Select      --Abra - CAR (Cordillera Administrative Region)Agusan Del Norte - Region XIII (CARAGA)Agusan Del Sur - Region XIII (CARAGA)Aklan - Region VI (Western Visayas)Albay - Region V (Bicol Region)Antique - Region VI (Western Visayas)Apayao - CAR (Cordillera Administrative Region)Aurora - Region III (Central Luzon)Basilan - BARMM (Bangsamoro Region)Bataan - Region III (Central Luzon)Batanes - Region II (Cagayan Valley)Batangas - Region IV-A (CALABARZON)Benguet - CAR (Cordillera Administrative Region)Biliran - Region VIII (Eastern Visayas)Bohol - Region VII (Central Visayas)Bukidnon - Region X (NORTHERN MINDANAO)Bulacan - Region III (Central Luzon)Cagayan - Region II (Cagayan Valley)Camarines Norte - Region V (Bicol Region)Camarines Sur - Region V (Bicol Region)Camiguin - Region X (NORTHERN MINDANAO)Capiz - Region VI (Western Visayas)Catanduanes - Region V (Bicol Region)Cavite - Region IV-A (CALABARZON)Cebu - Region VII (Central Visayas)Compostela Valley - Region XI (DAVAO Region)Cotabato - Region XII (SOCCSKSARGEN)COTABATO (NORTH COTABATO) - Region XII (SOCCSKSARGEN)Davao Del Norte - Region XI (DAVAO Region)Davao Del Sur - Region XI (DAVAO Region)Davao Occidental - Region XI (DAVAO Region)Davao Oriental - Region XI (DAVAO Region)Dinagat Islands - Region XIII (CARAGA)Eastern Samar - Region VIII (Eastern Visayas)Guimaras - Region VI (Western Visayas)Ifugao - CAR (Cordillera Administrative Region)Ilocos Norte - Region I (Ilocos Region)Ilocos Sur - Region I (Ilocos Region)Iloilo - Region VI (Western Visayas)Isabela - Region II (Cagayan Valley)Kalinga - CAR (Cordillera Administrative Region)Laguna - Region IV-A (CALABARZON)Lanao Del Norte - Region X (NORTHERN MINDANAO)Lanao Del Sur - BARMM (Bangsamoro Region)La Union - Region I (Ilocos Region)Leyte - Region VIII (Eastern Visayas)Maguindanao - BARMM (Bangsamoro Region)Marinduque - Region IV-B (MiMaRoPa)Masbate - Region V (Bicol Region)Metro Manila 1st District - NCR (National Capital Region)Metro Manila 2nd District - NCR (National Capital Region)Metro Manila 3rd District - NCR (National Capital Region)Metro Manila 4th District - NCR (National Capital Region)Misamis Occidental - Region X (NORTHERN MINDANAO)Misamis Oriental - Region X (NORTHERN MINDANAO)Mountain Province - CAR (Cordillera Administrative Region)Negros Occidental - Region VI (Western Visayas)Negros Oriental - Region VII (Central Visayas)Northern Samar - Region VIII (Eastern Visayas)Nueva Ecija - Region III (Central Luzon)Nueva Vizcaya - Region II (Cagayan Valley)Occidental Mindoro - Region IV-B (MiMaRoPa)Oriental Mindoro - Region IV-B (MiMaRoPa)Palawan - Region IV-B (MiMaRoPa)Pampanga - Region III (Central Luzon)Pangasinan - Region I (Ilocos Region)Quezon - Region IV-A (CALABARZON)Quirino - Region II (Cagayan Valley)Rizal - Region IV-A (CALABARZON)Romblon - Region IV-B (MiMaRoPa)SAMAR (WESTERN SAMAR) - Region VIII (Eastern Visayas)Sarangani - Region XII (SOCCSKSARGEN)Siquijor - Region VII (Central Visayas)Sorsogon - Region V (Bicol Region)South Cotabato - Region XII (SOCCSKSARGEN)Southern Leyte - Region VIII (Eastern Visayas)Sultan Kudarat - Region XII (SOCCSKSARGEN)Sulu - BARMM (Bangsamoro Region)Surigao Del Norte - Region XIII (CARAGA)Surigao Del Sur - Region XIII (CARAGA)Tarlac - Region III (Central Luzon)Tawi-Tawi - BARMM (Bangsamoro Region)Test Aklan - XXX Region VI XXXTest Ilocos Norte - Region I (Ilocos Region)Zambales - Region III (Central Luzon)Zamboanga Del Norte - Region IX (Zamboanga Peninsula)Zamboanga Del Sur - Region IX (Zamboanga Peninsula)Zamboanga Sibugay - Region IX (Zamboanga Peninsula)</value>
      <webElementGuid>b8be40e9-65f6-4c22-83d0-82f8839ee878</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cboPhyProvince&quot;)</value>
      <webElementGuid>ea7fa98d-d051-4585-b4f4-0cdee6da4cf1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='cboPhyProvince']</value>
      <webElementGuid>7285aad0-e318-4a71-b192-94acdd5a0009</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='2']/div/div/div/div[3]/div/div/select</value>
      <webElementGuid>17dda8a8-bb1f-41e0-a878-f37e21d3e436</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div[3]/div/div/select</value>
      <webElementGuid>e0924b7f-2ab5-4ed2-a8ad-12721a6e4c73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'cboPhyProvince' and (text() = '--      Select      --Abra - CAR (Cordillera Administrative Region)Agusan Del Norte - Region XIII (CARAGA)Agusan Del Sur - Region XIII (CARAGA)Aklan - Region VI (Western Visayas)Albay - Region V (Bicol Region)Antique - Region VI (Western Visayas)Apayao - CAR (Cordillera Administrative Region)Aurora - Region III (Central Luzon)Basilan - BARMM (Bangsamoro Region)Bataan - Region III (Central Luzon)Batanes - Region II (Cagayan Valley)Batangas - Region IV-A (CALABARZON)Benguet - CAR (Cordillera Administrative Region)Biliran - Region VIII (Eastern Visayas)Bohol - Region VII (Central Visayas)Bukidnon - Region X (NORTHERN MINDANAO)Bulacan - Region III (Central Luzon)Cagayan - Region II (Cagayan Valley)Camarines Norte - Region V (Bicol Region)Camarines Sur - Region V (Bicol Region)Camiguin - Region X (NORTHERN MINDANAO)Capiz - Region VI (Western Visayas)Catanduanes - Region V (Bicol Region)Cavite - Region IV-A (CALABARZON)Cebu - Region VII (Central Visayas)Compostela Valley - Region XI (DAVAO Region)Cotabato - Region XII (SOCCSKSARGEN)COTABATO (NORTH COTABATO) - Region XII (SOCCSKSARGEN)Davao Del Norte - Region XI (DAVAO Region)Davao Del Sur - Region XI (DAVAO Region)Davao Occidental - Region XI (DAVAO Region)Davao Oriental - Region XI (DAVAO Region)Dinagat Islands - Region XIII (CARAGA)Eastern Samar - Region VIII (Eastern Visayas)Guimaras - Region VI (Western Visayas)Ifugao - CAR (Cordillera Administrative Region)Ilocos Norte - Region I (Ilocos Region)Ilocos Sur - Region I (Ilocos Region)Iloilo - Region VI (Western Visayas)Isabela - Region II (Cagayan Valley)Kalinga - CAR (Cordillera Administrative Region)Laguna - Region IV-A (CALABARZON)Lanao Del Norte - Region X (NORTHERN MINDANAO)Lanao Del Sur - BARMM (Bangsamoro Region)La Union - Region I (Ilocos Region)Leyte - Region VIII (Eastern Visayas)Maguindanao - BARMM (Bangsamoro Region)Marinduque - Region IV-B (MiMaRoPa)Masbate - Region V (Bicol Region)Metro Manila 1st District - NCR (National Capital Region)Metro Manila 2nd District - NCR (National Capital Region)Metro Manila 3rd District - NCR (National Capital Region)Metro Manila 4th District - NCR (National Capital Region)Misamis Occidental - Region X (NORTHERN MINDANAO)Misamis Oriental - Region X (NORTHERN MINDANAO)Mountain Province - CAR (Cordillera Administrative Region)Negros Occidental - Region VI (Western Visayas)Negros Oriental - Region VII (Central Visayas)Northern Samar - Region VIII (Eastern Visayas)Nueva Ecija - Region III (Central Luzon)Nueva Vizcaya - Region II (Cagayan Valley)Occidental Mindoro - Region IV-B (MiMaRoPa)Oriental Mindoro - Region IV-B (MiMaRoPa)Palawan - Region IV-B (MiMaRoPa)Pampanga - Region III (Central Luzon)Pangasinan - Region I (Ilocos Region)Quezon - Region IV-A (CALABARZON)Quirino - Region II (Cagayan Valley)Rizal - Region IV-A (CALABARZON)Romblon - Region IV-B (MiMaRoPa)SAMAR (WESTERN SAMAR) - Region VIII (Eastern Visayas)Sarangani - Region XII (SOCCSKSARGEN)Siquijor - Region VII (Central Visayas)Sorsogon - Region V (Bicol Region)South Cotabato - Region XII (SOCCSKSARGEN)Southern Leyte - Region VIII (Eastern Visayas)Sultan Kudarat - Region XII (SOCCSKSARGEN)Sulu - BARMM (Bangsamoro Region)Surigao Del Norte - Region XIII (CARAGA)Surigao Del Sur - Region XIII (CARAGA)Tarlac - Region III (Central Luzon)Tawi-Tawi - BARMM (Bangsamoro Region)Test Aklan - XXX Region VI XXXTest Ilocos Norte - Region I (Ilocos Region)Zambales - Region III (Central Luzon)Zamboanga Del Norte - Region IX (Zamboanga Peninsula)Zamboanga Del Sur - Region IX (Zamboanga Peninsula)Zamboanga Sibugay - Region IX (Zamboanga Peninsula)' or . = '--      Select      --Abra - CAR (Cordillera Administrative Region)Agusan Del Norte - Region XIII (CARAGA)Agusan Del Sur - Region XIII (CARAGA)Aklan - Region VI (Western Visayas)Albay - Region V (Bicol Region)Antique - Region VI (Western Visayas)Apayao - CAR (Cordillera Administrative Region)Aurora - Region III (Central Luzon)Basilan - BARMM (Bangsamoro Region)Bataan - Region III (Central Luzon)Batanes - Region II (Cagayan Valley)Batangas - Region IV-A (CALABARZON)Benguet - CAR (Cordillera Administrative Region)Biliran - Region VIII (Eastern Visayas)Bohol - Region VII (Central Visayas)Bukidnon - Region X (NORTHERN MINDANAO)Bulacan - Region III (Central Luzon)Cagayan - Region II (Cagayan Valley)Camarines Norte - Region V (Bicol Region)Camarines Sur - Region V (Bicol Region)Camiguin - Region X (NORTHERN MINDANAO)Capiz - Region VI (Western Visayas)Catanduanes - Region V (Bicol Region)Cavite - Region IV-A (CALABARZON)Cebu - Region VII (Central Visayas)Compostela Valley - Region XI (DAVAO Region)Cotabato - Region XII (SOCCSKSARGEN)COTABATO (NORTH COTABATO) - Region XII (SOCCSKSARGEN)Davao Del Norte - Region XI (DAVAO Region)Davao Del Sur - Region XI (DAVAO Region)Davao Occidental - Region XI (DAVAO Region)Davao Oriental - Region XI (DAVAO Region)Dinagat Islands - Region XIII (CARAGA)Eastern Samar - Region VIII (Eastern Visayas)Guimaras - Region VI (Western Visayas)Ifugao - CAR (Cordillera Administrative Region)Ilocos Norte - Region I (Ilocos Region)Ilocos Sur - Region I (Ilocos Region)Iloilo - Region VI (Western Visayas)Isabela - Region II (Cagayan Valley)Kalinga - CAR (Cordillera Administrative Region)Laguna - Region IV-A (CALABARZON)Lanao Del Norte - Region X (NORTHERN MINDANAO)Lanao Del Sur - BARMM (Bangsamoro Region)La Union - Region I (Ilocos Region)Leyte - Region VIII (Eastern Visayas)Maguindanao - BARMM (Bangsamoro Region)Marinduque - Region IV-B (MiMaRoPa)Masbate - Region V (Bicol Region)Metro Manila 1st District - NCR (National Capital Region)Metro Manila 2nd District - NCR (National Capital Region)Metro Manila 3rd District - NCR (National Capital Region)Metro Manila 4th District - NCR (National Capital Region)Misamis Occidental - Region X (NORTHERN MINDANAO)Misamis Oriental - Region X (NORTHERN MINDANAO)Mountain Province - CAR (Cordillera Administrative Region)Negros Occidental - Region VI (Western Visayas)Negros Oriental - Region VII (Central Visayas)Northern Samar - Region VIII (Eastern Visayas)Nueva Ecija - Region III (Central Luzon)Nueva Vizcaya - Region II (Cagayan Valley)Occidental Mindoro - Region IV-B (MiMaRoPa)Oriental Mindoro - Region IV-B (MiMaRoPa)Palawan - Region IV-B (MiMaRoPa)Pampanga - Region III (Central Luzon)Pangasinan - Region I (Ilocos Region)Quezon - Region IV-A (CALABARZON)Quirino - Region II (Cagayan Valley)Rizal - Region IV-A (CALABARZON)Romblon - Region IV-B (MiMaRoPa)SAMAR (WESTERN SAMAR) - Region VIII (Eastern Visayas)Sarangani - Region XII (SOCCSKSARGEN)Siquijor - Region VII (Central Visayas)Sorsogon - Region V (Bicol Region)South Cotabato - Region XII (SOCCSKSARGEN)Southern Leyte - Region VIII (Eastern Visayas)Sultan Kudarat - Region XII (SOCCSKSARGEN)Sulu - BARMM (Bangsamoro Region)Surigao Del Norte - Region XIII (CARAGA)Surigao Del Sur - Region XIII (CARAGA)Tarlac - Region III (Central Luzon)Tawi-Tawi - BARMM (Bangsamoro Region)Test Aklan - XXX Region VI XXXTest Ilocos Norte - Region I (Ilocos Region)Zambales - Region III (Central Luzon)Zamboanga Del Norte - Region IX (Zamboanga Peninsula)Zamboanga Del Sur - Region IX (Zamboanga Peninsula)Zamboanga Sibugay - Region IX (Zamboanga Peninsula)')]</value>
      <webElementGuid>510a8f6d-7d59-446f-ac91-91122b85ec53</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
