<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_--Select--BrotherBrother-in-LawCousi_e1fca2</name>
   <tag></tag>
   <elementGuidId>e7b7fd56-8330-437c-b26c-9a5e1dca3551</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='cboBenRelType1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cboBenRelType2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#cboBenRelType2</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>aad4a182-070c-471d-92da-08a4bf822bf9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cboBenRelType2</value>
      <webElementGuid>38516155-b110-4fbf-92ec-1d6835afc43b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>5193d045-de62-497b-85e1-7e1e0eaed077</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> form-select required gb-border-fcs font-9</value>
      <webElementGuid>ecbff49a-25ad-436d-b0c3-c15bde615981</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>--Select--BrotherBrother-in-LawCousinDaughterFatherFather-in-LawMotherMother-in-LawOther relativesSisterSister-in-LawSonSpouse</value>
      <webElementGuid>3fa93caf-dfe3-4bbf-aa25-85fcb5191abb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cboBenRelType2&quot;)</value>
      <webElementGuid>1c53ba74-031d-4098-830a-8795bfe6b050</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='cboBenRelType2']</value>
      <webElementGuid>611d1fd5-3889-4d37-ae4e-0272d0c18f7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='row2']/div/div[3]/div/div/select</value>
      <webElementGuid>d09248d6-2a78-4e02-9dc8-b2dfdf56bc80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remarks:'])[1]/following::select[8]</value>
      <webElementGuid>f5751627-614d-4995-87f5-25664bf26b5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Additional Beneficiary If any'])[1]/preceding::select[7]</value>
      <webElementGuid>31f58048-8a90-487d-9628-c4f45dfaef31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Client Risk Assessment'])[2]/preceding::select[7]</value>
      <webElementGuid>a55dcd15-ce6d-4061-9c66-ac231bac6c31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div[3]/div/div/select</value>
      <webElementGuid>0fc1ac8a-c7de-451a-aa12-53698aaf629f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'cboBenRelType2' and (text() = '--Select--BrotherBrother-in-LawCousinDaughterFatherFather-in-LawMotherMother-in-LawOther relativesSisterSister-in-LawSonSpouse' or . = '--Select--BrotherBrother-in-LawCousinDaughterFatherFather-in-LawMotherMother-in-LawOther relativesSisterSister-in-LawSonSpouse')]</value>
      <webElementGuid>ee97cbad-9887-45bf-aca9-db31d278f095</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
