<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_--      Select      --AgdanganAlabat_8d941c</name>
   <tag></tag>
   <elementGuidId>5574feb6-27f4-49eb-bfeb-82b77586b6f3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='cboPhyMunicipalityCity']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cboPhyMunicipalityCity</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#cboPhyMunicipalityCity</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>99dd783c-8322-4ba5-8fd2-e6e512325199</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cboPhyMunicipalityCity</value>
      <webElementGuid>b53869a9-e793-41cb-bd56-4a934e8e5847</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-select gb-border-fcs font-11</value>
      <webElementGuid>d5c2201e-547e-4c9e-ae46-cc17a26148b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>--      Select      --AgdanganAlabatAtimonanBuenavistaBurdeosCalauagCandelariaCatanauanDoloresGeneral LunaGeneral NakarGuinayanganGumacaInfantaJomaligLopezLucbanLucena CityMacalelonMaubanMulanayPadre BurgosPagbilaoPanukulanPatnanunganPerezPitogoPlaridelPolilloQuezonRealSampalocSan AndresSan AntonioSan Francisco (Aurora)San NarcisoSariayaTagkawayanTayabas CityTiaongUnisan</value>
      <webElementGuid>d3369647-d43d-4bcc-b0ad-7fb29a70d7f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cboPhyMunicipalityCity&quot;)</value>
      <webElementGuid>c9bbfa70-f4cd-4f48-bf48-2518831a9451</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='cboPhyMunicipalityCity']</value>
      <webElementGuid>0b335526-d681-46f8-9371-a08867568f65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='2']/div/div/div/div[4]/div/div/select</value>
      <webElementGuid>f7252582-50dd-4a94-a4f7-b6e97b504d81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div[4]/div/div/select</value>
      <webElementGuid>f7ed55a6-1f08-4102-bf71-a8675352e8fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'cboPhyMunicipalityCity' and (text() = '--      Select      --AgdanganAlabatAtimonanBuenavistaBurdeosCalauagCandelariaCatanauanDoloresGeneral LunaGeneral NakarGuinayanganGumacaInfantaJomaligLopezLucbanLucena CityMacalelonMaubanMulanayPadre BurgosPagbilaoPanukulanPatnanunganPerezPitogoPlaridelPolilloQuezonRealSampalocSan AndresSan AntonioSan Francisco (Aurora)San NarcisoSariayaTagkawayanTayabas CityTiaongUnisan' or . = '--      Select      --AgdanganAlabatAtimonanBuenavistaBurdeosCalauagCandelariaCatanauanDoloresGeneral LunaGeneral NakarGuinayanganGumacaInfantaJomaligLopezLucbanLucena CityMacalelonMaubanMulanayPadre BurgosPagbilaoPanukulanPatnanunganPerezPitogoPlaridelPolilloQuezonRealSampalocSan AndresSan AntonioSan Francisco (Aurora)San NarcisoSariayaTagkawayanTayabas CityTiaongUnisan')]</value>
      <webElementGuid>92bc5b46-cde3-4b21-8263-9f40f5a1020a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
