<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_--Select--YESNO_1</name>
   <tag></tag>
   <elementGuidId>89e4f5b2-45bf-4cec-b1a0-3a3d577a492f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='cboCardMRIScho1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cboCardMRIScho2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#cboCardMRIScho2</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>145b170a-6d24-485f-8a9b-3465b43471b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cboCardMRIScho2</value>
      <webElementGuid>81cf0c83-29f6-491e-b4dc-098df720298e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>ab0c5216-a2d1-4bde-b123-251533fa8a77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> form-select required gb-border-fcs font-9</value>
      <webElementGuid>adc99c84-6309-449f-bb29-b75cfa389a20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
					--Select--
					YES
					NO
				</value>
      <webElementGuid>068fe8d5-78dd-4ee4-8899-b3382d532ac1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cboCardMRIScho2&quot;)</value>
      <webElementGuid>fb407948-1a32-4fba-9128-7473040a8952</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='cboCardMRIScho2']</value>
      <webElementGuid>466ea759-11cf-47d4-9533-f53a0ec4240b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='row2']/div/div[9]/div/div/select</value>
      <webElementGuid>6d2f0628-dbc4-420a-ad03-995bf11e6024</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remarks:'])[1]/following::select[13]</value>
      <webElementGuid>75bdcb58-92c5-4f58-aab8-7f4e8c5d508f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Additional Beneficiary If any'])[1]/preceding::select[2]</value>
      <webElementGuid>673b0d11-b2bc-485a-8da5-f3416a1dae17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Client Risk Assessment'])[2]/preceding::select[2]</value>
      <webElementGuid>d7d2c35a-0c5b-4d79-9457-b77f798fb645</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div[9]/div/div/select</value>
      <webElementGuid>6ef10ad2-ceaa-4693-b9f8-2c4aec9ebe13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'cboCardMRIScho2' and (text() = '
					--Select--
					YES
					NO
				' or . = '
					--Select--
					YES
					NO
				')]</value>
      <webElementGuid>e2c4d699-88ed-46d4-b9d9-1ad17d67df66</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
