<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_--      Select      --villagevillage_79bc42</name>
   <tag></tag>
   <elementGuidId>596b7308-422c-40c4-8316-864790b973f5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='cboCustomerCenter']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cboCustomerCenter</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#cboCustomerCenter</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>a0607089-9983-44c8-8bd0-a57132829b21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cboCustomerCenter</value>
      <webElementGuid>5f670bf3-811d-4c08-8e4d-cedacb74494e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-select gb-border-fcs select2 font-11</value>
      <webElementGuid>d9d9bf8b-4f23-428d-9056-d685122a442a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>select2</value>
      <webElementGuid>96d72054-459e-4d8a-9a5b-9a6ebf77c404</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>--      Select      --villagevillage 2village 3Village 4Village 5village 9village 8Village 7Village 6</value>
      <webElementGuid>a5728d8a-a4c7-427b-a299-1bd43cece489</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cboCustomerCenter&quot;)</value>
      <webElementGuid>0dca51c5-9c04-4618-8435-da0f95e1fc91</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='cboCustomerCenter']</value>
      <webElementGuid>e2ffd4ae-3c72-43c3-8fc4-5c4ca41a7264</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='myform']/div[2]/div[20]/div/div/select</value>
      <webElementGuid>026c2cc2-3ba3-444f-ad46-ddfdf7ff343a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CARD MRI Scholar :'])[1]/preceding::select[2]</value>
      <webElementGuid>23dc17f3-af75-4338-869a-a1ca45e40080</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[20]/div/div/select</value>
      <webElementGuid>bc7801eb-0cd3-4012-950d-2b2ad3196065</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'cboCustomerCenter' and (text() = '--      Select      --villagevillage 2village 3Village 4Village 5village 9village 8Village 7Village 6' or . = '--      Select      --villagevillage 2village 3Village 4Village 5village 9village 8Village 7Village 6')]</value>
      <webElementGuid>55bf35fe-be20-42e1-b36b-8cd46f6f413e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
