<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_--Select--YESNO</name>
   <tag></tag>
   <elementGuidId>77ef3db0-b965-4f6f-946c-2428b2de1fc7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='cboWithDisability1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cboWithDisability2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#cboWithDisability2</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>b8d8ea15-a97c-43cf-917b-d6492d914b31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cboWithDisability2</value>
      <webElementGuid>76b8dc1c-49be-4471-b4c3-7df3d677eb07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>beneficiaryDisability();</value>
      <webElementGuid>3392c582-02fe-44ab-bf47-be11dcc0ff1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>2795279c-bc32-4333-a9a3-92f078b7114c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> form-select required gb-border-fcs font-9</value>
      <webElementGuid>7a6abfe3-4c84-4b73-b488-1ea6286dc127</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
					--Select--
					YES
					NO
				</value>
      <webElementGuid>bed2393e-0e3e-4c9f-9161-16d920126a5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cboWithDisability2&quot;)</value>
      <webElementGuid>c35bba74-53b0-4425-8840-a2e022523173</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='cboWithDisability2']</value>
      <webElementGuid>a9585ee9-a799-4ed9-a89d-6746b417b1b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='row2']/div/div[7]/div/div/select</value>
      <webElementGuid>c1e3fe60-9447-4f7e-9200-008d0d46eb08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remarks:'])[1]/following::select[12]</value>
      <webElementGuid>83f3c697-581a-4cf3-8752-3122a0ce30dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Additional Beneficiary If any'])[1]/preceding::select[3]</value>
      <webElementGuid>f43e257b-bd9b-4d07-acdd-a2602f963d63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Client Risk Assessment'])[2]/preceding::select[3]</value>
      <webElementGuid>713891ea-e15a-4c3c-8b12-b246b1c8b2bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div[7]/div/div/select</value>
      <webElementGuid>cd96317e-2396-42b1-bb70-f8636fce4539</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'cboWithDisability2' and (text() = '
					--Select--
					YES
					NO
				' or . = '
					--Select--
					YES
					NO
				')]</value>
      <webElementGuid>1e680570-4605-466a-b4da-f6c57061d334</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
