<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_--Select--Adasen InlaudAetaAetaAlang_82eebf</name>
   <tag></tag>
   <elementGuidId>4c6f84f3-5665-4b29-a23d-9f790f40a463</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='cboTribetype']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cboTribetype</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#cboTribetype</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>75a36e46-c733-4fc0-9a87-229d048c9d89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cboTribetype</value>
      <webElementGuid>04634ec0-d41f-4f9c-9be4-94da086fe8b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-select gb-border-fcs select2 font-11</value>
      <webElementGuid>51d6ec2a-e956-4e21-a8da-75267b3676ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>select2</value>
      <webElementGuid>aff4e574-bb8f-44fd-b745-819971f4fd5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>--Select--Adasen InlaudAetaAetaAlanganAlangan Mangyan TribeApplaiATA manoboATA tribeAtiAyanganBadjaoBadjaoBagoboBago- KankanaeyBanwaonbasaoBilaan, manobo kauloBilaan ,Manobo KauloBlaanBontok TribeBugkalot/Ilongot/Kankana-EyBuhid Mangyan TribeBukkalotDibabawonHanunuo Mangyan TribeHiagaononHigaononHigaonon/ ManoboIbaloiIbaloi/ Kankanaey/ IgorotIbaloy/ Kankamaey/IgorotIlocano-KankanaeyIlongot/BugkalotInlaodiraya, alanganIraya Mangyan TribeIsnagIsnag ( Imalawa)ItnegKalangoya/Bugkalot/IlongotKalangoya/Kankana-EKalanguya(Kalanguya,Ifugao)Kalibugan,TausugKali-ekankanaeyKankana-EyKankanaey/IbaloiKankanaey/Ibaloi/ KalanguyaKankana-Ey/KalangoyaKannanaey/ IgorotLumadMaengMa-gantiMaguindanaoManaboMandayaMangyan BukidManoboManobo/ MatigsalogMansakaManuboMaranaoMasadiitMatigsalogMolbogMuslimMuslim MaguindanaoMuslim MaguindanawanMuslim PalauanMuyadanName Of MamanwaName Of Tribe Or Ethnic Group: AgtaName Of Tribe Or Ethnic Group: Agta And IlongotPalauanPalawanoSamalSubanenSubanen TribeSubaninSubanin, MuslimSubanonSumadelTadyawan Mangyan TribeTagabawaTalaandigTalaandig/ManaboTalaandig/ ManoboTausogTausugTboliTboli/ MuslimTboli/MuslimTidurayTiguianTigwanahonTuwaliTuwali &amp; AyanganUmayamnon- BulonayYatuka</value>
      <webElementGuid>51e675f9-892e-4f18-9873-5d75ec2e8b7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cboTribetype&quot;)</value>
      <webElementGuid>df553d21-a1fc-48df-ae57-c20326f6b5e3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='cboTribetype']</value>
      <webElementGuid>9685ddaa-6557-44ee-9cfc-b2e08f42a719</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='8']/div/div/div/div[4]/div[2]/div/select</value>
      <webElementGuid>aed3dca2-397b-4355-95b6-df14a8179ff4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total Score:'])[1]/following::select[2]</value>
      <webElementGuid>8a0efc8b-505c-41ca-aa51-a4bae2347985</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Health Declaration'])[1]/preceding::select[1]</value>
      <webElementGuid>b6317ddd-0037-4cbf-b39e-eb89bd7b9b4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='YES'])[13]/preceding::select[1]</value>
      <webElementGuid>a4a44556-b4e9-4de6-ad3f-cc957b51c312</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/select</value>
      <webElementGuid>88695ced-7fd8-4378-b1a0-ef2f33f7b0cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'cboTribetype' and (text() = '--Select--Adasen InlaudAetaAetaAlanganAlangan Mangyan TribeApplaiATA manoboATA tribeAtiAyanganBadjaoBadjaoBagoboBago- KankanaeyBanwaonbasaoBilaan, manobo kauloBilaan ,Manobo KauloBlaanBontok TribeBugkalot/Ilongot/Kankana-EyBuhid Mangyan TribeBukkalotDibabawonHanunuo Mangyan TribeHiagaononHigaononHigaonon/ ManoboIbaloiIbaloi/ Kankanaey/ IgorotIbaloy/ Kankamaey/IgorotIlocano-KankanaeyIlongot/BugkalotInlaodiraya, alanganIraya Mangyan TribeIsnagIsnag ( Imalawa)ItnegKalangoya/Bugkalot/IlongotKalangoya/Kankana-EKalanguya(Kalanguya,Ifugao)Kalibugan,TausugKali-ekankanaeyKankana-EyKankanaey/IbaloiKankanaey/Ibaloi/ KalanguyaKankana-Ey/KalangoyaKannanaey/ IgorotLumadMaengMa-gantiMaguindanaoManaboMandayaMangyan BukidManoboManobo/ MatigsalogMansakaManuboMaranaoMasadiitMatigsalogMolbogMuslimMuslim MaguindanaoMuslim MaguindanawanMuslim PalauanMuyadanName Of MamanwaName Of Tribe Or Ethnic Group: AgtaName Of Tribe Or Ethnic Group: Agta And IlongotPalauanPalawanoSamalSubanenSubanen TribeSubaninSubanin, MuslimSubanonSumadelTadyawan Mangyan TribeTagabawaTalaandigTalaandig/ManaboTalaandig/ ManoboTausogTausugTboliTboli/ MuslimTboli/MuslimTidurayTiguianTigwanahonTuwaliTuwali &amp; AyanganUmayamnon- BulonayYatuka' or . = '--Select--Adasen InlaudAetaAetaAlanganAlangan Mangyan TribeApplaiATA manoboATA tribeAtiAyanganBadjaoBadjaoBagoboBago- KankanaeyBanwaonbasaoBilaan, manobo kauloBilaan ,Manobo KauloBlaanBontok TribeBugkalot/Ilongot/Kankana-EyBuhid Mangyan TribeBukkalotDibabawonHanunuo Mangyan TribeHiagaononHigaononHigaonon/ ManoboIbaloiIbaloi/ Kankanaey/ IgorotIbaloy/ Kankamaey/IgorotIlocano-KankanaeyIlongot/BugkalotInlaodiraya, alanganIraya Mangyan TribeIsnagIsnag ( Imalawa)ItnegKalangoya/Bugkalot/IlongotKalangoya/Kankana-EKalanguya(Kalanguya,Ifugao)Kalibugan,TausugKali-ekankanaeyKankana-EyKankanaey/IbaloiKankanaey/Ibaloi/ KalanguyaKankana-Ey/KalangoyaKannanaey/ IgorotLumadMaengMa-gantiMaguindanaoManaboMandayaMangyan BukidManoboManobo/ MatigsalogMansakaManuboMaranaoMasadiitMatigsalogMolbogMuslimMuslim MaguindanaoMuslim MaguindanawanMuslim PalauanMuyadanName Of MamanwaName Of Tribe Or Ethnic Group: AgtaName Of Tribe Or Ethnic Group: Agta And IlongotPalauanPalawanoSamalSubanenSubanen TribeSubaninSubanin, MuslimSubanonSumadelTadyawan Mangyan TribeTagabawaTalaandigTalaandig/ManaboTalaandig/ ManoboTausogTausugTboliTboli/ MuslimTboli/MuslimTidurayTiguianTigwanahonTuwaliTuwali &amp; AyanganUmayamnon- BulonayYatuka')]</value>
      <webElementGuid>b95a8b3c-f814-4c71-97dc-ded73454f3fc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
