<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_--      Select      --0 - 7 o higit _f836c6</name>
   <tag></tag>
   <elementGuidId>d81b568a-c325-43e6-bb9d-29531bcc0a95</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='cbosecondQAnswer']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cbosecondQAnswer</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#cbosecondQAnswer</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>9e691ad0-fb8e-4fc4-b5e0-c21494e29f14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>validatelenght required gb-border-fcs form-select  Ans</value>
      <webElementGuid>18a6d61e-837a-4656-9a7c-435d7eec7ad0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cbosecondQAnswer</value>
      <webElementGuid>15f424ec-c091-4877-a53a-9f1eaa6e94d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>--      Select      --[0] - 7 o higit pa[9] - 5 - 6[18] - 4 pababa</value>
      <webElementGuid>66373d3c-aeb6-419b-b8c5-ed7d82cae35b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cbosecondQAnswer&quot;)</value>
      <webElementGuid>f7976fb3-ce52-46d9-923e-b60c518f403d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='cbosecondQAnswer']</value>
      <webElementGuid>f777f47e-5d14-4a4f-9016-f9963ad222f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='tblPPIBodySecond']/tr/td[2]/select</value>
      <webElementGuid>037d5189-14ae-4da7-b608-4d597f06ae63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mga Indikasyon/Indicators'])[1]/preceding::select[9]</value>
      <webElementGuid>20016cc3-d6f3-4402-abd7-73b7d6307839</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Puntos'])[1]/preceding::select[9]</value>
      <webElementGuid>f92b1420-bf42-41dc-8519-e92e0c48db65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tbody[2]/tr/td[2]/select</value>
      <webElementGuid>a0409ae8-4709-4939-8e37-c47f35a84d98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'cbosecondQAnswer' and (text() = '--      Select      --[0] - 7 o higit pa[9] - 5 - 6[18] - 4 pababa' or . = '--      Select      --[0] - 7 o higit pa[9] - 5 - 6[18] - 4 pababa')]</value>
      <webElementGuid>1864ce1a-5099-4f0c-857e-477ddcddf99f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
