<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_--Select--Barangay CertificateBIR TI_0033e0</name>
   <tag></tag>
   <elementGuidId>734d3668-02df-4247-9f4d-419937ba24c0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='cboIDType']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cboIDType</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#cboIDType</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>e68a3038-6010-4011-93e3-cc7c3871b0bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cboIDType</value>
      <webElementGuid>05866a98-684a-4364-aa53-53c02ea526b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>IdPresented();</value>
      <webElementGuid>8bc87898-0164-473c-a4a3-1d26771e13f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-select gb-border-fcs font-11</value>
      <webElementGuid>67509646-6073-4b31-96d6-49427b2af0e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>--Select--Barangay CertificateBIR TINCompany IDDriver's License IDGSIS IDNBI ClearanceOWWA IDPag-IBIG IDPassportPhilHealth IDPostal IDPRC IDSenior Citizen IDSSS IDUMIDVoter's ID</value>
      <webElementGuid>ddd5021f-986c-4efa-8fc2-c765887aca75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cboIDType&quot;)</value>
      <webElementGuid>9454014d-18c7-46d0-98fd-0f211cb5b40c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='cboIDType']</value>
      <webElementGuid>434c4513-4463-46a1-a9ce-dd77a62d6bcf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='3']/div/div/div/div[2]/div/div/select</value>
      <webElementGuid>51fc63f7-c7d0-4080-839f-398829844115</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ID Presented'])[1]/following::select[1]</value>
      <webElementGuid>d1c9fa33-4d8d-4560-9b4f-c5d62e4fc3f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div[2]/div/div/select</value>
      <webElementGuid>e88517e0-b681-4cc0-8e01-d0443b945be4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'cboIDType' and (text() = concat(&quot;--Select--Barangay CertificateBIR TINCompany IDDriver&quot; , &quot;'&quot; , &quot;s License IDGSIS IDNBI ClearanceOWWA IDPag-IBIG IDPassportPhilHealth IDPostal IDPRC IDSenior Citizen IDSSS IDUMIDVoter&quot; , &quot;'&quot; , &quot;s ID&quot;) or . = concat(&quot;--Select--Barangay CertificateBIR TINCompany IDDriver&quot; , &quot;'&quot; , &quot;s License IDGSIS IDNBI ClearanceOWWA IDPag-IBIG IDPassportPhilHealth IDPostal IDPRC IDSenior Citizen IDSSS IDUMIDVoter&quot; , &quot;'&quot; , &quot;s ID&quot;))]</value>
      <webElementGuid>d98fdd4c-08b7-413e-86e6-96e7167e77cf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
