<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_--Select--BeneficiaryLegal Dependent_a71cea</name>
   <tag></tag>
   <elementGuidId>d51111e9-5b73-47a2-a236-04ae351bf887</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='cboRemarks1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cboRemarks2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#cboRemarks2</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>1c1b6dc3-87bb-4c10-b5f8-604245f1a2aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cboRemarks2</value>
      <webElementGuid>18bcd217-a6d8-4c34-bcfc-9071364b1c4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>07133f7d-e1ba-4aff-a31b-b320d1318a53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>beneficiaryRemarks($('#txtBeneficiaryBday2').val(), $('#cboWithDisability2').val(),$('#cboRemarks2').val(),'#cboRemarks2');</value>
      <webElementGuid>c9157b85-037b-41b2-9765-2f9301028b00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-select required gb-border-fcs font-9</value>
      <webElementGuid>4e4072c8-7ebe-4e02-8d77-71b8bdd4d8b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>--Select--BeneficiaryLegal DependentLegal Dependent and Beneficiary</value>
      <webElementGuid>4390e5e1-b66d-467b-af45-e09f3c095ec4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cboRemarks2&quot;)</value>
      <webElementGuid>76fdfb73-d9e4-4041-81ff-afbb983fa92d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='cboRemarks2']</value>
      <webElementGuid>ef7e11c3-6965-44c6-b461-4d89773bdf1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='row2']/div/div[10]/div/div/select</value>
      <webElementGuid>6f70da9e-6eed-4ef6-847c-0f77328da0d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remarks:'])[1]/following::select[14]</value>
      <webElementGuid>9329c31c-d762-4a65-908b-e891646486d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Additional Beneficiary If any'])[1]/preceding::select[1]</value>
      <webElementGuid>24988233-07e7-427c-80e3-05ff46e16821</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Client Risk Assessment'])[2]/preceding::select[1]</value>
      <webElementGuid>7cf894de-fc7c-4eeb-a34e-e29a75e7c785</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div[10]/div/div/select</value>
      <webElementGuid>316b7122-c7b6-4dd5-a253-a10fa66ba6f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'cboRemarks2' and (text() = '--Select--BeneficiaryLegal DependentLegal Dependent and Beneficiary' or . = '--Select--BeneficiaryLegal DependentLegal Dependent and Beneficiary')]</value>
      <webElementGuid>8b911f67-8a2f-43af-8083-98424835de24</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
