<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_--      Select      --0 - Magaang ma_840447</name>
   <tag></tag>
   <elementGuidId>51dc00f7-5661-458a-a8d8-4d50cd10de17</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='cbofifthQAnswer']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cbofifthQAnswer</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#cbofifthQAnswer</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>87fecf30-48a9-4093-a894-c53b91333323</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>validatelenght required gb-border-fcs form-select  Ans</value>
      <webElementGuid>a1bb8d31-099b-477f-98b6-abf4fb80665d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cbofifthQAnswer</value>
      <webElementGuid>7e6bd53b-7b4b-44f8-849a-dd90c9846b0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>--      Select      --[0] - Magaang materyales (kawayan, sawali,cogon, nipa, anahaw), Isinalba/ pansamantalang materyales, Magkahalo ngunit mas marami ang magagaang materyales, Magkahalo ngunit mas maraming isinalbang materyales[7] - Magkahalo ngunit mas maraming matitibay na materyales[8] - Matitibay na materyales (yero, aluminum, tile, semento, brick, bato, kahoy, plywood, asbestos)</value>
      <webElementGuid>ae7a1d63-5e41-470f-bac1-6e8d53bd1f43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cbofifthQAnswer&quot;)</value>
      <webElementGuid>d44fea46-d306-495e-82e7-bbbcb44cfde2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='cbofifthQAnswer']</value>
      <webElementGuid>3a971564-1f1e-4243-9524-3c75ac321ac2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='tblPPIBodyFifth']/tr/td[2]/select</value>
      <webElementGuid>063f9a11-0090-45c6-bd89-ef08bfb3d8d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mga Indikasyon/Indicators'])[1]/preceding::select[6]</value>
      <webElementGuid>aae7d930-4894-4649-9e49-748a0938d33b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Puntos'])[1]/preceding::select[6]</value>
      <webElementGuid>9d7d5df7-3678-4528-bd71-f65e54e7a1fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tbody[5]/tr/td[2]/select</value>
      <webElementGuid>f2c2f1de-067f-44e9-8379-c749b20ac968</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'cbofifthQAnswer' and (text() = '--      Select      --[0] - Magaang materyales (kawayan, sawali,cogon, nipa, anahaw), Isinalba/ pansamantalang materyales, Magkahalo ngunit mas marami ang magagaang materyales, Magkahalo ngunit mas maraming isinalbang materyales[7] - Magkahalo ngunit mas maraming matitibay na materyales[8] - Matitibay na materyales (yero, aluminum, tile, semento, brick, bato, kahoy, plywood, asbestos)' or . = '--      Select      --[0] - Magaang materyales (kawayan, sawali,cogon, nipa, anahaw), Isinalba/ pansamantalang materyales, Magkahalo ngunit mas marami ang magagaang materyales, Magkahalo ngunit mas maraming isinalbang materyales[7] - Magkahalo ngunit mas maraming matitibay na materyales[8] - Matitibay na materyales (yero, aluminum, tile, semento, brick, bato, kahoy, plywood, asbestos)')]</value>
      <webElementGuid>9a1889d4-1db5-4340-8458-d6f07c3159a1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
