<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_--Select--BusinessGovernment Employe_69ab64</name>
   <tag></tag>
   <elementGuidId>3a316beb-0bbf-44e7-b7b7-d2a862ac129a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='cboSpouseOccupation']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cboSpouseOccupation</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#cboSpouseOccupation</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>d9e1ad1e-e4cd-4b46-b65e-bb06e60496a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cboSpouseOccupation</value>
      <webElementGuid>e8f186e4-7ad2-44a5-8e37-a763bf7f4c04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>df5c891d-e9a4-41aa-ac82-ccd22407c740</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-select gb-border-fcs font-11</value>
      <webElementGuid>0d468bdc-4ba4-44ac-81c1-5a5830c4256d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>--Select--BusinessGovernment EmployeeOthersPrivate Emplovee</value>
      <webElementGuid>14492826-6a61-402d-b86e-5c123bab00ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cboSpouseOccupation&quot;)</value>
      <webElementGuid>11020204-395a-4d56-9012-9050a6ebc70e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='cboSpouseOccupation']</value>
      <webElementGuid>924474b6-8be7-4d84-845b-3e0f64542a9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='5']/div/div/div[2]/div[2]/div/div[3]/div/div/select</value>
      <webElementGuid>0e2feebb-9360-4373-bbb4-b950fc4aaa68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div[3]/div/div/select</value>
      <webElementGuid>06ad8055-5a01-47eb-8a54-1f5d9e7dfdbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'cboSpouseOccupation' and (text() = '--Select--BusinessGovernment EmployeeOthersPrivate Emplovee' or . = '--Select--BusinessGovernment EmployeeOthersPrivate Emplovee')]</value>
      <webElementGuid>73de26cd-1b18-4dc7-8519-b01daad9a4a3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
