<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_i_swal2-success-ring</name>
   <tag></tag>
   <elementGuidId>d83dd213-ae03-4b19-8b86-7b5d635fbfd9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@class=&quot;swal2-success-ring&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.swal2-success-ring</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.swal2-success-ring</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>0e6c76eb-ea1b-412a-a57b-8542071774b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>swal2-success-ring</value>
      <webElementGuid>20c9cc49-16c8-4edd-85c7-371d837eaabe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;body&quot;)/div[@class=&quot;swal2-container swal2-center swal2-fade swal2-shown&quot;]/div[@class=&quot;swal2-popup swal2-modal swal2-show&quot;]/div[@class=&quot;swal2-header&quot;]/div[@class=&quot;swal2-icon swal2-success swal2-animate-success-icon&quot;]/div[@class=&quot;swal2-success-ring&quot;]</value>
      <webElementGuid>4145724a-0b85-471c-b049-e404b957e19e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='body']/div[9]/div/div/div[5]/div[2]</value>
      <webElementGuid>fb530a4d-ec3a-4f32-b7d0-b32626b67ba8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/div/div[5]/div[2]</value>
      <webElementGuid>2bf66b71-b01d-44d6-8c83-9b200abf5800</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
