<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_AddAnother Income</name>
   <tag></tag>
   <elementGuidId>47022709-182b-45d4-bc6c-7aa88125aca2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='add-income-button']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#add-income-button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>af633ea4-9d7d-41de-93fb-ebdb856c9474</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>add-income-button</value>
      <webElementGuid>efddc28b-d70b-480c-9b14-f4b8d7adc8bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>34591145-9d75-4a3e-91ec-f418abb4a9d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-info</value>
      <webElementGuid>65ebfdfa-eff7-4964-a719-ffd19613cd72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add
														Another Income</value>
      <webElementGuid>324b49a6-1c24-4d1c-998a-d69c61d6a0c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;add-income-button&quot;)</value>
      <webElementGuid>13027c09-373f-4dda-886d-abbd72d16711</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='add-income-button']</value>
      <webElementGuid>4e629e9e-4cfa-408c-8ee1-4519d9d2dc94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cashflow1']/div/div/div[3]/div/div[2]/div/div/div/div/div[3]/div/button</value>
      <webElementGuid>bec99379-f1fe-4599-954c-7e7ab94a3091</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/button</value>
      <webElementGuid>98ebf397-3e47-4e0a-b575-355ade75039a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'add-income-button' and @type = 'button' and (text() = 'Add
														Another Income' or . = 'Add
														Another Income')]</value>
      <webElementGuid>60bdb612-d70f-4161-ba7c-35b66fd4b42f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
