<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputtxtTotalIncome</name>
   <tag></tag>
   <elementGuidId>c47bb838-4a91-45dd-a69a-dff3defa0630</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtTotalIncome']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#txtTotalIncome</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5c7c51e6-1f35-410c-97b8-273c564146e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>23ad6d7d-22fa-437f-ac74-1264dbd6acc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>49ab25d2-1669-4701-8672-06c5dffe0ca4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control computeCashflow gb-border-fcs keep-disabled font-12</value>
      <webElementGuid>c1389b1c-7d11-4ac4-a761-75e841c41707</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtTotalIncome</value>
      <webElementGuid>e2eeb705-a4f2-4dc9-b6c1-f17f64da2ce9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtTotalIncome&quot;)</value>
      <webElementGuid>b3c53f19-84e8-4ec9-94d4-7494ff396a46</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtTotalIncome']</value>
      <webElementGuid>00c5b1a1-358d-4190-80ec-db0625aefd3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cashflow1']/div/div/div[3]/div/div[2]/div/div/div/div/div[3]/div[3]/div/input</value>
      <webElementGuid>f4ed38d7-896c-407d-a1f1-818878bf7ef3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[3]/div/input</value>
      <webElementGuid>e521e2f3-240c-4a0e-a30e-5fc8234c649b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'txtTotalIncome']</value>
      <webElementGuid>d0491bf2-c85e-4edf-90b7-e7ffa7330239</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
