<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputtxtrowExpenseAmount1</name>
   <tag></tag>
   <elementGuidId>1ce0509a-1b87-4ad4-a851-249e8c2f98d1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtrowExpenseAmount1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#txtrowExpenseAmount1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d8db87c1-679b-410a-a5b6-fb09eea8e2a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>6d095a96-1a76-4093-9ab8-9bb17a535eb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9886d323-f49c-48aa-9ee0-d286df18ef20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control required gb-border-fcs</value>
      <webElementGuid>45429de8-13ca-4cf6-9e71-959ca563b603</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtrowExpenseAmount1</value>
      <webElementGuid>66940391-60ad-460b-8705-fa3ff60629f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtrowExpenseAmount1&quot;)</value>
      <webElementGuid>e454f5df-3256-475c-b6b2-8069bb36a3ea</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtrowExpenseAmount1']</value>
      <webElementGuid>f76b0abf-3eb5-4490-a0a1-f0eeccb07254</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='inputRow2']/div[2]/div/div/input</value>
      <webElementGuid>0007801c-79f7-432d-8dcb-9fbadd74deeb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div/div/div/div/div[5]/div/div/div[2]/div/div/input</value>
      <webElementGuid>da4d19b2-5c52-4f44-824f-3ebf6a2bda89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'txtrowExpenseAmount1']</value>
      <webElementGuid>0c619166-e1ec-4ab1-be88-5526ad8e7e87</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
