<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputtxtrowExpenseAmount2</name>
   <tag></tag>
   <elementGuidId>b814d241-06c8-4843-9367-488a405534fc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtrowExpenseAmount2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#txtrowExpenseAmount2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ffcff8d3-99c1-4721-bce3-1c7b6993e505</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>ce8bc61f-a056-4445-97df-779671c119a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5b78c598-c2b1-4e39-80e7-f853c715113a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control required gb-border-fcs</value>
      <webElementGuid>ee1074c3-875e-44ae-9beb-5c8beaaffde3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtrowExpenseAmount2</value>
      <webElementGuid>2bd829c3-0f62-4b1c-acaa-fb112cd2703a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtrowExpenseAmount2&quot;)</value>
      <webElementGuid>a25017a9-c769-4c77-9c04-9b59accbbf76</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtrowExpenseAmount2']</value>
      <webElementGuid>e433819a-9923-4c2a-9f10-3dadb776fa16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='inputRow2']/div[2]/div/div/input)[2]</value>
      <webElementGuid>952f4bd6-db27-4534-987f-a056a5fa2f4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div[5]/div[2]/div/div[2]/div/div/input</value>
      <webElementGuid>69317c2b-184c-4ae6-84b3-48ccec7e0362</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'txtrowExpenseAmount2']</value>
      <webElementGuid>0cbde370-ac43-42f9-8ca9-afaff26f9648</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
