<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_-- Select --FoodWaterElectricityEduc_adf9e8</name>
   <tag></tag>
   <elementGuidId>fefab5c5-d7b7-425f-a014-3383dd3797d4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='cborowExpense1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cborowExpense1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>bb2f4e39-058e-4abb-9322-514e11c8e98f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-select required gb-border-fcs</value>
      <webElementGuid>251b2c43-7d44-41cf-9367-0c2618bb7c90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cborowExpense1</value>
      <webElementGuid>10410583-157b-4df4-8552-4b9d793d34ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-- Select --FoodWaterElectricityEducation/TuitionSalary of  WorkersAllowances and TransportationTransportation/GasolineClothingEntertainment/RecreationMedical ExpensesAmortization of  other loansHouse rentalOthers</value>
      <webElementGuid>193d50a9-a8fd-4f06-b805-6f7969ca9dfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cborowExpense1&quot;)</value>
      <webElementGuid>abc36fdf-620a-46b6-95c4-eb9d936ecbed</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='cborowExpense1']</value>
      <webElementGuid>78295a3e-1a5b-4cf1-9682-b6bbd84e0c7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='inputRow2']/div/div/select</value>
      <webElementGuid>7a74b72c-448e-4e69-9575-cb43df3c61a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div[5]/div/div/div/div/select</value>
      <webElementGuid>638c554d-465f-438a-a6ec-3cdba05aa330</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'cborowExpense1' and (text() = '-- Select --FoodWaterElectricityEducation/TuitionSalary of  WorkersAllowances and TransportationTransportation/GasolineClothingEntertainment/RecreationMedical ExpensesAmortization of  other loansHouse rentalOthers' or . = '-- Select --FoodWaterElectricityEducation/TuitionSalary of  WorkersAllowances and TransportationTransportation/GasolineClothingEntertainment/RecreationMedical ExpensesAmortization of  other loansHouse rentalOthers')]</value>
      <webElementGuid>8043e68f-1b31-4eef-b296-9525c28baa12</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
