<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_(Open)_rounded-circle</name>
   <tag></tag>
   <elementGuidId>60999415-9d17-4e69-8b3b-8649886ebb0c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body[@id='body']/div/div/div/ul/li[6]/a/span/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.account-user-avatar > img.rounded-circle</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>a2f61300-12f1-4062-b4fc-33f30dfd930d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../Resources/assets/images/users/avatar-1.jpg</value>
      <webElementGuid>d9e0776d-6579-47df-9eac-76e255108650</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>user-image</value>
      <webElementGuid>b50f7cc0-71b2-4267-a6f3-f0f1a6ed0473</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>32</value>
      <webElementGuid>6d0a3b71-3a64-462c-a6b8-77fdf36bbefb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rounded-circle</value>
      <webElementGuid>6969ad8d-72c6-4b1e-9208-177b72846c2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;body&quot;)/div[@class=&quot;wrapper show&quot;]/div[@class=&quot;navbar-custom&quot;]/div[@class=&quot;topbar container-fluid&quot;]/ul[@class=&quot;topbar-menu d-flex align-items-center gap-2&quot;]/li[@class=&quot;dropdown&quot;]/a[@class=&quot;nav-link dropdown-toggle arrow-none nav-user px-2 show&quot;]/span[@class=&quot;account-user-avatar&quot;]/img[@class=&quot;rounded-circle&quot;]</value>
      <webElementGuid>1eeac84d-c33b-46b2-81d5-412a7af36e4c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='body']/div/div/div/ul/li[6]/a/span/img</value>
      <webElementGuid>65d2bfdc-43b2-4cbf-ad1c-2d8135805dbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='user-image']</value>
      <webElementGuid>4c02d744-7d46-415d-93aa-c4f39525954a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[6]/a/span/img</value>
      <webElementGuid>03146ef4-55b3-49ab-b6db-a62f4e7ddefe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '../Resources/assets/images/users/avatar-1.jpg' and @alt = 'user-image']</value>
      <webElementGuid>70f1d597-37ff-44ba-9feb-22231528cda9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
