<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_(Open)_account-user-avatar</name>
   <tag></tag>
   <elementGuidId>2454638c-c22d-4403-950e-c1b6538958ba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[6]/a/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.account-user-avatar</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>dd1ed3e6-34b3-4f67-b070-2240ce1dac3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>account-user-avatar</value>
      <webElementGuid>b450c8a3-8cb9-42cb-9d20-14fb0e6679ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;body&quot;)/div[@class=&quot;wrapper show&quot;]/div[@class=&quot;navbar-custom&quot;]/div[@class=&quot;topbar container-fluid&quot;]/ul[@class=&quot;topbar-menu d-flex align-items-center gap-2&quot;]/li[@class=&quot;dropdown&quot;]/a[@class=&quot;nav-link dropdown-toggle arrow-none nav-user px-2&quot;]/span[@class=&quot;account-user-avatar&quot;]</value>
      <webElementGuid>5bd38773-de9c-4cb8-84b0-696373d1cf85</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='body']/div/div/div/ul/li[6]/a/span</value>
      <webElementGuid>c6cce6de-2c49-4fcb-add3-34b34469c86f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[6]/a/span</value>
      <webElementGuid>45ac508f-befa-42ac-ba02-7b035a5ae1ea</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
