<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_ClientCreation</name>
   <tag></tag>
   <elementGuidId>6171eb5e-6cef-483c-8947-7a2eb309488e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#CustomerPage</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='CustomerPage']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>5efa0226-0521-4bb9-88f9-7d346e26ee89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gb-hover-side confirmation-link</value>
      <webElementGuid>06431de6-e0f7-4e11-af14-895113839651</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>CustomerValidation</value>
      <webElementGuid>82275cf2-3b64-48f1-a0a9-147955161bed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>CustomerPage</value>
      <webElementGuid>bc66ca70-351a-486e-8501-cb3f51b07a6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>return loadIframe('ifrm1', this.href);</value>
      <webElementGuid>15063f8f-0aca-4eca-a648-b29acc0e946e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Client
									Creation</value>
      <webElementGuid>e124bcaf-d95e-4259-b1ff-9c13aec1e438</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CustomerPage&quot;)</value>
      <webElementGuid>76df0e97-61ea-4a6c-9180-256ceb95cfc3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='CustomerPage']</value>
      <webElementGuid>6e6bd71b-5d1a-4295-8291-ff80dfbc6fc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sidebarCustomer']/ul/li[2]/a</value>
      <webElementGuid>e42e0894-2314-48c3-b877-fbf483ba7ef6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Client
									Creation')]</value>
      <webElementGuid>213571bb-acec-4153-a5fd-8ef73b88a5c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'CustomerValidation')]</value>
      <webElementGuid>2c0a05c3-7dbe-4123-8262-cc1d645eefc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/div/ul/li[2]/a</value>
      <webElementGuid>76c02e54-292c-4dca-90d9-ee4401fb2580</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'CustomerValidation' and @id = 'CustomerPage' and (text() = 'Client
									Creation' or . = 'Client
									Creation')]</value>
      <webElementGuid>699c900a-edec-4ed3-88c4-433a1734493e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
