<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputtxtTotalBrorrowAmount</name>
   <tag></tag>
   <elementGuidId>3b5e8b70-6e25-4e07-82f0-f4e703f3bbf6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtTotalBrorrowAmount']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#txtTotalBrorrowAmount</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>32b8d3b4-22ea-40b9-870b-36c38017d1a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>4ccb33a5-9241-4b2a-8158-2d600fdca2d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a3db343c-af89-4f12-bf52-314facd75c91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control required gb-border-fcs font-12</value>
      <webElementGuid>c1d396c6-6b15-43dc-ae95-dbdeb8eaef0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtTotalBrorrowAmount</value>
      <webElementGuid>58625179-cc1b-4cc8-9a8b-4c26514dfe3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtTotalBrorrowAmount&quot;)</value>
      <webElementGuid>e808e9ee-e4f6-4686-a3f9-be25069f0faf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtTotalBrorrowAmount']</value>
      <webElementGuid>3c915018-0417-47bb-91e0-fe2e2d810d72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cashflow1']/div/div[2]/div/div[3]/div[2]/div/input</value>
      <webElementGuid>19030b23-2fb0-43a8-8557-4ce31f4fa7ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[3]/div[2]/div/input</value>
      <webElementGuid>09cca090-1df0-488b-b2df-850207691257</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'txtTotalBrorrowAmount']</value>
      <webElementGuid>2ed5f6a4-37a2-46a5-afd3-006f94d31fca</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
