<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Vocational_txtSeniorHighSchool</name>
   <tag></tag>
   <elementGuidId>ac549751-d95f-4093-9f5e-f57997db8932</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtSeniorHighSchool</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtSeniorHighSchool']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7492500b-9f9e-4a43-a6db-aa5416d8ecd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>66d047a8-45cd-4cbc-a120-e58d2368c716</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>68b6350b-2777-404b-8b4e-d9329e84b723</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control gb-border-fcs font-11</value>
      <webElementGuid>d6e9a69d-08a1-4e61-a07b-73aa348e6452</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return onlyNumberKey(event)</value>
      <webElementGuid>a184d2be-d548-4aec-a19d-5ceeb76136e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtSeniorHighSchool</value>
      <webElementGuid>be6d5106-1ddf-4e2b-b052-df71961f028f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtSeniorHighSchool&quot;)</value>
      <webElementGuid>a836a12b-e586-4563-8a3b-d99b5d3e89d4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtSeniorHighSchool']</value>
      <webElementGuid>a8ec43c6-eaeb-4e0a-aa12-ec2995239f48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='7']/div/div/div/div[8]/div[4]/div/div/input</value>
      <webElementGuid>be6d0bf7-14a8-4409-b0dc-1b1ed6e9307a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/input</value>
      <webElementGuid>414f46fd-d38c-4042-adbe-731e93134ca3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'txtSeniorHighSchool']</value>
      <webElementGuid>2c4ab15a-c05c-44c5-b992-209e7ad04a64</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
