<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Numberof Household Member_txtHouseholdMember</name>
   <tag></tag>
   <elementGuidId>f38b03c3-e8c4-49b2-a0c7-3149d072c714</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtHouseholdMember</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtHouseholdMember']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a12950cc-13e3-42ca-ac67-0f7a3b28409f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>2a8f715b-8eff-4834-83dd-6e6d05e9ba13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a5821540-5490-4ab1-822f-494737789245</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control gb-border-fcs font-11</value>
      <webElementGuid>b5f61c07-d94f-4479-855e-07c59da93106</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return onlyNumberKey(event)</value>
      <webElementGuid>9882dbfe-b1b2-4ba1-bd95-c22e749ea9a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtHouseholdMember</value>
      <webElementGuid>c98c0686-5a4e-4ecc-9525-fe9f753114f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtHouseholdMember&quot;)</value>
      <webElementGuid>32ac2e7c-dd4f-45a4-b38e-0c7c5d3fc3b1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtHouseholdMember']</value>
      <webElementGuid>d3d6d914-f646-405a-a938-d5f613d37c24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='7']/div/div/div/div[2]/div/input</value>
      <webElementGuid>c4f81ef9-1795-4a62-b252-a5926edf2846</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/div/div[2]/div/input</value>
      <webElementGuid>9835b738-9b4e-4690-8edb-e08c38ec7b63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'txtHouseholdMember']</value>
      <webElementGuid>170e8ff5-9634-4280-a136-f4f0c95bd2f2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
