<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputtxtRemainingLoanable</name>
   <tag></tag>
   <elementGuidId>089cd42a-ba2e-4852-832f-59b9b3475ff5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtRemainingLoanable']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#txtRemainingLoanable</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7fcd59c1-5315-4256-b158-d3c76e4b9983</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>0ca40731-36c5-42ec-a36b-fc8f85d1fd4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b1ce598b-1474-4bd3-bb31-c1b3558c558e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control keep-disabled gb-border-fcs</value>
      <webElementGuid>98f563ec-1635-4bfe-8583-f4a498d7cb12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtRemainingLoanable</value>
      <webElementGuid>da7ff587-6498-4a0a-b4d7-efaf0271f856</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtRemainingLoanable&quot;)</value>
      <webElementGuid>f21b30fe-deda-4d54-b5d3-6b0f688a1c4e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtRemainingLoanable']</value>
      <webElementGuid>8c91d339-d0eb-485f-afb9-6ace8c93c6c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cashflow1']/div/div[3]/div[6]/div[2]/div/input</value>
      <webElementGuid>f2206aba-aad4-42a3-9792-7a6c71871be5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[2]/div/input</value>
      <webElementGuid>fecdadd4-7051-41b3-8748-cac54431746d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'txtRemainingLoanable']</value>
      <webElementGuid>fdc0590b-67db-4087-9d24-d9d9eb22739b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
