<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_FirstName_txtmothersMaidenFName</name>
   <tag></tag>
   <elementGuidId>9a8a4df3-ac25-42f1-973d-e37a092e2d85</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtmothersMaidenFName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtmothersMaidenFName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b42984ee-951f-4770-a6b1-b88474ca3793</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>05184e67-85fe-4519-8bfa-e3adaa5c0d48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d9e31fa5-cd7d-4e69-a430-a4f1611b30d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control gb-border-fcs text-capitalize font-11</value>
      <webElementGuid>10eee921-16f8-4e71-b26a-c3ae5e879ec0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtmothersMaidenFName</value>
      <webElementGuid>cd5c3373-7d79-4964-84f4-12e2fed06700</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>checkNames();</value>
      <webElementGuid>44b4754d-968a-4938-b8f8-fa200cdd0253</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtmothersMaidenFName&quot;)</value>
      <webElementGuid>d941bd24-3310-4d8f-9c81-dce1d7020e04</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtmothersMaidenFName']</value>
      <webElementGuid>81ed8cc3-b081-4199-97dc-677a94e97181</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='0']/div/div/div[2]/div/div/div[18]/div/input</value>
      <webElementGuid>d5e44140-37c3-42c9-a850-060562cfe5ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[18]/div/input</value>
      <webElementGuid>45e5edbb-b77b-4e47-8fdc-790bfccf1dc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'txtmothersMaidenFName']</value>
      <webElementGuid>e0298e67-a39c-45a2-9681-e32e93bfbe0e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
