<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Sourceof Fund_txtOtherKYCSourceOfIncome</name>
   <tag></tag>
   <elementGuidId>3a037e1b-0949-4c7d-8831-d43d2966fa90</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtOtherKYCSourceOfIncome</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtOtherKYCSourceOfIncome']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>801e52bb-6df6-4a80-a87a-664740ee7a64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>71d5cb23-cb52-44d4-aa13-9b8d1d11a986</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>edb6b1bb-7438-4afa-a03f-3293aab8093a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control gb-border-fcs text-capitalize font-11</value>
      <webElementGuid>9a09b170-4bed-4d0e-90f9-66766accc3ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtOtherKYCSourceOfIncome</value>
      <webElementGuid>66192cfb-4588-4d30-8c20-85de744d094d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Company name</value>
      <webElementGuid>12dd2649-9aeb-40ea-ba9b-09c21ffcabd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtOtherKYCSourceOfIncome&quot;)</value>
      <webElementGuid>a16b2984-e5c8-4480-8e36-e4cbbf890564</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtOtherKYCSourceOfIncome']</value>
      <webElementGuid>48a5f7bc-79d5-4df1-a399-f8e3bf2d1976</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='kycSourceOfFund']/div/input</value>
      <webElementGuid>649a9cd4-fdfe-432e-a7ec-77d79fbc86c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/div/div[4]/div/input</value>
      <webElementGuid>3d44c055-9b0b-47b5-8487-7037bcdfb819</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'txtOtherKYCSourceOfIncome' and @placeholder = 'Enter Company name']</value>
      <webElementGuid>9e91959a-a95e-4f3f-82c7-18400a6cd6f2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
