<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputtxtLoanableAmount</name>
   <tag></tag>
   <elementGuidId>ab24dbdc-7318-4b68-86e2-961d8e407c40</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtLoanableAmount']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#txtLoanableAmount</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>48b1b2b8-4e53-4d6b-8d5d-f541e94d363a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>2686639e-4ea9-4728-bde2-9afd515441aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>973b2974-d67c-4e30-bb80-95868a05be63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control keep-disabled</value>
      <webElementGuid>b1084419-ef56-4cdb-bd1a-0fbd12373b84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtLoanableAmount</value>
      <webElementGuid>0ec9d7cd-4cbc-48f6-8940-2b7aff290d93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtLoanableAmount&quot;)</value>
      <webElementGuid>973a8cce-83ae-40e5-970a-815e4f33d232</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtLoanableAmount']</value>
      <webElementGuid>e47184db-09b4-4c5d-af94-fed2c4b754c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cashflow1']/div/div[3]/div[4]/div[2]/div/input</value>
      <webElementGuid>a6684494-7833-4d65-b9a3-7e73a7ac8ab4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[4]/div[2]/div/input</value>
      <webElementGuid>6c1c1576-35da-4b09-8017-12c74a82348c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'txtLoanableAmount']</value>
      <webElementGuid>7a105955-08d5-40dd-9fe5-2c0c5230e4ad</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
