<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Remarks_txtBeneficiaryName1</name>
   <tag></tag>
   <elementGuidId>16f2b1ef-9c7a-44db-b355-10f9528b7635</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtBeneficiaryName1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtBeneficiaryName1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>21bacd03-4460-4e7b-b670-9cc03134fe56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>561241b2-3765-4964-ba0d-dc839a0e6d2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9adeddec-3cec-4c4b-8986-16ef5bfbd26f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control required gb-border-fcs text-capitalize font-9</value>
      <webElementGuid>30d63254-f1b7-472e-877c-504066d8c935</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>522d0028-2569-4fd2-9639-41aeb3d5edd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtBeneficiaryName1</value>
      <webElementGuid>330c1c1a-f7fa-4b67-aa64-9bc1f61314f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtBeneficiaryName1&quot;)</value>
      <webElementGuid>ceb71bff-dbb4-47ca-b109-2dec0e5ae721</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtBeneficiaryName1']</value>
      <webElementGuid>5305900e-766d-4c2a-86aa-a30544caf747</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='row1']/div/div/div/div/input</value>
      <webElementGuid>7d6ed9a8-819b-45f3-a013-881c0cc98da8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/div/input</value>
      <webElementGuid>35831b65-065b-4912-a1ec-398291f6a1e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'txtBeneficiaryName1']</value>
      <webElementGuid>b023ce6b-6644-419b-b357-414f7ee7973c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
