<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputtxtActiveLoanTotal</name>
   <tag></tag>
   <elementGuidId>7532127e-a03a-4f55-9e0f-a563bd2c4856</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtActiveLoanTotal']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#txtActiveLoanTotal</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3761ce44-ed79-4051-b735-c9969aac6cd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>57ac72b1-2fe4-4496-b453-92d09a005a09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3630b3cd-83af-4477-b7be-72e995fdac2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control keep-disabled computeCashflow</value>
      <webElementGuid>56c496d9-405d-4eb9-a9c2-4b0582d00a70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtActiveLoanTotal</value>
      <webElementGuid>6d20e65a-694f-43e7-8466-086a266a192c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtActiveLoanTotal&quot;)</value>
      <webElementGuid>40fcbc24-4db5-4c1d-a622-f3f176b3d2c8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtActiveLoanTotal']</value>
      <webElementGuid>c10fac46-1c17-4d9d-9e72-0542113aecb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cashflow1']/div/div[2]/div/div[2]/div/div[2]/div[3]/div/input</value>
      <webElementGuid>de3777bd-b960-4194-be9d-74570febf582</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/div/input</value>
      <webElementGuid>6976d07b-1337-4701-81d2-6bf0191e47cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'txtActiveLoanTotal']</value>
      <webElementGuid>5c4c9a03-7835-4051-828a-e7bd9108b38e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
