<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_YES_FormerEmployee</name>
   <tag></tag>
   <elementGuidId>92bccb3e-55fb-4cb3-9217-952b206e1d23</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtFormerEmployeeNO</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtFormerEmployeeNO']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f520201c-0b54-4cbc-b380-6648d2adb0de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>8fb0c683-024e-4f96-98fe-9eeb1b6a6cce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input gb-border-fcs </value>
      <webElementGuid>a8516384-b283-45c0-a41d-30308925b2f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>849e21ee-fa23-4f6d-a6c2-e797a17f6fe5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtFormerEmployeeNO</value>
      <webElementGuid>abb4c72c-d7b8-45c3-a373-328338abe244</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>FormerEmployee</value>
      <webElementGuid>b4373f54-1b81-44ae-a839-593b07ed541a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtFormerEmployeeNO&quot;)</value>
      <webElementGuid>57a8b6cd-e6b8-4923-a730-fa96fa4388ed</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtFormerEmployeeNO']</value>
      <webElementGuid>09a41cef-0079-47b7-95a6-cccfc53ca3a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='0']/div/div/div[2]/div[2]/div[22]/div[2]/input</value>
      <webElementGuid>61712146-8759-4c57-bb6c-dad8cac70cea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[22]/div[2]/input</value>
      <webElementGuid>91394f0c-1739-4c03-91e3-d96a3058e0c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'txtFormerEmployeeNO' and @name = 'FormerEmployee']</value>
      <webElementGuid>ae91e9e3-66db-4564-968f-23c059e08a7e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
