<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Birthday_txtbday</name>
   <tag></tag>
   <elementGuidId>17917c53-7597-4473-b802-8aca822c43c0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtbday</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtbday']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d827c381-5765-4247-bd55-c48ee730359b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>66254810-0a46-428d-b13b-33317a15197a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>date</value>
      <webElementGuid>5df2154b-00a8-48c4-b835-fc2c82179dd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control text-uppercase gb-border-fcs font-11</value>
      <webElementGuid>3114492f-2094-4f59-b756-451c41fbcf8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>2999-12-12</value>
      <webElementGuid>91379d42-aeab-4a07-a0a6-6911cda436f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtbday</value>
      <webElementGuid>8c6d9436-b8cc-4405-8ac3-917eece4be10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtbday&quot;)</value>
      <webElementGuid>d5542efd-a3ad-4479-946a-31391706eb7f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtbday']</value>
      <webElementGuid>777fc850-25aa-4252-bbec-752779ce3015</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='0']/div/div/div[2]/div[2]/div[5]/div/input</value>
      <webElementGuid>76197c11-c13e-4d09-b1a9-eb7155500db1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/input</value>
      <webElementGuid>2c63a2c8-6a11-4f7d-8f4b-2239c667e1f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'date' and @id = 'txtbday']</value>
      <webElementGuid>f194569a-b57a-4e6a-a386-5cd7dcaf4896</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
