<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_PostGraduate_txtHighSchool</name>
   <tag></tag>
   <elementGuidId>6a8bd1d3-c7ee-454a-bbfd-390f89a0da57</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtHighSchool</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtHighSchool']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>09a11860-6b93-4590-a427-7a34072168f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>ec1b4c56-be3d-4e55-ba13-1e88e858c96d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>99125bec-0141-47e4-ad26-2c9c9565e1d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control gb-border-fcs font-11</value>
      <webElementGuid>bdd05a8c-1422-4b23-a10a-70e111676f69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return onlyNumberKey(event)</value>
      <webElementGuid>cdc0e5cc-425a-4b2f-9ebf-9639773a8705</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtHighSchool</value>
      <webElementGuid>244d2b61-6ce0-4bb2-98a0-1e5e9a62c21a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtHighSchool&quot;)</value>
      <webElementGuid>c3e45ddb-0a30-45d8-8e6f-68ac86a48a84</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtHighSchool']</value>
      <webElementGuid>545e3e43-04ec-48ba-80a4-6dfa739f93f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='7']/div/div/div/div[8]/div[3]/div/div/input</value>
      <webElementGuid>10064664-2195-40ed-adc2-04e649b01f07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div[3]/div/div/input</value>
      <webElementGuid>e0d6400f-8a23-4cf8-968e-ca84700ee38c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'txtHighSchool']</value>
      <webElementGuid>79ce7272-0995-4a26-aabf-086c0afb2333</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
