<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_IDNumber_txtIdNumber</name>
   <tag></tag>
   <elementGuidId>de7350d3-98ec-404f-88bd-9ecb0dc89a1d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtIdNumber</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtIdNumber']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1c48296c-413a-4268-86b1-bf724ddc5840</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>33260a8b-fb09-4fa9-90bf-a80f740e14c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2b3c7484-8ed9-4f91-828e-a76cd38430a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control gb-border-fcs font-11</value>
      <webElementGuid>8e213e86-3d87-4e4d-854e-8bbe032f7843</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtIdNumber</value>
      <webElementGuid>adf8b737-f0f6-4a02-a8a3-160cb6cd0ea9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtIdNumber&quot;)</value>
      <webElementGuid>6b2bd68d-6f30-45d2-b11c-821fcb8f376f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtIdNumber']</value>
      <webElementGuid>0cff2b35-93c8-4609-a442-64f124f89250</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='3']/div/div/div/div[3]/div/input</value>
      <webElementGuid>890355e4-8c5d-46d6-aad8-8b54079c32ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>2e7b280a-bb18-4a30-a886-07133fcdfb80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'txtIdNumber']</value>
      <webElementGuid>c6a29422-1fd6-495a-beba-b83e90fe78e0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
