<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_HouseholdMonthly Expense_txtMonthlyExpense</name>
   <tag></tag>
   <elementGuidId>f6705062-81ac-46d7-9c4c-6bd12783d88e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtMonthlyExpense</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtMonthlyExpense']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3564f23e-a291-4598-a11a-3205ccf459a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>437c849e-7dd9-4c4d-8524-b88e294cf144</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7503d440-8cba-4e5d-b470-c57407a02afb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control gb-border-fcs font-11</value>
      <webElementGuid>93fc4a5c-207f-4594-a14a-3f0c722bd2b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtMonthlyExpense</value>
      <webElementGuid>e00f6316-21e1-42f6-892b-7fb563c06990</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtMonthlyExpense&quot;)</value>
      <webElementGuid>82df48df-2087-4fae-84d1-9b5a2a30d38b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtMonthlyExpense']</value>
      <webElementGuid>e3370ec6-22ac-42c1-91b6-df9882e96088</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='7']/div/div/div/div[6]/div/input</value>
      <webElementGuid>29795bba-44d6-409b-a801-cbfa6100b25e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/div/div[6]/div/input</value>
      <webElementGuid>134fd0e4-5e77-49c4-9fd5-e72792035241</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'txtMonthlyExpense']</value>
      <webElementGuid>83f5d960-82f6-45f1-8acd-25ef28a45cc7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
