<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_DOSRI_dosri</name>
   <tag></tag>
   <elementGuidId>5de240a6-208a-4319-a0b9-974e44a454eb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dosriNone</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dosriNone']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a9f21acf-3d5c-4603-88d6-e417418edebe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>19c40eb1-f2d7-4340-b361-516889f3e2b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input gb-border-fcs  </value>
      <webElementGuid>dff2095b-8ed2-4ba7-95ae-f0727f238cd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>ee0f0d94-6cc4-4b55-b5b7-a5b698a61a42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>dosri();</value>
      <webElementGuid>315608e6-e3cd-4004-b26d-615ed6219cfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dosriNone</value>
      <webElementGuid>a080b90e-129c-45e8-baa6-750884d8e20d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>dosri</value>
      <webElementGuid>4114fb7a-03a6-491b-aaad-8be99587eb30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>CLient Type</value>
      <webElementGuid>8460826a-974b-4556-9d9c-6d6bfd1db163</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dosriNone&quot;)</value>
      <webElementGuid>18902bca-d653-46f1-9367-51ab98ba5596</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dosriNone']</value>
      <webElementGuid>5bcd8ace-1791-49db-9d45-6a653a55f353</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='4']/div/div/div/div[2]/div/input</value>
      <webElementGuid>99b47210-71e8-44c1-be82-a64ccb8472c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div[2]/div/input</value>
      <webElementGuid>0d4e9621-4f1f-4b21-b405-fb3fc6260ae2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'dosriNone' and @name = 'dosri' and @placeholder = 'CLient Type']</value>
      <webElementGuid>6ad9acf6-bff1-40e6-97b0-35393a448375</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
