<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Same with the Present AddressPhysical_c9b861</name>
   <tag></tag>
   <elementGuidId>28061c5b-9a98-4b2b-84bf-a277f2b20737</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#yes</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='yes']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4e90a588-e740-47f0-b67f-9867d916428d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>063dabf3-7dd4-4918-a8df-c0bff4fdbc5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-inpput gb-border-fcs </value>
      <webElementGuid>2e647e0f-f54e-4c71-8ae1-434d6b2bb18c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>30206008-01d9-49e6-aa5a-4c7c027d58ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>CheckAddress();</value>
      <webElementGuid>514e8eed-5ba9-43ab-9b7a-274cb0ccb6f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>yes</value>
      <webElementGuid>de6dd32c-6765-4b7b-b91a-7e8122503539</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>droneadd</value>
      <webElementGuid>ccde1895-810b-4937-bba9-120ddf3455a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>CLient Type</value>
      <webElementGuid>a0ea4103-b756-4f00-a327-2ddb0e7abde5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;yes&quot;)</value>
      <webElementGuid>49b5c29c-159e-46ab-b308-843066e1aec6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='yes']</value>
      <webElementGuid>72224345-93ad-4d8b-ba2b-0789864a6728</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='2']/div/div/div/div[10]/div/input</value>
      <webElementGuid>93993f02-87db-4e71-99e6-09666362cb31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[10]/div/input</value>
      <webElementGuid>e2699f75-5702-4cab-9f9d-cd83509107c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'yes' and @name = 'droneadd' and @placeholder = 'CLient Type']</value>
      <webElementGuid>35711390-ba18-4a98-a5a8-805fe792a8fb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
