<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_YES_ImmediateFamilyMember</name>
   <tag></tag>
   <elementGuidId>0122b8e9-8a35-44c4-b460-374da84ac2b5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ImmediateFamilyMemberNo</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ImmediateFamilyMemberNo']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ab3cb98b-47c2-4a4a-b4f0-1cedc2d459ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>316d694e-048d-4c13-ab40-4220aff2f79b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input gb-border-fcs</value>
      <webElementGuid>65f9f89c-bea9-4242-a231-e3e774902528</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>550aa6a9-19eb-4f22-9fbd-b9f2b08c2b4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>RelationshipwithImmediateFamilyMember();</value>
      <webElementGuid>02aa9a6e-c2c8-4349-be41-4577e0fcb02a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ImmediateFamilyMemberNo</value>
      <webElementGuid>0c98293c-abbf-43ca-b05d-961ce98284d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ImmediateFamilyMember</value>
      <webElementGuid>7eb84b6c-53a0-432b-8f3c-094b9aac6237</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ImmediateFamilyMemberNo&quot;)</value>
      <webElementGuid>ebe450d9-f76a-4fa3-8953-f578459279bf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ImmediateFamilyMemberNo']</value>
      <webElementGuid>3434be01-83df-46cf-a1e2-0aecf93079c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='4']/div/div/div/div[10]/div[2]/input</value>
      <webElementGuid>31b5cec2-7cc6-4d67-81fc-a793697e91c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div[10]/div[2]/input</value>
      <webElementGuid>13dbd8b6-aa7f-440a-b55c-511e1040f21e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'ImmediateFamilyMemberNo' and @name = 'ImmediateFamilyMember']</value>
      <webElementGuid>ea64ac27-5d9d-48bb-b12b-4cd6b3aa2141</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
