<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_YES_CARDScholar</name>
   <tag></tag>
   <elementGuidId>0f1fffa0-d773-4c75-9be7-a829988d1ff6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtCARDScholarNO</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtCARDScholarNO']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ff9d359f-ae6b-498a-bdf9-c99c914079f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>f897047d-2718-4324-b040-845ee18873a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input gb-border-fcs </value>
      <webElementGuid>ae53889b-a81a-44db-aeaf-28dd97afb1c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>40455f72-22e4-493b-b436-8e8f0c363a1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtCARDScholarNO</value>
      <webElementGuid>6929460d-b688-418f-84dd-4298134bf117</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>CARDScholar</value>
      <webElementGuid>28f35acc-f25d-4a69-8aa5-dc7a1052dd1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtCARDScholarNO&quot;)</value>
      <webElementGuid>a548ea9c-9909-4c6d-aadf-e0591b6c503c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtCARDScholarNO']</value>
      <webElementGuid>c92dcd12-69ee-4dec-a417-39be795f2458</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='0']/div/div/div[2]/div[2]/div[21]/div[2]/input</value>
      <webElementGuid>98519762-db14-4450-8f80-292553de76e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[21]/div[2]/input</value>
      <webElementGuid>d72dae83-0462-405b-88df-dd7fd958d40b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'txtCARDScholarNO' and @name = 'CARDScholar']</value>
      <webElementGuid>b83cad8f-6cc6-41e2-820a-a3a1b635480e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
