<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Referredby_txtReferredbyOtherPrimary</name>
   <tag></tag>
   <elementGuidId>1f901106-aea8-4a8a-83d1-be397bf49945</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtReferredbyOtherPrimary</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtReferredbyOtherPrimary']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4fc03f0c-dc55-4601-a50a-cf15583eca48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>cc2522b8-bdfd-488c-9213-5af69f2afd1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d922cdea-9e72-4ba1-9588-14d37afa0b1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtReferredbyOtherPrimary</value>
      <webElementGuid>c94ddefa-dff5-4a28-bab5-440bad0e5acb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>Referredby();</value>
      <webElementGuid>4ed9225e-f383-43e7-ba1d-97add5c94c55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control gb-border-fcs font-11 text-capitalize</value>
      <webElementGuid>be64c752-6bc8-4b7b-b019-942b9875a5de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtReferredbyOtherPrimary&quot;)</value>
      <webElementGuid>2a1f13e4-3f55-4b9b-916f-2fb04448d3ab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtReferredbyOtherPrimary']</value>
      <webElementGuid>3af511ea-6d7c-4e6c-afc5-b5846e51d94f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='4']/div/div/div/div[7]/div[2]/div/input</value>
      <webElementGuid>6bf98453-c066-4c1b-a337-af9925de1f66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div[2]/div/input</value>
      <webElementGuid>0771be0f-6673-4b16-816d-a5932d729009</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'txtReferredbyOtherPrimary']</value>
      <webElementGuid>a69454f9-dfb3-4874-aa06-eb3a47fd9c55</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
