<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select      51015_1</name>
   <tag></tag>
   <elementGuidId>ea98121a-0bd3-489a-9531-6a90ec419552</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cbosecondRiskAnswer</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='cbosecondRiskAnswer']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>42e5c7d2-3051-46b9-b7d9-ed21e0a3ab4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-center gb-border-fcs Ans2</value>
      <webElementGuid>a9812ddf-3bc3-49fb-966c-f19a263e0b6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cbosecondRiskAnswer</value>
      <webElementGuid>74b18736-2ea4-47fe-b2b0-8cf751d86a09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>     Select      51015</value>
      <webElementGuid>3d79f50f-0a0d-44fe-a04f-377d8bd81048</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cbosecondRiskAnswer&quot;)</value>
      <webElementGuid>e5998520-712d-4da2-92f9-6300b69139e8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='cbosecondRiskAnswer']</value>
      <webElementGuid>8418eeaf-3c97-4df6-98cb-b52b79135722</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='tblRiskclassSecBody']/tr/td[9]/select</value>
      <webElementGuid>c666ef3b-785c-4a01-8d16-091c5455e101</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tbody[2]/tr/td[9]/select</value>
      <webElementGuid>db3a731c-0e0a-4685-816a-9d1653f98b50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'cbosecondRiskAnswer' and (text() = '     Select      51015' or . = '     Select      51015')]</value>
      <webElementGuid>e036c680-67c8-48f3-a8f3-fb978e984052</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
