<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_--Select--Barangay CertificateBIR TI_0033e0</name>
   <tag></tag>
   <elementGuidId>ad05e8e6-9bd1-489b-89f3-e429a10ae4b6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cboIDType</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='cboIDType']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>ca4f89d8-60ea-414f-a8ca-5f05ce08f9be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cboIDType</value>
      <webElementGuid>4d52928d-adf2-41af-adbd-b307d2042097</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>IdPresented();</value>
      <webElementGuid>4655abfe-b3b2-4f4a-9909-44dabd0b08b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control gb-border-fcs font-11</value>
      <webElementGuid>2ade20a7-7982-4098-ad98-a8d0fbc32db5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>--Select--Barangay CertificateBIR TINCompany IDDriver's License IDGSIS IDNBI ClearanceOWWA IDPag-IBIG IDPassportPhilHealth IDPostal IDPRC IDSenior Citizen IDSSS IDUMIDVoter's ID</value>
      <webElementGuid>f219aff9-1a7d-43b1-860b-f01c5ef9560f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cboIDType&quot;)</value>
      <webElementGuid>9e02d4af-0c2b-47c7-802b-9971445a76a4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='cboIDType']</value>
      <webElementGuid>f32aefd2-ea55-437b-a811-1d618f746307</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='3']/div/div/div/div[2]/div/div/select</value>
      <webElementGuid>285340be-4162-42aa-814a-bffaf0f10d98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div[2]/div/div/select</value>
      <webElementGuid>a1c01e63-6689-4fd5-9bee-9e013736f675</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'cboIDType' and (text() = concat(&quot;--Select--Barangay CertificateBIR TINCompany IDDriver&quot; , &quot;'&quot; , &quot;s License IDGSIS IDNBI ClearanceOWWA IDPag-IBIG IDPassportPhilHealth IDPostal IDPRC IDSenior Citizen IDSSS IDUMIDVoter&quot; , &quot;'&quot; , &quot;s ID&quot;) or . = concat(&quot;--Select--Barangay CertificateBIR TINCompany IDDriver&quot; , &quot;'&quot; , &quot;s License IDGSIS IDNBI ClearanceOWWA IDPag-IBIG IDPassportPhilHealth IDPostal IDPRC IDSenior Citizen IDSSS IDUMIDVoter&quot; , &quot;'&quot; , &quot;s ID&quot;))]</value>
      <webElementGuid>a5a80c42-193b-436b-b48f-79cda461e475</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
