<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_--      Select      --0 - Ika-6 na b_ee969e</name>
   <tag></tag>
   <elementGuidId>570b6708-9020-4b24-aac2-2b486743f87e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cbothirdQAnswer</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='cbothirdQAnswer']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>b7403762-50eb-487d-bf7b-fd762d5b3ef0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>validatelenght required gb-border-fcs form-control Ans</value>
      <webElementGuid>5d985458-30b5-430b-b834-b1dbee2434c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cbothirdQAnswer</value>
      <webElementGuid>de4725e0-6dfb-433b-b001-391f3f67389c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>--      Select      --[0] - Ika-6 na baitang o mas mababa pa[6] - Ilang taon sa mataas na paaralan[7] - Nakatapos ng mataas na paaralan</value>
      <webElementGuid>225cec8e-48c6-4a97-9a73-e8724579b00d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cbothirdQAnswer&quot;)</value>
      <webElementGuid>152de2e0-e00d-434a-b65a-1ae73e4bfba5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='cbothirdQAnswer']</value>
      <webElementGuid>ed57b3ed-b5d9-40ff-b094-280e1ff509cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='tblPPIBodyThird']/tr/td[2]/select</value>
      <webElementGuid>2fbe6a12-4de1-4501-b90e-d02a48da4d8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tbody[3]/tr/td[2]/select</value>
      <webElementGuid>c929dce1-9594-40e2-868b-bef3d0cbacc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'cbothirdQAnswer' and (text() = '--      Select      --[0] - Ika-6 na baitang o mas mababa pa[6] - Ilang taon sa mataas na paaralan[7] - Nakatapos ng mataas na paaralan' or . = '--      Select      --[0] - Ika-6 na baitang o mas mababa pa[6] - Ilang taon sa mataas na paaralan[7] - Nakatapos ng mataas na paaralan')]</value>
      <webElementGuid>8ee53989-a536-4493-8d63-3049aac745a3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
