<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_--      Select      --Abra - CAR (Co_3be376</name>
   <tag></tag>
   <elementGuidId>39acc628-b600-4732-9ca2-0007365ffd8e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cboBdayProvince</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='cboBdayProvince']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>b096b9dc-ab88-4f90-84e7-58dd76864630</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cboBdayProvince</value>
      <webElementGuid>8b1e4ce8-ddeb-49cf-98c3-7f4609480b6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control gb-border-fcs select2 font-11</value>
      <webElementGuid>079b4795-e624-4dda-a370-999f2d2f2e95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>select2</value>
      <webElementGuid>8525f73b-1b34-48fc-bdf5-d8c0f14f2894</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>--      Select      --Abra - CAR (Cordillera Administrative Region)Agusan Del Norte - Region XIII (CARAGA)Agusan Del Sur - Region XIII (CARAGA)Aklan - Region VI (Western Visayas)Albay - Region V (Bicol Region)Antique - Region VI (Western Visayas)Apayao - CAR (Cordillera Administrative Region)Aurora - Region III (Central Luzon)Basilan - BARMM (Bangsamoro Region)Bataan - Region III (Central Luzon)Batanes - Region II (Cagayan Valley)Batangas - Region IV-A (CALABARZON)Benguet - CAR (Cordillera Administrative Region)Biliran - Region VIII (Eastern Visayas)Bohol - Region VII (Central Visayas)Bukidnon - Region X (NORTHERN MINDANAO)Bulacan - Region III (Central Luzon)Cagayan - Region II (Cagayan Valley)Camarines Norte - Region V (Bicol Region)Camarines Sur - Region V (Bicol Region)Camiguin - Region X (NORTHERN MINDANAO)Capiz - Region VI (Western Visayas)Catanduanes - Region V (Bicol Region)Cavite - Region IV-A (CALABARZON)Cebu - Region VII (Central Visayas)Compostela Valley - Region XI (DAVAO Region)Cotabato - Region XII (SOCCSKSARGEN)COTABATO (NORTH COTABATO) - Region XII (SOCCSKSARGEN)Davao Del Norte - Region XI (DAVAO Region)Davao Del Sur - Region XI (DAVAO Region)Davao Occidental - Region XI (DAVAO Region)Davao Oriental - Region XI (DAVAO Region)Dinagat Islands - Region XIII (CARAGA)Eastern Samar - Region VIII (Eastern Visayas)Guimaras - Region VI (Western Visayas)Ifugao - CAR (Cordillera Administrative Region)Ilocos Norte - Region I (Ilocos Region)Ilocos Sur - Region I (Ilocos Region)Iloilo - Region VI (Western Visayas)Isabela - Region II (Cagayan Valley)Kalinga - CAR (Cordillera Administrative Region)Laguna - Region IV-A (CALABARZON)Lanao Del Norte - Region X (NORTHERN MINDANAO)Lanao Del Sur - BARMM (Bangsamoro Region)La Union - Region I (Ilocos Region)Leyte - Region VIII (Eastern Visayas)Maguindanao - BARMM (Bangsamoro Region)Marinduque - Region IV-B (MiMaRoPa)Masbate - Region V (Bicol Region)Metro Manila 1st District - NCR (National Capital Region)Metro Manila 2nd District - NCR (National Capital Region)Metro Manila 3rd District - NCR (National Capital Region)Metro Manila 4th District - NCR (National Capital Region)Misamis Occidental - Region X (NORTHERN MINDANAO)Misamis Oriental - Region X (NORTHERN MINDANAO)Mountain Province - CAR (Cordillera Administrative Region)Negros Occidental - Region VI (Western Visayas)Negros Oriental - Region VII (Central Visayas)Northern Samar - Region VIII (Eastern Visayas)Nueva Ecija - Region III (Central Luzon)Nueva Vizcaya - Region II (Cagayan Valley)Occidental Mindoro - Region IV-B (MiMaRoPa)Oriental Mindoro - Region IV-B (MiMaRoPa)Palawan - Region IV-B (MiMaRoPa)Pampanga - Region III (Central Luzon)Pangasinan - Region I (Ilocos Region)Quezon - Region IV-A (CALABARZON)Quirino - Region II (Cagayan Valley)Rizal - Region IV-A (CALABARZON)Romblon - Region IV-B (MiMaRoPa)SAMAR (WESTERN SAMAR) - Region VIII (Eastern Visayas)Sarangani - Region XII (SOCCSKSARGEN)Siquijor - Region VII (Central Visayas)Sorsogon - Region V (Bicol Region)South Cotabato - Region XII (SOCCSKSARGEN)Southern Leyte - Region VIII (Eastern Visayas)Sultan Kudarat - Region XII (SOCCSKSARGEN)Sulu - BARMM (Bangsamoro Region)Surigao Del Norte - Region XIII (CARAGA)Surigao Del Sur - Region XIII (CARAGA)Tarlac - Region III (Central Luzon)Tawi-Tawi - BARMM (Bangsamoro Region)Test Aklan - XXX Region VI XXXTest Ilocos Norte - Region I (Ilocos Region)Zambales - Region III (Central Luzon)Zamboanga Del Norte - Region IX (Zamboanga Peninsula)Zamboanga Del Sur - Region IX (Zamboanga Peninsula)Zamboanga Sibugay - Region IX (Zamboanga Peninsula)</value>
      <webElementGuid>01422fd2-a951-4409-a499-2b49bfc5c717</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cboBdayProvince&quot;)</value>
      <webElementGuid>70d29570-8b14-48d7-84d2-15d36ef7c010</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='cboBdayProvince']</value>
      <webElementGuid>085879d0-4399-471f-b907-e8d33b68df16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='0']/div/div/div[2]/div[2]/div[8]/div/div/select</value>
      <webElementGuid>ebe29472-4939-4dfc-b48a-b3db4c3c32a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div/select</value>
      <webElementGuid>327343ee-6791-4c81-86f5-d1479a0ce3fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'cboBdayProvince' and (text() = '--      Select      --Abra - CAR (Cordillera Administrative Region)Agusan Del Norte - Region XIII (CARAGA)Agusan Del Sur - Region XIII (CARAGA)Aklan - Region VI (Western Visayas)Albay - Region V (Bicol Region)Antique - Region VI (Western Visayas)Apayao - CAR (Cordillera Administrative Region)Aurora - Region III (Central Luzon)Basilan - BARMM (Bangsamoro Region)Bataan - Region III (Central Luzon)Batanes - Region II (Cagayan Valley)Batangas - Region IV-A (CALABARZON)Benguet - CAR (Cordillera Administrative Region)Biliran - Region VIII (Eastern Visayas)Bohol - Region VII (Central Visayas)Bukidnon - Region X (NORTHERN MINDANAO)Bulacan - Region III (Central Luzon)Cagayan - Region II (Cagayan Valley)Camarines Norte - Region V (Bicol Region)Camarines Sur - Region V (Bicol Region)Camiguin - Region X (NORTHERN MINDANAO)Capiz - Region VI (Western Visayas)Catanduanes - Region V (Bicol Region)Cavite - Region IV-A (CALABARZON)Cebu - Region VII (Central Visayas)Compostela Valley - Region XI (DAVAO Region)Cotabato - Region XII (SOCCSKSARGEN)COTABATO (NORTH COTABATO) - Region XII (SOCCSKSARGEN)Davao Del Norte - Region XI (DAVAO Region)Davao Del Sur - Region XI (DAVAO Region)Davao Occidental - Region XI (DAVAO Region)Davao Oriental - Region XI (DAVAO Region)Dinagat Islands - Region XIII (CARAGA)Eastern Samar - Region VIII (Eastern Visayas)Guimaras - Region VI (Western Visayas)Ifugao - CAR (Cordillera Administrative Region)Ilocos Norte - Region I (Ilocos Region)Ilocos Sur - Region I (Ilocos Region)Iloilo - Region VI (Western Visayas)Isabela - Region II (Cagayan Valley)Kalinga - CAR (Cordillera Administrative Region)Laguna - Region IV-A (CALABARZON)Lanao Del Norte - Region X (NORTHERN MINDANAO)Lanao Del Sur - BARMM (Bangsamoro Region)La Union - Region I (Ilocos Region)Leyte - Region VIII (Eastern Visayas)Maguindanao - BARMM (Bangsamoro Region)Marinduque - Region IV-B (MiMaRoPa)Masbate - Region V (Bicol Region)Metro Manila 1st District - NCR (National Capital Region)Metro Manila 2nd District - NCR (National Capital Region)Metro Manila 3rd District - NCR (National Capital Region)Metro Manila 4th District - NCR (National Capital Region)Misamis Occidental - Region X (NORTHERN MINDANAO)Misamis Oriental - Region X (NORTHERN MINDANAO)Mountain Province - CAR (Cordillera Administrative Region)Negros Occidental - Region VI (Western Visayas)Negros Oriental - Region VII (Central Visayas)Northern Samar - Region VIII (Eastern Visayas)Nueva Ecija - Region III (Central Luzon)Nueva Vizcaya - Region II (Cagayan Valley)Occidental Mindoro - Region IV-B (MiMaRoPa)Oriental Mindoro - Region IV-B (MiMaRoPa)Palawan - Region IV-B (MiMaRoPa)Pampanga - Region III (Central Luzon)Pangasinan - Region I (Ilocos Region)Quezon - Region IV-A (CALABARZON)Quirino - Region II (Cagayan Valley)Rizal - Region IV-A (CALABARZON)Romblon - Region IV-B (MiMaRoPa)SAMAR (WESTERN SAMAR) - Region VIII (Eastern Visayas)Sarangani - Region XII (SOCCSKSARGEN)Siquijor - Region VII (Central Visayas)Sorsogon - Region V (Bicol Region)South Cotabato - Region XII (SOCCSKSARGEN)Southern Leyte - Region VIII (Eastern Visayas)Sultan Kudarat - Region XII (SOCCSKSARGEN)Sulu - BARMM (Bangsamoro Region)Surigao Del Norte - Region XIII (CARAGA)Surigao Del Sur - Region XIII (CARAGA)Tarlac - Region III (Central Luzon)Tawi-Tawi - BARMM (Bangsamoro Region)Test Aklan - XXX Region VI XXXTest Ilocos Norte - Region I (Ilocos Region)Zambales - Region III (Central Luzon)Zamboanga Del Norte - Region IX (Zamboanga Peninsula)Zamboanga Del Sur - Region IX (Zamboanga Peninsula)Zamboanga Sibugay - Region IX (Zamboanga Peninsula)' or . = '--      Select      --Abra - CAR (Cordillera Administrative Region)Agusan Del Norte - Region XIII (CARAGA)Agusan Del Sur - Region XIII (CARAGA)Aklan - Region VI (Western Visayas)Albay - Region V (Bicol Region)Antique - Region VI (Western Visayas)Apayao - CAR (Cordillera Administrative Region)Aurora - Region III (Central Luzon)Basilan - BARMM (Bangsamoro Region)Bataan - Region III (Central Luzon)Batanes - Region II (Cagayan Valley)Batangas - Region IV-A (CALABARZON)Benguet - CAR (Cordillera Administrative Region)Biliran - Region VIII (Eastern Visayas)Bohol - Region VII (Central Visayas)Bukidnon - Region X (NORTHERN MINDANAO)Bulacan - Region III (Central Luzon)Cagayan - Region II (Cagayan Valley)Camarines Norte - Region V (Bicol Region)Camarines Sur - Region V (Bicol Region)Camiguin - Region X (NORTHERN MINDANAO)Capiz - Region VI (Western Visayas)Catanduanes - Region V (Bicol Region)Cavite - Region IV-A (CALABARZON)Cebu - Region VII (Central Visayas)Compostela Valley - Region XI (DAVAO Region)Cotabato - Region XII (SOCCSKSARGEN)COTABATO (NORTH COTABATO) - Region XII (SOCCSKSARGEN)Davao Del Norte - Region XI (DAVAO Region)Davao Del Sur - Region XI (DAVAO Region)Davao Occidental - Region XI (DAVAO Region)Davao Oriental - Region XI (DAVAO Region)Dinagat Islands - Region XIII (CARAGA)Eastern Samar - Region VIII (Eastern Visayas)Guimaras - Region VI (Western Visayas)Ifugao - CAR (Cordillera Administrative Region)Ilocos Norte - Region I (Ilocos Region)Ilocos Sur - Region I (Ilocos Region)Iloilo - Region VI (Western Visayas)Isabela - Region II (Cagayan Valley)Kalinga - CAR (Cordillera Administrative Region)Laguna - Region IV-A (CALABARZON)Lanao Del Norte - Region X (NORTHERN MINDANAO)Lanao Del Sur - BARMM (Bangsamoro Region)La Union - Region I (Ilocos Region)Leyte - Region VIII (Eastern Visayas)Maguindanao - BARMM (Bangsamoro Region)Marinduque - Region IV-B (MiMaRoPa)Masbate - Region V (Bicol Region)Metro Manila 1st District - NCR (National Capital Region)Metro Manila 2nd District - NCR (National Capital Region)Metro Manila 3rd District - NCR (National Capital Region)Metro Manila 4th District - NCR (National Capital Region)Misamis Occidental - Region X (NORTHERN MINDANAO)Misamis Oriental - Region X (NORTHERN MINDANAO)Mountain Province - CAR (Cordillera Administrative Region)Negros Occidental - Region VI (Western Visayas)Negros Oriental - Region VII (Central Visayas)Northern Samar - Region VIII (Eastern Visayas)Nueva Ecija - Region III (Central Luzon)Nueva Vizcaya - Region II (Cagayan Valley)Occidental Mindoro - Region IV-B (MiMaRoPa)Oriental Mindoro - Region IV-B (MiMaRoPa)Palawan - Region IV-B (MiMaRoPa)Pampanga - Region III (Central Luzon)Pangasinan - Region I (Ilocos Region)Quezon - Region IV-A (CALABARZON)Quirino - Region II (Cagayan Valley)Rizal - Region IV-A (CALABARZON)Romblon - Region IV-B (MiMaRoPa)SAMAR (WESTERN SAMAR) - Region VIII (Eastern Visayas)Sarangani - Region XII (SOCCSKSARGEN)Siquijor - Region VII (Central Visayas)Sorsogon - Region V (Bicol Region)South Cotabato - Region XII (SOCCSKSARGEN)Southern Leyte - Region VIII (Eastern Visayas)Sultan Kudarat - Region XII (SOCCSKSARGEN)Sulu - BARMM (Bangsamoro Region)Surigao Del Norte - Region XIII (CARAGA)Surigao Del Sur - Region XIII (CARAGA)Tarlac - Region III (Central Luzon)Tawi-Tawi - BARMM (Bangsamoro Region)Test Aklan - XXX Region VI XXXTest Ilocos Norte - Region I (Ilocos Region)Zambales - Region III (Central Luzon)Zamboanga Del Norte - Region IX (Zamboanga Peninsula)Zamboanga Del Sur - Region IX (Zamboanga Peninsula)Zamboanga Sibugay - Region IX (Zamboanga Peninsula)')]</value>
      <webElementGuid>cee87b98-ee92-4e3d-866b-15300a0c51e6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
