<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select      51015_1_2</name>
   <tag></tag>
   <elementGuidId>7ec6125c-2fe8-4b2f-8830-7bbf6d24e327</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cbosixthRiskAnswer</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='cbosixthRiskAnswer']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>092b766a-29b6-4ac8-88cc-0d45cdacd967</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-center gb-border-fcs Ans6</value>
      <webElementGuid>880cc2e8-3ac0-4cb2-812b-840d34654bdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cbosixthRiskAnswer</value>
      <webElementGuid>861e9cdc-22e4-476d-9f65-bbb816ad3b32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>     Select      51015</value>
      <webElementGuid>9bbfcc4f-3bb2-48b2-bf2c-d7e0e5ce1b07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cbosixthRiskAnswer&quot;)</value>
      <webElementGuid>056f1c3b-8ef8-4e43-b4dc-79500f02f1b2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='cbosixthRiskAnswer']</value>
      <webElementGuid>6e2b05cc-ad5c-4928-a430-79751f0e969f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='tblRiskclassSixBody']/tr/td[9]/select</value>
      <webElementGuid>be908519-8257-4728-91b4-ee0dd660d02d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tbody[6]/tr/td[9]/select</value>
      <webElementGuid>bf5b7ed6-5b2e-4c55-a9d8-62e1a9d47775</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'cbosixthRiskAnswer' and (text() = '     Select      51015' or . = '     Select      51015')]</value>
      <webElementGuid>10f3087f-348e-45a3-94ab-1e60260c2804</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
