<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_--Select--No Formal EducationElement_aa261c_1</name>
   <tag></tag>
   <elementGuidId>211cd626-79c1-47f4-911a-4fdea518aaac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cboEducationalAttainment1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='cboEducationalAttainment1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>1029cf94-0cc1-4e9c-a290-f72c6369376c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cboEducationalAttainment1</value>
      <webElementGuid>5db45395-036d-4466-bcfa-52012b74cd3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>eda7ee07-9109-4e8f-b7a8-946c90ad4d12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control required gb-border-fcs font-9</value>
      <webElementGuid>06c33d20-2f95-4f8d-b34b-83da16b0a59b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>--Select--No Formal EducationElementary UndergraduateElementary GraduateHigh School UndergraduateHigh School GraduateVocationalAssociate DegreeCollege UndergraduateCollege GraduateMaster's DegreeDoctorate Degree</value>
      <webElementGuid>bad9d729-43f9-44b4-aef3-1dde1dec55f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cboEducationalAttainment1&quot;)</value>
      <webElementGuid>682ca5a7-d470-40f3-9947-dbeea6e4c941</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='cboEducationalAttainment1']</value>
      <webElementGuid>5cc7b7ae-ae62-4451-b603-daa7b16b5eea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='row1']/div/div[5]/div/div/select</value>
      <webElementGuid>925d73b2-b1f6-4ff0-b70d-b03caad235ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div[5]/div/div/select</value>
      <webElementGuid>578de5ab-bd79-4df1-94cb-4336d0fd6a2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'cboEducationalAttainment1' and (text() = concat(&quot;--Select--No Formal EducationElementary UndergraduateElementary GraduateHigh School UndergraduateHigh School GraduateVocationalAssociate DegreeCollege UndergraduateCollege GraduateMaster&quot; , &quot;'&quot; , &quot;s DegreeDoctorate Degree&quot;) or . = concat(&quot;--Select--No Formal EducationElementary UndergraduateElementary GraduateHigh School UndergraduateHigh School GraduateVocationalAssociate DegreeCollege UndergraduateCollege GraduateMaster&quot; , &quot;'&quot; , &quot;s DegreeDoctorate Degree&quot;))]</value>
      <webElementGuid>9c585f3f-d22d-4a85-b0d2-2f10b6a26d92</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
