<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_--      Select      --AlaminosBayBia_8f7d3f</name>
   <tag></tag>
   <elementGuidId>0fc371b3-53ba-4bcf-a631-66b3dccfb555</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cboBdayMunicipalityCity</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='cboBdayMunicipalityCity']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>44775f4e-60e0-4dd0-a3f4-a354390d693c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cboBdayMunicipalityCity</value>
      <webElementGuid>8190afac-e4ca-4d69-8c58-7635242d1054</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control gb-border-fcs select2 font-11</value>
      <webElementGuid>1f6f575a-9150-4ccf-a41c-1fff5c191d11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>select2</value>
      <webElementGuid>1ce00bea-3380-4feb-add8-206a16fed6fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>--      Select      --AlaminosBayBiñan CityCabuyao CityCalamba CityCalauanCavintiFamyKalayaanLiliwLos BañosLuisianaLumbanMabitacMagdalenaMajayjayNagcarlanPaetePagsanjanPakilPangilPilaRizalSan Pablo CitySan Pedro CitySiniloanSta. CruzSta. MariaSta. Rosa CityVictoria</value>
      <webElementGuid>0375dd53-6b25-4cef-9d41-2f3061656cb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cboBdayMunicipalityCity&quot;)</value>
      <webElementGuid>a1c1ac01-1efc-4355-b339-f181ef7ebd23</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='cboBdayMunicipalityCity']</value>
      <webElementGuid>3327a287-ea71-4736-ab43-afc405f18715</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='0']/div/div/div[2]/div[2]/div[9]/div/div/select</value>
      <webElementGuid>c4775739-e193-4f3a-9f61-42479caa9a3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[9]/div/div/select</value>
      <webElementGuid>98cc7e4d-da12-417e-93b6-a275ec9f6f52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'cboBdayMunicipalityCity' and (text() = '--      Select      --AlaminosBayBiñan CityCabuyao CityCalamba CityCalauanCavintiFamyKalayaanLiliwLos BañosLuisianaLumbanMabitacMagdalenaMajayjayNagcarlanPaetePagsanjanPakilPangilPilaRizalSan Pablo CitySan Pedro CitySiniloanSta. CruzSta. MariaSta. Rosa CityVictoria' or . = '--      Select      --AlaminosBayBiñan CityCabuyao CityCalamba CityCalauanCavintiFamyKalayaanLiliwLos BañosLuisianaLumbanMabitacMagdalenaMajayjayNagcarlanPaetePagsanjanPakilPangilPilaRizalSan Pablo CitySan Pedro CitySiniloanSta. CruzSta. MariaSta. Rosa CityVictoria')]</value>
      <webElementGuid>6dd55997-249a-4a6f-9807-d2076ff4bea5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
