<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_--      Select      --Abra - CAR (Co_3be376_1</name>
   <tag></tag>
   <elementGuidId>5bef1df6-af40-4519-ab25-80d606bf21c2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cboPhyProvince</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='cboPhyProvince']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>fbf2fe13-84a4-49a4-8d9f-fc8a235f2fc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cboPhyProvince</value>
      <webElementGuid>cc954fe9-c1f3-4ed4-a972-73f4b1741de5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control gb-border-fcs font-11</value>
      <webElementGuid>9b3e8adb-18f2-4465-9c49-7f94836e27e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>--      Select      --Abra - CAR (Cordillera Administrative Region)Agusan Del Norte - Region XIII (CARAGA)Agusan Del Sur - Region XIII (CARAGA)Aklan - Region VI (Western Visayas)Albay - Region V (Bicol Region)Antique - Region VI (Western Visayas)Apayao - CAR (Cordillera Administrative Region)Aurora - Region III (Central Luzon)Basilan - BARMM (Bangsamoro Region)Bataan - Region III (Central Luzon)Batanes - Region II (Cagayan Valley)Batangas - Region IV-A (CALABARZON)Benguet - CAR (Cordillera Administrative Region)Biliran - Region VIII (Eastern Visayas)Bohol - Region VII (Central Visayas)Bukidnon - Region X (NORTHERN MINDANAO)Bulacan - Region III (Central Luzon)Cagayan - Region II (Cagayan Valley)Camarines Norte - Region V (Bicol Region)Camarines Sur - Region V (Bicol Region)Camiguin - Region X (NORTHERN MINDANAO)Capiz - Region VI (Western Visayas)Catanduanes - Region V (Bicol Region)Cavite - Region IV-A (CALABARZON)Cebu - Region VII (Central Visayas)Compostela Valley - Region XI (DAVAO Region)Cotabato - Region XII (SOCCSKSARGEN)COTABATO (NORTH COTABATO) - Region XII (SOCCSKSARGEN)Davao Del Norte - Region XI (DAVAO Region)Davao Del Sur - Region XI (DAVAO Region)Davao Occidental - Region XI (DAVAO Region)Davao Oriental - Region XI (DAVAO Region)Dinagat Islands - Region XIII (CARAGA)Eastern Samar - Region VIII (Eastern Visayas)Guimaras - Region VI (Western Visayas)Ifugao - CAR (Cordillera Administrative Region)Ilocos Norte - Region I (Ilocos Region)Ilocos Sur - Region I (Ilocos Region)Iloilo - Region VI (Western Visayas)Isabela - Region II (Cagayan Valley)Kalinga - CAR (Cordillera Administrative Region)Laguna - Region IV-A (CALABARZON)Lanao Del Norte - Region X (NORTHERN MINDANAO)Lanao Del Sur - BARMM (Bangsamoro Region)La Union - Region I (Ilocos Region)Leyte - Region VIII (Eastern Visayas)Maguindanao - BARMM (Bangsamoro Region)Marinduque - Region IV-B (MiMaRoPa)Masbate - Region V (Bicol Region)Metro Manila 1st District - NCR (National Capital Region)Metro Manila 2nd District - NCR (National Capital Region)Metro Manila 3rd District - NCR (National Capital Region)Metro Manila 4th District - NCR (National Capital Region)Misamis Occidental - Region X (NORTHERN MINDANAO)Misamis Oriental - Region X (NORTHERN MINDANAO)Mountain Province - CAR (Cordillera Administrative Region)Negros Occidental - Region VI (Western Visayas)Negros Oriental - Region VII (Central Visayas)Northern Samar - Region VIII (Eastern Visayas)Nueva Ecija - Region III (Central Luzon)Nueva Vizcaya - Region II (Cagayan Valley)Occidental Mindoro - Region IV-B (MiMaRoPa)Oriental Mindoro - Region IV-B (MiMaRoPa)Palawan - Region IV-B (MiMaRoPa)Pampanga - Region III (Central Luzon)Pangasinan - Region I (Ilocos Region)Quezon - Region IV-A (CALABARZON)Quirino - Region II (Cagayan Valley)Rizal - Region IV-A (CALABARZON)Romblon - Region IV-B (MiMaRoPa)SAMAR (WESTERN SAMAR) - Region VIII (Eastern Visayas)Sarangani - Region XII (SOCCSKSARGEN)Siquijor - Region VII (Central Visayas)Sorsogon - Region V (Bicol Region)South Cotabato - Region XII (SOCCSKSARGEN)Southern Leyte - Region VIII (Eastern Visayas)Sultan Kudarat - Region XII (SOCCSKSARGEN)Sulu - BARMM (Bangsamoro Region)Surigao Del Norte - Region XIII (CARAGA)Surigao Del Sur - Region XIII (CARAGA)Tarlac - Region III (Central Luzon)Tawi-Tawi - BARMM (Bangsamoro Region)Test Aklan - XXX Region VI XXXTest Ilocos Norte - Region I (Ilocos Region)Zambales - Region III (Central Luzon)Zamboanga Del Norte - Region IX (Zamboanga Peninsula)Zamboanga Del Sur - Region IX (Zamboanga Peninsula)Zamboanga Sibugay - Region IX (Zamboanga Peninsula)</value>
      <webElementGuid>0b26b486-ca4d-4601-9c10-3d22b15a6863</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cboPhyProvince&quot;)</value>
      <webElementGuid>79def374-b83d-4de7-aa56-db728b3256c1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='cboPhyProvince']</value>
      <webElementGuid>516623ac-0d01-46fe-be7d-b0dcf2bf034d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='2']/div/div/div/div[3]/div/div/select</value>
      <webElementGuid>8271cc14-8ed2-44be-84de-1701764daf66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[3]/div/div/select</value>
      <webElementGuid>fb941ad4-1aa2-4cbb-afd7-f60dde1dc524</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'cboPhyProvince' and (text() = '--      Select      --Abra - CAR (Cordillera Administrative Region)Agusan Del Norte - Region XIII (CARAGA)Agusan Del Sur - Region XIII (CARAGA)Aklan - Region VI (Western Visayas)Albay - Region V (Bicol Region)Antique - Region VI (Western Visayas)Apayao - CAR (Cordillera Administrative Region)Aurora - Region III (Central Luzon)Basilan - BARMM (Bangsamoro Region)Bataan - Region III (Central Luzon)Batanes - Region II (Cagayan Valley)Batangas - Region IV-A (CALABARZON)Benguet - CAR (Cordillera Administrative Region)Biliran - Region VIII (Eastern Visayas)Bohol - Region VII (Central Visayas)Bukidnon - Region X (NORTHERN MINDANAO)Bulacan - Region III (Central Luzon)Cagayan - Region II (Cagayan Valley)Camarines Norte - Region V (Bicol Region)Camarines Sur - Region V (Bicol Region)Camiguin - Region X (NORTHERN MINDANAO)Capiz - Region VI (Western Visayas)Catanduanes - Region V (Bicol Region)Cavite - Region IV-A (CALABARZON)Cebu - Region VII (Central Visayas)Compostela Valley - Region XI (DAVAO Region)Cotabato - Region XII (SOCCSKSARGEN)COTABATO (NORTH COTABATO) - Region XII (SOCCSKSARGEN)Davao Del Norte - Region XI (DAVAO Region)Davao Del Sur - Region XI (DAVAO Region)Davao Occidental - Region XI (DAVAO Region)Davao Oriental - Region XI (DAVAO Region)Dinagat Islands - Region XIII (CARAGA)Eastern Samar - Region VIII (Eastern Visayas)Guimaras - Region VI (Western Visayas)Ifugao - CAR (Cordillera Administrative Region)Ilocos Norte - Region I (Ilocos Region)Ilocos Sur - Region I (Ilocos Region)Iloilo - Region VI (Western Visayas)Isabela - Region II (Cagayan Valley)Kalinga - CAR (Cordillera Administrative Region)Laguna - Region IV-A (CALABARZON)Lanao Del Norte - Region X (NORTHERN MINDANAO)Lanao Del Sur - BARMM (Bangsamoro Region)La Union - Region I (Ilocos Region)Leyte - Region VIII (Eastern Visayas)Maguindanao - BARMM (Bangsamoro Region)Marinduque - Region IV-B (MiMaRoPa)Masbate - Region V (Bicol Region)Metro Manila 1st District - NCR (National Capital Region)Metro Manila 2nd District - NCR (National Capital Region)Metro Manila 3rd District - NCR (National Capital Region)Metro Manila 4th District - NCR (National Capital Region)Misamis Occidental - Region X (NORTHERN MINDANAO)Misamis Oriental - Region X (NORTHERN MINDANAO)Mountain Province - CAR (Cordillera Administrative Region)Negros Occidental - Region VI (Western Visayas)Negros Oriental - Region VII (Central Visayas)Northern Samar - Region VIII (Eastern Visayas)Nueva Ecija - Region III (Central Luzon)Nueva Vizcaya - Region II (Cagayan Valley)Occidental Mindoro - Region IV-B (MiMaRoPa)Oriental Mindoro - Region IV-B (MiMaRoPa)Palawan - Region IV-B (MiMaRoPa)Pampanga - Region III (Central Luzon)Pangasinan - Region I (Ilocos Region)Quezon - Region IV-A (CALABARZON)Quirino - Region II (Cagayan Valley)Rizal - Region IV-A (CALABARZON)Romblon - Region IV-B (MiMaRoPa)SAMAR (WESTERN SAMAR) - Region VIII (Eastern Visayas)Sarangani - Region XII (SOCCSKSARGEN)Siquijor - Region VII (Central Visayas)Sorsogon - Region V (Bicol Region)South Cotabato - Region XII (SOCCSKSARGEN)Southern Leyte - Region VIII (Eastern Visayas)Sultan Kudarat - Region XII (SOCCSKSARGEN)Sulu - BARMM (Bangsamoro Region)Surigao Del Norte - Region XIII (CARAGA)Surigao Del Sur - Region XIII (CARAGA)Tarlac - Region III (Central Luzon)Tawi-Tawi - BARMM (Bangsamoro Region)Test Aklan - XXX Region VI XXXTest Ilocos Norte - Region I (Ilocos Region)Zambales - Region III (Central Luzon)Zamboanga Del Norte - Region IX (Zamboanga Peninsula)Zamboanga Del Sur - Region IX (Zamboanga Peninsula)Zamboanga Sibugay - Region IX (Zamboanga Peninsula)' or . = '--      Select      --Abra - CAR (Cordillera Administrative Region)Agusan Del Norte - Region XIII (CARAGA)Agusan Del Sur - Region XIII (CARAGA)Aklan - Region VI (Western Visayas)Albay - Region V (Bicol Region)Antique - Region VI (Western Visayas)Apayao - CAR (Cordillera Administrative Region)Aurora - Region III (Central Luzon)Basilan - BARMM (Bangsamoro Region)Bataan - Region III (Central Luzon)Batanes - Region II (Cagayan Valley)Batangas - Region IV-A (CALABARZON)Benguet - CAR (Cordillera Administrative Region)Biliran - Region VIII (Eastern Visayas)Bohol - Region VII (Central Visayas)Bukidnon - Region X (NORTHERN MINDANAO)Bulacan - Region III (Central Luzon)Cagayan - Region II (Cagayan Valley)Camarines Norte - Region V (Bicol Region)Camarines Sur - Region V (Bicol Region)Camiguin - Region X (NORTHERN MINDANAO)Capiz - Region VI (Western Visayas)Catanduanes - Region V (Bicol Region)Cavite - Region IV-A (CALABARZON)Cebu - Region VII (Central Visayas)Compostela Valley - Region XI (DAVAO Region)Cotabato - Region XII (SOCCSKSARGEN)COTABATO (NORTH COTABATO) - Region XII (SOCCSKSARGEN)Davao Del Norte - Region XI (DAVAO Region)Davao Del Sur - Region XI (DAVAO Region)Davao Occidental - Region XI (DAVAO Region)Davao Oriental - Region XI (DAVAO Region)Dinagat Islands - Region XIII (CARAGA)Eastern Samar - Region VIII (Eastern Visayas)Guimaras - Region VI (Western Visayas)Ifugao - CAR (Cordillera Administrative Region)Ilocos Norte - Region I (Ilocos Region)Ilocos Sur - Region I (Ilocos Region)Iloilo - Region VI (Western Visayas)Isabela - Region II (Cagayan Valley)Kalinga - CAR (Cordillera Administrative Region)Laguna - Region IV-A (CALABARZON)Lanao Del Norte - Region X (NORTHERN MINDANAO)Lanao Del Sur - BARMM (Bangsamoro Region)La Union - Region I (Ilocos Region)Leyte - Region VIII (Eastern Visayas)Maguindanao - BARMM (Bangsamoro Region)Marinduque - Region IV-B (MiMaRoPa)Masbate - Region V (Bicol Region)Metro Manila 1st District - NCR (National Capital Region)Metro Manila 2nd District - NCR (National Capital Region)Metro Manila 3rd District - NCR (National Capital Region)Metro Manila 4th District - NCR (National Capital Region)Misamis Occidental - Region X (NORTHERN MINDANAO)Misamis Oriental - Region X (NORTHERN MINDANAO)Mountain Province - CAR (Cordillera Administrative Region)Negros Occidental - Region VI (Western Visayas)Negros Oriental - Region VII (Central Visayas)Northern Samar - Region VIII (Eastern Visayas)Nueva Ecija - Region III (Central Luzon)Nueva Vizcaya - Region II (Cagayan Valley)Occidental Mindoro - Region IV-B (MiMaRoPa)Oriental Mindoro - Region IV-B (MiMaRoPa)Palawan - Region IV-B (MiMaRoPa)Pampanga - Region III (Central Luzon)Pangasinan - Region I (Ilocos Region)Quezon - Region IV-A (CALABARZON)Quirino - Region II (Cagayan Valley)Rizal - Region IV-A (CALABARZON)Romblon - Region IV-B (MiMaRoPa)SAMAR (WESTERN SAMAR) - Region VIII (Eastern Visayas)Sarangani - Region XII (SOCCSKSARGEN)Siquijor - Region VII (Central Visayas)Sorsogon - Region V (Bicol Region)South Cotabato - Region XII (SOCCSKSARGEN)Southern Leyte - Region VIII (Eastern Visayas)Sultan Kudarat - Region XII (SOCCSKSARGEN)Sulu - BARMM (Bangsamoro Region)Surigao Del Norte - Region XIII (CARAGA)Surigao Del Sur - Region XIII (CARAGA)Tarlac - Region III (Central Luzon)Tawi-Tawi - BARMM (Bangsamoro Region)Test Aklan - XXX Region VI XXXTest Ilocos Norte - Region I (Ilocos Region)Zambales - Region III (Central Luzon)Zamboanga Del Norte - Region IX (Zamboanga Peninsula)Zamboanga Del Sur - Region IX (Zamboanga Peninsula)Zamboanga Sibugay - Region IX (Zamboanga Peninsula)')]</value>
      <webElementGuid>a23a18b8-1373-4510-8560-274e0307d15f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
