<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_--Select--BeneficiaryLegal Dependent_a71cea</name>
   <tag></tag>
   <elementGuidId>13aa251c-40a5-4503-890e-5c1fe835befb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cboRemarks1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='cboRemarks1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>9c384318-b1a9-43b4-910f-0296cc167262</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cboRemarks1</value>
      <webElementGuid>88ca908b-6bc1-4a6f-b0d8-84f84e2b87ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>3dca77da-7521-49b2-aa73-8a4c213935b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>beneficiaryRemarks($('#txtBeneficiaryBday1').val(), $('#cboWithDisability1').val(),$('#cboRemarks1').val(),'#cboRemarks1');</value>
      <webElementGuid>7fb8d264-9fb9-4237-8bdb-c82316a93c38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control required gb-border-fcs font-9</value>
      <webElementGuid>096ff3b9-6d16-4d34-8681-ba01b8088fc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>--Select--BeneficiaryLegal DependentLegal Dependent and Beneficiary</value>
      <webElementGuid>10540ffe-f536-4fcd-b862-96613664a488</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cboRemarks1&quot;)</value>
      <webElementGuid>71b7cd9c-399d-4f09-9c84-1c3c26dff9ce</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='cboRemarks1']</value>
      <webElementGuid>05db61a4-144f-4cd9-bd04-784b350b6948</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='row1']/div/div[10]/div/div/select</value>
      <webElementGuid>1389ae9d-96de-4d37-82e7-921d492385ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div[10]/div/div/select</value>
      <webElementGuid>181fc329-2ff5-439d-b82f-a15ac423ffde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'cboRemarks1' and (text() = '--Select--BeneficiaryLegal DependentLegal Dependent and Beneficiary' or . = '--Select--BeneficiaryLegal DependentLegal Dependent and Beneficiary')]</value>
      <webElementGuid>191db94f-2304-4c20-a3b5-3db7d4ca2d7e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
