<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_--Select--NewTransferred</name>
   <tag></tag>
   <elementGuidId>95d50f74-9d91-49ca-b459-f45931926188</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cboMembershiptype</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='cboMembershiptype']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>2a4dce33-cc19-4bbd-9b63-e99fb5100dca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cboMembershiptype</value>
      <webElementGuid>448ca273-98ff-4fa8-a776-616ba209e875</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>computeAge2()</value>
      <webElementGuid>d69e844d-cb01-4f98-88cd-0d5c7ce21984</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control gb-border-fcs select2 font-11</value>
      <webElementGuid>af549901-2977-44e8-bb30-55647286057b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>select2</value>
      <webElementGuid>3d527df7-b328-43dc-9c69-e9e6e68cc5e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>--Select--NewTransferred</value>
      <webElementGuid>2215df96-1391-4764-8bf9-0cfa91edd792</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cboMembershiptype&quot;)</value>
      <webElementGuid>730caacd-8781-4169-bddc-7cf0c39a43d5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='cboMembershiptype']</value>
      <webElementGuid>6ab73ede-79ee-4fad-af2a-4bea44da2548</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='0']/div/div/div[2]/div/div/div[3]/div/select</value>
      <webElementGuid>3218defc-06cd-485c-bebe-dcc20a4516a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>29d2f807-e8fb-4e9f-9a50-233482289442</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'cboMembershiptype' and (text() = '--Select--NewTransferred' or . = '--Select--NewTransferred')]</value>
      <webElementGuid>050371a2-9e2f-491e-8f14-69feed3ce92b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
