<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_--      Select      --0 - Hindi8 - Oo</name>
   <tag></tag>
   <elementGuidId>6e797e50-04c0-4df8-a799-ccee62d5a5b7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cbotenthQAnswer</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='cbotenthQAnswer']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>6f7e5204-dfa8-431a-9b20-f44974281369</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>validatelenght required gb-border-fcs form-control Ans</value>
      <webElementGuid>843a9007-e668-4717-ae3f-dc11884c9fd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cbotenthQAnswer</value>
      <webElementGuid>3973d228-9d25-4a42-8f80-bc7290c65f31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>--      Select      --[0] - Hindi[8] - Oo</value>
      <webElementGuid>682837b3-2e5b-4c58-9771-ee3fa7efa253</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cbotenthQAnswer&quot;)</value>
      <webElementGuid>1ebaf934-fb4b-4882-99bf-7d420badd9db</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='cbotenthQAnswer']</value>
      <webElementGuid>ceef1e0e-542b-4f05-87b3-7679abe29929</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='tblPPIBodyTenth']/tr/td[2]/select</value>
      <webElementGuid>8ef8e78d-9c6e-4ef1-b71c-07a1446387a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tbody[10]/tr/td[2]/select</value>
      <webElementGuid>6b73bc03-b42d-4e30-8927-a3548b0201f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'cbotenthQAnswer' and (text() = '--      Select      --[0] - Hindi[8] - Oo' or . = '--      Select      --[0] - Hindi[8] - Oo')]</value>
      <webElementGuid>71d22089-379f-415a-8667-a5a3c7dbe564</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
