<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select      01020</name>
   <tag></tag>
   <elementGuidId>c4816ef5-2d3a-4334-90f8-cacf6094038d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cbofourthRiskAnswer</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='cbofourthRiskAnswer']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>78004eee-6622-4a95-84c3-f965dbbcb466</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-center gb-border-fcs Ans4</value>
      <webElementGuid>befa4690-a059-4d44-8856-c43c63c5f452</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cbofourthRiskAnswer</value>
      <webElementGuid>e627f9f9-4d21-4b7f-87af-3892ce88937d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>     Select      01020</value>
      <webElementGuid>bdb09315-8229-40ce-a7db-9317b2b1d75e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cbofourthRiskAnswer&quot;)</value>
      <webElementGuid>d435d45c-ea6f-4dcd-a0eb-8e78d6760cea</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='cbofourthRiskAnswer']</value>
      <webElementGuid>682879a2-19fa-4711-a6da-f3f462b94b66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='tblRiskclassFourthBody']/tr/td[9]/select</value>
      <webElementGuid>756b71c4-7929-4e6c-a0b8-e5f535d68968</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tbody[4]/tr/td[9]/select</value>
      <webElementGuid>86607753-4572-4f3d-a2c6-8fb578a8a3d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'cbofourthRiskAnswer' and (text() = '     Select      01020' or . = '     Select      01020')]</value>
      <webElementGuid>99f8b7b2-deb4-41c7-93f1-672be094c8c9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
