<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select      51020</name>
   <tag></tag>
   <elementGuidId>1893a114-eeaf-4a38-9da1-9b46baf05324</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cbothirdRiskAnswer</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='cbothirdRiskAnswer']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>6cad5de5-3f96-475a-a11e-507903e1ea8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-center gb-border-fcs Ans3</value>
      <webElementGuid>a91714be-b202-4321-b5d9-09be4817a0d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cbothirdRiskAnswer</value>
      <webElementGuid>08cbf92c-fe28-4774-bac0-55dae9968628</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>     Select      51020</value>
      <webElementGuid>d49e6e74-32a5-4d4a-a77f-bd20eecd7022</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cbothirdRiskAnswer&quot;)</value>
      <webElementGuid>d41b3692-1edd-4f11-93a6-1769c2ccc551</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='cbothirdRiskAnswer']</value>
      <webElementGuid>2e7c061d-cdfc-4680-8e35-2b6dcf0f53aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='tblRiskclassThirdBody']/tr/td[9]/select</value>
      <webElementGuid>05cc29fc-d55e-4223-a86f-ab60e184b8a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tbody[3]/tr/td[9]/select</value>
      <webElementGuid>190c215a-a93e-4430-b030-dd1d5a824bf3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'cbothirdRiskAnswer' and (text() = '     Select      51020' or . = '     Select      51020')]</value>
      <webElementGuid>f671766e-e340-43f4-9e3b-bbe8a1f5c01a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
