<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_--      Select      --0 - Iba pa5 - _f3691f</name>
   <tag></tag>
   <elementGuidId>df33aa69-bb20-41ff-87e8-37e454c5f57b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cboseventhQAnswer</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='cboseventhQAnswer']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>fde25a06-8ee4-417a-8c2a-dde47883ff8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>validatelenght required gb-border-fcs form-control Ans</value>
      <webElementGuid>c55a15a2-133d-4bd3-b398-e48e752a6147</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cboseventhQAnswer</value>
      <webElementGuid>d12c6294-3e37-4a97-961c-d0a1a3a737f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>--      Select      --[0] - Iba pa[5] - Balon[10] - Pansariling gamit, gripo, pangkomunidad na sistema ng tubig[7] - Pansariling gamit, may tubong balon o may tubong mababaw na balon[7] - Pinaghahatian, gripo, pangkomunidad na sistema ng tubig[6] - Pinaghahatian, may tubong malalim na balon</value>
      <webElementGuid>9d7d2904-e50e-4a03-831b-2b665ed2d4e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cboseventhQAnswer&quot;)</value>
      <webElementGuid>d89a1be7-fb36-4314-835a-495b4c72c660</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='cboseventhQAnswer']</value>
      <webElementGuid>6fa4d0ff-cc21-4564-8e34-15cd3252caae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='tblPPIBodySeventh']/tr/td[2]/select</value>
      <webElementGuid>fdc315e6-d413-4f5c-8947-b37a6ecc556b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tbody[7]/tr/td[2]/select</value>
      <webElementGuid>cd9818ef-aa68-46cc-8c88-6af3aa9376ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'cboseventhQAnswer' and (text() = '--      Select      --[0] - Iba pa[5] - Balon[10] - Pansariling gamit, gripo, pangkomunidad na sistema ng tubig[7] - Pansariling gamit, may tubong balon o may tubong mababaw na balon[7] - Pinaghahatian, gripo, pangkomunidad na sistema ng tubig[6] - Pinaghahatian, may tubong malalim na balon' or . = '--      Select      --[0] - Iba pa[5] - Balon[10] - Pansariling gamit, gripo, pangkomunidad na sistema ng tubig[7] - Pansariling gamit, may tubong balon o may tubong mababaw na balon[7] - Pinaghahatian, gripo, pangkomunidad na sistema ng tubig[6] - Pinaghahatian, may tubong malalim na balon')]</value>
      <webElementGuid>029e8985-7e1e-4818-af0b-5708e9ae952e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
