<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_-- Select --FoodWaterElectricityEduc_adf9e8_1</name>
   <tag></tag>
   <elementGuidId>fd6dddfa-4769-41f0-ab25-b8924d04804e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='cborowExpense2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cborowExpense2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>e1127654-96fe-484a-81be-500ae7679ec5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-select required gb-border-fcs</value>
      <webElementGuid>d292407b-7388-4a53-bc25-847658fd4406</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cborowExpense2</value>
      <webElementGuid>28876714-bcb7-4818-892f-c60e8bba2ea8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-- Select --FoodWaterElectricityEducation/TuitionSalary of  WorkersAllowances and TransportationTransportation/GasolineClothingEntertainment/RecreationMedical ExpensesAmortization of  other loansHouse rentalOthers</value>
      <webElementGuid>802ef7e7-ba24-4ed7-9d40-2e7b0d7ba79c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cborowExpense2&quot;)</value>
      <webElementGuid>9aaccbfa-9163-45bc-a08f-a2705d978c29</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='cborowExpense2']</value>
      <webElementGuid>c2f3f45f-e01b-455b-abeb-8ed20b9395e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='inputRow2']/div/div/select)[2]</value>
      <webElementGuid>bb2ac721-7fbb-4612-bf44-2f895f90cb13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/div/div/div/select</value>
      <webElementGuid>bcc8a975-bb37-44e4-977d-d892f366ca34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'cborowExpense2' and (text() = '-- Select --FoodWaterElectricityEducation/TuitionSalary of  WorkersAllowances and TransportationTransportation/GasolineClothingEntertainment/RecreationMedical ExpensesAmortization of  other loansHouse rentalOthers' or . = '-- Select --FoodWaterElectricityEducation/TuitionSalary of  WorkersAllowances and TransportationTransportation/GasolineClothingEntertainment/RecreationMedical ExpensesAmortization of  other loansHouse rentalOthers')]</value>
      <webElementGuid>af340582-5585-4d25-86f9-b91ba10d94e2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
