<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_--      Select      --0 - Magaang ma_840447</name>
   <tag></tag>
   <elementGuidId>849c5780-6660-4f06-9b5b-d93bbc39c2ec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cbofifthQAnswer</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='cbofifthQAnswer']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>16289eb5-9acc-4e21-bcf5-f8ec1b896965</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>validatelenght required gb-border-fcs form-control Ans</value>
      <webElementGuid>cb3a98da-438b-438a-929c-5b04c00d2011</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cbofifthQAnswer</value>
      <webElementGuid>9aa74b62-c914-4ea0-81af-3e32c1854e67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>--      Select      --[0] - Magaang materyales (kawayan, sawali,cogon, nipa, anahaw), Isinalba/ pansamantalang materyales, Magkahalo ngunit mas marami ang magagaang materyales, Magkahalo ngunit mas maraming isinalbang materyales[7] - Magkahalo ngunit mas maraming matitibay na materyales[8] - Matitibay na materyales (yero, aluminum, tile, semento, brick, bato, kahoy, plywood, asbestos)</value>
      <webElementGuid>46fbd956-52e0-4b9f-bb6e-641eb3ccf8b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cbofifthQAnswer&quot;)</value>
      <webElementGuid>379c86cb-3edd-4c84-9056-ebe55f37eec1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='cbofifthQAnswer']</value>
      <webElementGuid>71bc9937-6a60-4a0d-b9d3-02bdb87f1475</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='tblPPIBodyFifth']/tr/td[2]/select</value>
      <webElementGuid>96668822-f188-4696-a531-b9881959f86b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tbody[5]/tr/td[2]/select</value>
      <webElementGuid>2465cbbe-698f-4812-b0f4-d7d4f1092d33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'cbofifthQAnswer' and (text() = '--      Select      --[0] - Magaang materyales (kawayan, sawali,cogon, nipa, anahaw), Isinalba/ pansamantalang materyales, Magkahalo ngunit mas marami ang magagaang materyales, Magkahalo ngunit mas maraming isinalbang materyales[7] - Magkahalo ngunit mas maraming matitibay na materyales[8] - Matitibay na materyales (yero, aluminum, tile, semento, brick, bato, kahoy, plywood, asbestos)' or . = '--      Select      --[0] - Magaang materyales (kawayan, sawali,cogon, nipa, anahaw), Isinalba/ pansamantalang materyales, Magkahalo ngunit mas marami ang magagaang materyales, Magkahalo ngunit mas maraming isinalbang materyales[7] - Magkahalo ngunit mas maraming matitibay na materyales[8] - Matitibay na materyales (yero, aluminum, tile, semento, brick, bato, kahoy, plywood, asbestos)')]</value>
      <webElementGuid>13efca3c-2c10-478e-a66c-ac4aaaf2ed52</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
