<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_--      Select      --0 - Hindi11 - Oo</name>
   <tag></tag>
   <elementGuidId>d80aa593-5db1-4838-adbe-8b06a5c05690</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cboninthQAnswer</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='cboninthQAnswer']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>0ebd4e23-559c-4e5b-bb64-558764a21dd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>validatelenght required gb-border-fcs form-control Ans</value>
      <webElementGuid>3d2388bc-6f81-48cc-b143-4a50b6c59d04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cboninthQAnswer</value>
      <webElementGuid>c8e6b5dc-2821-4e36-a26a-bb2e7bb3e642</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>--      Select      --[0] - Hindi[11] - Oo</value>
      <webElementGuid>ce76cfe6-1579-4d2b-8aa6-55e7975c94be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cboninthQAnswer&quot;)</value>
      <webElementGuid>afe39b5e-2834-4a1e-b623-f63d3640b9ae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='cboninthQAnswer']</value>
      <webElementGuid>fcd15ad3-c031-428e-be4f-a273690fa49a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='tblPPIBodyNinth']/tr/td[2]/select</value>
      <webElementGuid>51eb4cb1-b42b-4c6c-992c-186e217eccc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tbody[9]/tr/td[2]/select</value>
      <webElementGuid>364e626f-a18f-4a82-8ea0-d35effba80c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'cboninthQAnswer' and (text() = '--      Select      --[0] - Hindi[11] - Oo' or . = '--      Select      --[0] - Hindi[11] - Oo')]</value>
      <webElementGuid>be76462f-4c13-4658-9e37-ce10e3ba5e6f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
