<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_--      Select      --villagevillage_79bc42</name>
   <tag></tag>
   <elementGuidId>8ad4d1e6-087d-4a8e-83a0-008ad1740ca3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cboCustomerCenter</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='cboCustomerCenter']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>cd0d513e-5ad1-4240-a3ef-9b8d66a1244e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cboCustomerCenter</value>
      <webElementGuid>03011b99-8418-4178-b25c-557c1156536f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control gb-border-fcs select2 font-11</value>
      <webElementGuid>b0ab191b-22fd-4ba3-9330-18c3bed5a72e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>select2</value>
      <webElementGuid>d853f64d-1b7b-4317-aed6-70f84ae69f7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>--      Select      --villagevillage 2village 3Village 4Village 5village 9village 8Village 7Village 6</value>
      <webElementGuid>99ed946d-1958-4f21-80c5-b0d5c2113f53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cboCustomerCenter&quot;)</value>
      <webElementGuid>19901bc0-78d1-4c6c-a073-2ffe5a23bb83</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='cboCustomerCenter']</value>
      <webElementGuid>bf96fb64-ec3b-45fe-89c8-e3026b123fc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='0']/div/div/div[2]/div[2]/div[20]/div/div/select</value>
      <webElementGuid>971f68c3-51f6-4ac3-8d69-13dabdcc4b3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[20]/div/div/select</value>
      <webElementGuid>a76ee405-4683-4001-839d-1b0a28bdab5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'cboCustomerCenter' and (text() = '--      Select      --villagevillage 2village 3Village 4Village 5village 9village 8Village 7Village 6' or . = '--      Select      --villagevillage 2village 3Village 4Village 5village 9village 8Village 7Village 6')]</value>
      <webElementGuid>a9d79a0b-b4c1-4baf-9325-097fe02f22b0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
