<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_--      Select      --0 - 7 o higit _f836c6</name>
   <tag></tag>
   <elementGuidId>de32535c-a7c9-4cb4-a87b-894dfae0df77</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cbosecondQAnswer</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='cbosecondQAnswer']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>0e154806-62c0-453e-9aae-0040e2093706</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>validatelenght required gb-border-fcs form-control Ans</value>
      <webElementGuid>fbbfd4d8-8118-469d-9c51-bc52341e57d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cbosecondQAnswer</value>
      <webElementGuid>faa86744-5570-4bf9-ba3b-373dd87565db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>--      Select      --[0] - 7 o higit pa[9] - 5 - 6[18] - 4 pababa</value>
      <webElementGuid>fce03862-f8fd-4bba-a3bf-fabae71a542b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cbosecondQAnswer&quot;)</value>
      <webElementGuid>c27607d9-78fe-427e-a2e1-fca37ad5cca8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='cbosecondQAnswer']</value>
      <webElementGuid>9bfbafb4-8fb0-42fa-b126-161847e89b1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='tblPPIBodySecond']/tr/td[2]/select</value>
      <webElementGuid>3b272ea7-764f-47f8-9484-b6301059be42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tbody[2]/tr/td[2]/select</value>
      <webElementGuid>1a6d0518-795d-4d6b-8680-e86dd04df507</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'cbosecondQAnswer' and (text() = '--      Select      --[0] - 7 o higit pa[9] - 5 - 6[18] - 4 pababa' or . = '--      Select      --[0] - 7 o higit pa[9] - 5 - 6[18] - 4 pababa')]</value>
      <webElementGuid>7977ab6b-0f3c-48f4-8765-925376fc3283</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
