<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_--      Select      --AlaminosBayBia_8f7d3f_1</name>
   <tag></tag>
   <elementGuidId>e654778c-d5b6-4a08-96c4-d477edc75cff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cboPhyMunicipalityCity</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='cboPhyMunicipalityCity']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>22abc5e5-2cc8-437b-b49b-7bd766293e37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cboPhyMunicipalityCity</value>
      <webElementGuid>cc100ad2-b5a2-4ac8-8318-de0c22c05841</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control gb-border-fcs font-11</value>
      <webElementGuid>843a8833-6fcf-495a-8743-c0bf4bd88db2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>--      Select      --AlaminosBayBiñan CityCabuyao CityCalamba CityCalauanCavintiFamyKalayaanLiliwLos BañosLuisianaLumbanMabitacMagdalenaMajayjayNagcarlanPaetePagsanjanPakilPangilPilaRizalSan Pablo CitySan Pedro CitySiniloanSta. CruzSta. MariaSta. Rosa CityVictoria</value>
      <webElementGuid>dbe37412-6f2e-4031-b3f6-d1e9c7b24310</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cboPhyMunicipalityCity&quot;)</value>
      <webElementGuid>19d01c7f-4600-4167-96ce-e13c1069b3b8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='cboPhyMunicipalityCity']</value>
      <webElementGuid>2999e0f1-f199-4ec9-a3c2-add56643a2e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='2']/div/div/div/div[4]/div/div/select</value>
      <webElementGuid>6eac19d5-d58b-4a7b-8897-b38e310aa412</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[4]/div/div/select</value>
      <webElementGuid>541e8147-89d0-4d26-a2db-acd5e6b7654d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'cboPhyMunicipalityCity' and (text() = '--      Select      --AlaminosBayBiñan CityCabuyao CityCalamba CityCalauanCavintiFamyKalayaanLiliwLos BañosLuisianaLumbanMabitacMagdalenaMajayjayNagcarlanPaetePagsanjanPakilPangilPilaRizalSan Pablo CitySan Pedro CitySiniloanSta. CruzSta. MariaSta. Rosa CityVictoria' or . = '--      Select      --AlaminosBayBiñan CityCabuyao CityCalamba CityCalauanCavintiFamyKalayaanLiliwLos BañosLuisianaLumbanMabitacMagdalenaMajayjayNagcarlanPaetePagsanjanPakilPangilPilaRizalSan Pablo CitySan Pedro CitySiniloanSta. CruzSta. MariaSta. Rosa CityVictoria')]</value>
      <webElementGuid>57c4f970-03fa-47d7-ac52-0e30572beaed</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
