<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select      51015</name>
   <tag></tag>
   <elementGuidId>47d6c36e-a904-4efd-b829-af14899291ea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cboRiskAnswerList</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='cboRiskAnswerList']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>7f015553-81f4-4557-bd79-f10cf778c68f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-center gb-border-fcs Ans1</value>
      <webElementGuid>d3fecb06-8842-4b23-ab44-f05f72ff0cb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cboRiskAnswerList</value>
      <webElementGuid>6c96c7de-984f-42d7-ac9d-26c9b419830f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>     Select      51015</value>
      <webElementGuid>5c05044f-ece9-43a4-a989-6f12188cb37e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cboRiskAnswerList&quot;)</value>
      <webElementGuid>99855900-0215-4484-90ca-e46012fe0fe7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='cboRiskAnswerList']</value>
      <webElementGuid>91c72d58-80c7-4215-b3f8-5687cbe5091e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='tblRiskclassPriBody']/tr/td[9]/select</value>
      <webElementGuid>a6b05c50-3d14-4603-8d3e-92f1836d63ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[9]/select</value>
      <webElementGuid>6e8db2b4-c981-444d-bdf3-90987e29d713</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'cboRiskAnswerList' and (text() = '     Select      51015' or . = '     Select      51015')]</value>
      <webElementGuid>0b205d88-da63-4146-9293-a62926582f78</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
