<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_--      Select      --0 - Magaang ma_b84cbb</name>
   <tag></tag>
   <elementGuidId>c50c1f47-7666-45c2-b7ab-b3f3d3a89837</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cbofourthQAnswer</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='cbofourthQAnswer']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>d0106435-e294-4976-a212-d2cd84153b85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>validatelenght required gb-border-fcs form-control Ans</value>
      <webElementGuid>a0c67af1-dbe4-49f5-9efd-69c5f3f41501</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cbofourthQAnswer</value>
      <webElementGuid>09278eef-2f0e-477a-b535-df65695173fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>--      Select      --[0] - Magaang materyales (cogon, nipa, anahaw), Isinalba/ pansamantalang materyales, Magkahalo ngunit mas maraming isinalbang materyales[5] - Magkahalo ngunit mas maraming matitibay na materyales[6] - Matitibay na materyales (yero, aluminum, tile, konkreto, brick, bato, asbestos</value>
      <webElementGuid>db387329-2ef8-467b-8542-f385b86b13ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cbofourthQAnswer&quot;)</value>
      <webElementGuid>86809766-d98f-4625-a88c-ea912df00c4f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='cbofourthQAnswer']</value>
      <webElementGuid>6a68f0d1-69ef-4516-bbe4-64c7bb94bfe3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='tblPPIBodyFourth']/tr/td[2]/select</value>
      <webElementGuid>384b5032-ab40-4708-aada-442fcdfb28d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tbody[4]/tr/td[2]/select</value>
      <webElementGuid>0f84ec74-b790-450a-80cd-d24eb4c4fd18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'cbofourthQAnswer' and (text() = '--      Select      --[0] - Magaang materyales (cogon, nipa, anahaw), Isinalba/ pansamantalang materyales, Magkahalo ngunit mas maraming isinalbang materyales[5] - Magkahalo ngunit mas maraming matitibay na materyales[6] - Matitibay na materyales (yero, aluminum, tile, konkreto, brick, bato, asbestos' or . = '--      Select      --[0] - Magaang materyales (cogon, nipa, anahaw), Isinalba/ pansamantalang materyales, Magkahalo ngunit mas maraming isinalbang materyales[5] - Magkahalo ngunit mas maraming matitibay na materyales[6] - Matitibay na materyales (yero, aluminum, tile, konkreto, brick, bato, asbestos')]</value>
      <webElementGuid>0c558726-44dc-41d9-8884-9112e71be55b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
