<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_--Select--EmploymentSalariesIncome f_b99596</name>
   <tag></tag>
   <elementGuidId>2991b63d-beca-475c-9e79-d86ea47632e3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cboKYCSourceOfIncome</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='cboKYCSourceOfIncome']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>5aac4676-c966-4b7f-98c1-b6c656713ded</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cboKYCSourceOfIncome</value>
      <webElementGuid>32bb4aaf-5360-4d1f-92fb-eaa94b72860c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>checksourceOfFund();</value>
      <webElementGuid>46d9dbb6-3d55-4c38-bb0e-c88886828369</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control gb-border-fcs font-11</value>
      <webElementGuid>74f1cea6-ab7c-4979-9153-31f3e6745e2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>--Select--Employment/SalariesIncome from businessInheritanceOthersProceeds from investmentRemittancesRetirement/Pension</value>
      <webElementGuid>72737b20-6330-4360-a335-c2e74097121a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cboKYCSourceOfIncome&quot;)</value>
      <webElementGuid>6eac0ff7-b1d7-4aac-801e-148b7982cb31</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='cboKYCSourceOfIncome']</value>
      <webElementGuid>fbe5647d-7fc9-4709-be04-ba337c248d53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='7']/div/div/div/div[3]/div/div/select</value>
      <webElementGuid>79f6e2b7-f3ad-44ee-9199-cdc09174596b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/div/div[3]/div/div/select</value>
      <webElementGuid>43fd3872-e2e7-48f4-ba69-fba15885ba98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'cboKYCSourceOfIncome' and (text() = '--Select--Employment/SalariesIncome from businessInheritanceOthersProceeds from investmentRemittancesRetirement/Pension' or . = '--Select--Employment/SalariesIncome from businessInheritanceOthersProceeds from investmentRemittancesRetirement/Pension')]</value>
      <webElementGuid>3b0fcac3-a72b-4c28-b428-d5d27a8bfe96</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
