<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_-- Select --Atty.Dr.Eng.Hon.MrMrsMs</name>
   <tag></tag>
   <elementGuidId>53c2e32f-5a38-4b36-80cd-285379ce949f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cboTitle</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='cboTitle']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>802d43e8-5702-4662-b92e-76a3e8e37431</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cboTitle</value>
      <webElementGuid>b0fecc8e-5b87-4fde-a2ec-c39e5a803293</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>validateTitle();</value>
      <webElementGuid>8d6e2850-9f32-4d78-a4a4-1fbe6aa05702</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control gb-border-fcs select2 font-11</value>
      <webElementGuid>95626b14-e22d-47eb-b940-ba857491d3fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>select2</value>
      <webElementGuid>6f44d72b-c11a-4bbf-8bda-6e6ec3180c25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
																		-- Select --Atty.Dr.Eng.Hon.MrMrsMs</value>
      <webElementGuid>e73074e2-c556-4e71-a662-bfabb6f66106</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cboTitle&quot;)</value>
      <webElementGuid>77ebb9e9-ea66-4676-98e7-3a9a04a15dd1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='cboTitle']</value>
      <webElementGuid>5ebb31cf-8410-49e7-9374-f1a4bfe8d466</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='0']/div/div/div[2]/div/div/div[5]/div/select</value>
      <webElementGuid>22579b27-1390-446b-8bfe-6016bf0a0e76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/select</value>
      <webElementGuid>915b49f7-0eae-43de-9a0c-f249f1d5b099</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'cboTitle' and (text() = '
																		-- Select --Atty.Dr.Eng.Hon.MrMrsMs' or . = '
																		-- Select --Atty.Dr.Eng.Hon.MrMrsMs')]</value>
      <webElementGuid>538f7734-038c-4b1f-91c6-91dc4a65c713</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
