<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_--Select--DSHPGLIP 1GLIP 2IPPaglambo_b40e80</name>
   <tag></tag>
   <elementGuidId>c396021e-b604-483e-bcd7-0c55d3f0e470</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cboSubClassification</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='cboSubClassification']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>2af116fe-557b-44da-a115-3b123045dbde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cboSubClassification</value>
      <webElementGuid>72b9d110-6d4a-403b-b1f8-873f6a851051</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>membershipClassification();</value>
      <webElementGuid>a00c29f4-3a13-428a-ace0-b8b86fe4ec05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control required gb-border-fcs select2 font-11</value>
      <webElementGuid>c2184e4f-c0fd-4599-ac4d-d3b58cab3378</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>select2</value>
      <webElementGuid>7fa8236f-8305-4a12-bdbb-049fde4a7910</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>--Select--DSHPGLIP 1GLIP 2IPPaglamboRegular Client</value>
      <webElementGuid>3ece68b5-56b1-497e-984b-9ece285fc513</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cboSubClassification&quot;)</value>
      <webElementGuid>20fd0d30-1824-4f7a-8ec9-3b99e0430de9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='cboSubClassification']</value>
      <webElementGuid>3df47cea-6df7-446d-8809-595e07ea4371</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='8']/div/div/div/div[3]/div/div/select</value>
      <webElementGuid>d2ca25df-9b22-4506-9d36-259bf85154a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div/div/div[3]/div/div/select</value>
      <webElementGuid>72a0d2d2-27ce-4e76-9c69-3ccf59296166</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'cboSubClassification' and (text() = '--Select--DSHPGLIP 1GLIP 2IPPaglamboRegular Client' or . = '--Select--DSHPGLIP 1GLIP 2IPPaglamboRegular Client')]</value>
      <webElementGuid>d7bf9ae5-a0d9-47a7-888b-9d0d1fe7bad8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
