<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_-- Select --CARD MRI MemberCARD MRI _8bd785</name>
   <tag></tag>
   <elementGuidId>ddf74f04-f08a-4f55-bef6-eda82c3bbae6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cboReferredbyPrimary</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='cboReferredbyPrimary']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>fdc7abd1-f562-4b52-b229-6caac661b25c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cboReferredbyPrimary</value>
      <webElementGuid>743d2a79-4fcd-4754-b086-2b3a232ee6aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>Referredby();</value>
      <webElementGuid>08cd201d-696b-40d5-b30c-c0bfe27928ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control gb-border-fcs font-11</value>
      <webElementGuid>2d51e7ca-d740-4a47-a9bf-9f37d2c2cac1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-- Select --CARD MRI MemberCARD MRI StaffOthers</value>
      <webElementGuid>193d7b9c-9523-49b5-8ffa-f8ace6014a1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cboReferredbyPrimary&quot;)</value>
      <webElementGuid>1372303f-2825-4989-8b20-40a7b5d2d48d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='cboReferredbyPrimary']</value>
      <webElementGuid>5a8b5a23-e656-4558-ab39-8173f770f532</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='4']/div/div/div/div[7]/div/div/select</value>
      <webElementGuid>5acfdafe-f725-4def-ae0a-a8f9bfa76338</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div[7]/div/div/select</value>
      <webElementGuid>658f2227-dafd-4841-962d-79e72dc4568a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'cboReferredbyPrimary' and (text() = '-- Select --CARD MRI MemberCARD MRI StaffOthers' or . = '-- Select --CARD MRI MemberCARD MRI StaffOthers')]</value>
      <webElementGuid>28c0aae4-ad22-4d58-99a3-8ec457154ad4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
