<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_--Select--farmfarm 2farm 3</name>
   <tag></tag>
   <elementGuidId>e9e7cc4b-6c4f-4c86-8022-f8fcc346d5a5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cboCustomerUnit</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='cboCustomerUnit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>c875505f-3df9-45e5-b0a3-5909cbf9502d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cboCustomerUnit</value>
      <webElementGuid>3ebf95f2-858f-4199-b94f-fa794221cc29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control gb-border-fcs select2 font-11</value>
      <webElementGuid>7f3afa9e-f731-492c-a17b-3cc0caa51c5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>select2</value>
      <webElementGuid>b007c38a-6faf-4e6c-a959-0cac7b14563f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>--Select--farmfarm 2farm 3</value>
      <webElementGuid>cac85f37-8c6e-4f1c-ab22-22ee72976853</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cboCustomerUnit&quot;)</value>
      <webElementGuid>5723a412-31de-4ef9-b8a5-20d0b6140ffc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='cboCustomerUnit']</value>
      <webElementGuid>9f51b265-8707-4f2a-9274-8e3d481cf34b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='0']/div/div/div[2]/div[2]/div[19]/div/div/select</value>
      <webElementGuid>2cf631f5-be84-4161-9b9b-f370834c1579</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[19]/div/div/select</value>
      <webElementGuid>60425d11-b9cf-41c5-9568-ad56bf78f9f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'cboCustomerUnit' and (text() = '--Select--farmfarm 2farm 3' or . = '--Select--farmfarm 2farm 3')]</value>
      <webElementGuid>3a1ae448-bf7a-41f8-a227-9cad8c7c403b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
