<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_--Select--YESNO</name>
   <tag></tag>
   <elementGuidId>dc847140-d8a5-4514-9e4c-5d604b24b614</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cboWithDisability1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='cboWithDisability1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>37c7abe6-8999-43ee-8819-a92a27701315</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cboWithDisability1</value>
      <webElementGuid>20a7fadb-57f9-428f-b828-376128d31522</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>beneficiaryDisability();</value>
      <webElementGuid>4acae981-e85b-4462-bde5-59e6484595a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>a267616b-7938-40df-b434-ddeaf0229ec8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control required gb-border-fcs font-9</value>
      <webElementGuid>961e981a-328b-4df4-99ca-21193dccb075</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
																			--Select--
																			YES
																			NO
																		</value>
      <webElementGuid>1d999aa4-f6a0-4589-b7f3-90ee5a4cbfce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cboWithDisability1&quot;)</value>
      <webElementGuid>0d233f60-40bd-4ac9-b092-ad2a33fecdb6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='cboWithDisability1']</value>
      <webElementGuid>7e576e02-a866-4c18-a920-ad0a17af9347</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='row1']/div/div[7]/div/div/select</value>
      <webElementGuid>fd17cac7-0c2d-49ca-b8e4-309a4acc7064</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div[7]/div/div/select</value>
      <webElementGuid>8e4d2867-f379-488d-a808-4a5f4db6992c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'cboWithDisability1' and (text() = '
																			--Select--
																			YES
																			NO
																		' or . = '
																			--Select--
																			YES
																			NO
																		')]</value>
      <webElementGuid>f77d3a7b-3616-465e-b44e-2d6826bb2f08</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
