<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_--Select--YESNO_1</name>
   <tag></tag>
   <elementGuidId>f49b7ba9-f811-4a5b-bbb0-28b5583ec6e1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cboCardMRIScho1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='cboCardMRIScho1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>7e28a876-4d8f-4622-a7ea-decabe74e0da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cboCardMRIScho1</value>
      <webElementGuid>c80df826-a131-4498-9c15-d095ee7567b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>f0108aa5-7681-4a00-9da1-d2cd3435257e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control required gb-border-fcs font-9</value>
      <webElementGuid>a9277cc6-13c9-4bc6-ab9d-96f7b516a879</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
																			--Select--
																			YES
																			NO
																		</value>
      <webElementGuid>8bda8e94-1dde-4c4d-9491-dcb173ba81eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cboCardMRIScho1&quot;)</value>
      <webElementGuid>f7ee7f77-954d-4f3a-bfa6-600ae87c8d1a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='cboCardMRIScho1']</value>
      <webElementGuid>4450e321-cf46-4f3a-a924-fad2f6634dca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='row1']/div/div[9]/div/div/select</value>
      <webElementGuid>01681a3c-1fbf-468c-8bed-8110c0d66d22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div[9]/div/div/select</value>
      <webElementGuid>5467e458-823d-47d4-86a1-ce361485179c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'cboCardMRIScho1' and (text() = '
																			--Select--
																			YES
																			NO
																		' or . = '
																			--Select--
																			YES
																			NO
																		')]</value>
      <webElementGuid>b225d3cf-4eea-496e-9d10-036e21e1f7e3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
