<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_--Select--BusinessGovernment Employe_69ab64</name>
   <tag></tag>
   <elementGuidId>f71ae7c2-e5d8-4c81-8d7e-c8d25419881a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cboOccupation</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='cboOccupation']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>73ff7b56-ed74-4186-9433-6a0a5a728e1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cboOccupation</value>
      <webElementGuid>aa167f28-9728-460e-aadd-a45971b74a45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control gb-border-fcs select2 font-11</value>
      <webElementGuid>27129929-a2cf-4620-9bbc-960894b19fae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>select2</value>
      <webElementGuid>a4ff55bc-b51c-45aa-b7bd-533225782730</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>--Select--BusinessGovernment EmployeeOthersPrivate Emplovee</value>
      <webElementGuid>3b150b3e-e841-4502-95a6-47350a3554f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cboOccupation&quot;)</value>
      <webElementGuid>3affcb6f-4e0a-4840-b0ae-37cc68dbef6c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='cboOccupation']</value>
      <webElementGuid>2993e1e2-ef61-484b-a20d-8a6110a41d76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='0']/div/div/div[2]/div[2]/div[2]/div/div/select</value>
      <webElementGuid>a49df9ad-c174-4cca-a2c2-66c6c590875a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/select</value>
      <webElementGuid>7c298c1e-bb45-4b20-921d-b2cdd5467c5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'cboOccupation' and (text() = '--Select--BusinessGovernment EmployeeOthersPrivate Emplovee' or . = '--Select--BusinessGovernment EmployeeOthersPrivate Emplovee')]</value>
      <webElementGuid>c3fc34e5-cf18-44d3-9909-c2ffd7ee2027</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
