<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_--Select--Below 1,000 pesos1001 - 3,_8e7891</name>
   <tag></tag>
   <elementGuidId>ea891434-0a8c-4c44-afd5-25e04754d43a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cboHouseholdMonthlyInc</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='cboHouseholdMonthlyInc']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>db58067a-7014-4cee-ab39-31bf96458020</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cboHouseholdMonthlyInc</value>
      <webElementGuid>45d0e8bd-1eea-4186-9a77-bcef28f32cd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control gb-border-fcs font-11</value>
      <webElementGuid>2bdc24b8-d371-4a6e-8fec-ac7ae0caaff3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>--Select--Below 1,000 pesos1001 - 3,000 pesos3001 - 5,000 pesos5001 - 8,000 pesos8001 - 10,000 pesos10001 - 15,000 pesosAbove 15,000 pesos</value>
      <webElementGuid>cb89a121-9bcb-4098-88e0-270e8cfca020</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cboHouseholdMonthlyInc&quot;)</value>
      <webElementGuid>6780a330-ccc4-4c15-8c40-e9c21f156815</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='cboHouseholdMonthlyInc']</value>
      <webElementGuid>44ff729f-b86e-4ea3-b372-037accbc9528</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='7']/div/div/div/div[5]/div/div/select</value>
      <webElementGuid>bdb8074c-7b55-4477-b46b-00fe52ae09fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/div/div[5]/div/div/select</value>
      <webElementGuid>80573e41-5419-42da-b56d-2c2bc7a7d566</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'cboHouseholdMonthlyInc' and (text() = '--Select--Below 1,000 pesos1001 - 3,000 pesos3001 - 5,000 pesos5001 - 8,000 pesos8001 - 10,000 pesos10001 - 15,000 pesosAbove 15,000 pesos' or . = '--Select--Below 1,000 pesos1001 - 3,000 pesos3001 - 5,000 pesos5001 - 8,000 pesos8001 - 10,000 pesos10001 - 15,000 pesosAbove 15,000 pesos')]</value>
      <webElementGuid>5ea370e1-5977-4093-8dc5-368983a095ab</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
