<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_--      Select      --0 - ARMM8 - Il_f2aada</name>
   <tag></tag>
   <elementGuidId>ac755a5c-4e13-4188-8649-22da179b9cef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cboAnswerList</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='cboAnswerList']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>83252346-2f22-4731-9287-8e8218c8a728</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>validatelenght required gb-border-fcs form-control Ans</value>
      <webElementGuid>091e164a-07a6-47cf-9fe1-6d03c7e68c99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cboAnswerList</value>
      <webElementGuid>a1b1eed4-c466-479b-b6f6-2f7933e2d6c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>--      Select      --[0] - ARMM[8] - Ilocos[8] - Cagayan Valley[6] - Central Luzon[9] - Calabarzon[8] - MIMAROPA[5] - Western Mindanao[4] - Bicol[8] - Western Visayas[4] - Central Visayas[2] - Eastern Visayas[0] - Northern Mindanao[6] - Southern Mindanao[2] - Central Mindanao[12] - NCR[7] - CAR[0] - CARAGA</value>
      <webElementGuid>496e19f0-8fd4-4e73-8af9-5988747883bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cboAnswerList&quot;)</value>
      <webElementGuid>5e223f01-07f8-44df-9ee6-8dad68ddcabe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='cboAnswerList']</value>
      <webElementGuid>c7a675c3-55cc-4010-8125-e587ac0dc5ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='tblPPIBody']/tr/td[2]/select</value>
      <webElementGuid>2c5c68f0-b31c-49dc-8dd7-845e1b14e00f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/select</value>
      <webElementGuid>80956221-535a-406d-8d92-ce72d11b01ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'cboAnswerList' and (text() = '--      Select      --[0] - ARMM[8] - Ilocos[8] - Cagayan Valley[6] - Central Luzon[9] - Calabarzon[8] - MIMAROPA[5] - Western Mindanao[4] - Bicol[8] - Western Visayas[4] - Central Visayas[2] - Eastern Visayas[0] - Northern Mindanao[6] - Southern Mindanao[2] - Central Mindanao[12] - NCR[7] - CAR[0] - CARAGA' or . = '--      Select      --[0] - ARMM[8] - Ilocos[8] - Cagayan Valley[6] - Central Luzon[9] - Calabarzon[8] - MIMAROPA[5] - Western Mindanao[4] - Bicol[8] - Western Visayas[4] - Central Visayas[2] - Eastern Visayas[0] - Northern Mindanao[6] - Southern Mindanao[2] - Central Mindanao[12] - NCR[7] - CAR[0] - CARAGA')]</value>
      <webElementGuid>3d818280-1f17-4ee3-9d20-b5b8e964e18b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
