<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_--      Select      --0 - Wala7 - Oo</name>
   <tag></tag>
   <elementGuidId>27d86ff0-cba8-4cd6-9d5c-2364bba19aca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cbosixthQAnswer</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='cbosixthQAnswer']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>fbaa21ca-fb3d-477a-a4c3-c847b913c146</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>validatelenght required gb-border-fcs form-control Ans</value>
      <webElementGuid>5e89ac4a-027d-49cb-a474-4910cefdb405</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cbosixthQAnswer</value>
      <webElementGuid>a17298b4-82ec-4ef1-b2bd-43777eb3bee2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>--      Select      --[0] - Wala[7] - Oo</value>
      <webElementGuid>895a1135-faed-40e1-bea8-518a0a7edbc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cbosixthQAnswer&quot;)</value>
      <webElementGuid>e7999a19-3f22-4035-81fc-0402f02a144d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='cbosixthQAnswer']</value>
      <webElementGuid>2aa036ae-80a7-4751-bd45-6cb69de89f66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='tblPPIBodySixth']/tr/td[2]/select</value>
      <webElementGuid>cac7f1be-10ce-4944-b8f5-d861e4140ce0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tbody[6]/tr/td[2]/select</value>
      <webElementGuid>490555b0-eb3d-425f-8362-8d74c6ab124f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'cbosixthQAnswer' and (text() = '--      Select      --[0] - Wala[7] - Oo' or . = '--      Select      --[0] - Wala[7] - Oo')]</value>
      <webElementGuid>b7292bfc-23d8-4de3-ac77-33b3d8eae6ec</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
