<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select      0030</name>
   <tag></tag>
   <elementGuidId>271be60a-4441-4ab0-9afe-ad2b982d2de0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cbofifthRiskAnswer</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='cbofifthRiskAnswer']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>3775a765-ed2c-419b-8708-e43059e79167</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-center gb-border-fcs Ans5</value>
      <webElementGuid>3b00ef41-4b46-4cde-bcbd-c09dbfcc342c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cbofifthRiskAnswer</value>
      <webElementGuid>10c369e7-c376-45e3-8162-f8642ce8959a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>     Select      0030</value>
      <webElementGuid>44e8960d-d41f-40df-8fee-71583335677a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cbofifthRiskAnswer&quot;)</value>
      <webElementGuid>b584c59c-3758-4420-a5d1-eeb54ec56911</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='cbofifthRiskAnswer']</value>
      <webElementGuid>8519b8b6-4491-4a08-8444-9ff8e6bf7688</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='tblRiskclassFifthBody']/tr/td[9]/select</value>
      <webElementGuid>1dafd2e4-8cd6-4511-93b9-5e02a3f1d9f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tbody[5]/tr/td[9]/select</value>
      <webElementGuid>50bd4a2a-3018-4e8e-8175-959ecd936506</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'cbofifthRiskAnswer' and (text() = '     Select      0030' or . = '     Select      0030')]</value>
      <webElementGuid>4248401d-fc4a-4e95-b6b5-c91e048f1d2b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
