<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_--Select--AglipayanBorn AgainEvangel_87720a</name>
   <tag></tag>
   <elementGuidId>fb59b95e-e11b-4e58-bcd0-deac3c7659f8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cboReligion</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='cboReligion']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>128511ab-6d61-4c47-bbe3-f094b93110b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cboReligion</value>
      <webElementGuid>4e2422ac-557e-42c7-9e52-51af0b54efa8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control gb-border-fcs select2 font-11</value>
      <webElementGuid>88035923-c8b6-44c1-902a-2254d64ebd46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>select2</value>
      <webElementGuid>a884fac2-de7c-424f-a9ae-0253736e4874</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>--Select--AglipayanBorn AgainEvangelicalIglesia ni KristoIslamJehova's WitnessOthersProtestantRoman CatholicSeventh-day Adventist</value>
      <webElementGuid>6ee3456e-91e6-4f34-8be1-245637d55e32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cboReligion&quot;)</value>
      <webElementGuid>76ac4060-e8dd-453c-820b-fbaf07a3e191</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='cboReligion']</value>
      <webElementGuid>87ea3ff6-b0dd-4144-92cb-4e1e18039655</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='0']/div/div/div[2]/div/div/div[21]/div/div/select</value>
      <webElementGuid>b7e672f6-dc2e-4391-b3ef-c806b9933dd6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[21]/div/div/select</value>
      <webElementGuid>3e1bb8de-63e5-4c82-bc35-4ca69d34ff61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'cboReligion' and (text() = concat(&quot;--Select--AglipayanBorn AgainEvangelicalIglesia ni KristoIslamJehova&quot; , &quot;'&quot; , &quot;s WitnessOthersProtestantRoman CatholicSeventh-day Adventist&quot;) or . = concat(&quot;--Select--AglipayanBorn AgainEvangelicalIglesia ni KristoIslamJehova&quot; , &quot;'&quot; , &quot;s WitnessOthersProtestantRoman CatholicSeventh-day Adventist&quot;))]</value>
      <webElementGuid>56fd915c-c047-4687-a355-995137ec2eae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
