<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_--Select--Accommodation and Food Ser_e45bf9</name>
   <tag></tag>
   <elementGuidId>321b4282-ce2b-4b2b-9061-484cb8f989cd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cboBusinessType</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='cboBusinessType']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>5311dfa1-f6b7-40b3-a35d-b7f17650cdd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cboBusinessType</value>
      <webElementGuid>c87815d4-6633-4ff7-819a-9866bd90ea85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control gb-border-fcs select2 font-11</value>
      <webElementGuid>8e55c0a0-83fb-445c-b415-1582021d3dff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>select2</value>
      <webElementGuid>fd5efa75-9210-49a5-bbcc-8bac7f78761b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>--Select--Accommodation and Food ServicesAdministrative and Support Service ActivitiesAgriculture, Forestry and FishingArts, Entertainment and RecreationBanking and Financial ActivitiesCellphone, Computer and ElectronicsCompulsory Social SecurityConstructionEducationElectricity, Gas, Stream and Aircon supplyFishingFood ServicesHealth and Social Work ActivitiesHousehold Use/ Consumption ServicesInsuranceManufacturingMining and QuarryingOther Community, Social, and Personal Servicesother service activitiesProfessional, Scientific and Technical ActivitiesPublic Administration and DefenseReal Estate ActivitiesRepair of Motor Vehicles, MotorcyclesTransportation, Storage and CommunicationWater Supply, Sewerage, Waste management and Remediation SystemWholesale and Retail Trade</value>
      <webElementGuid>06fd2efc-2a04-4c71-a877-f2d23c6953f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cboBusinessType&quot;)</value>
      <webElementGuid>be0094f6-dd41-4f7d-a0ff-0f44020431c9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='cboBusinessType']</value>
      <webElementGuid>025b3aaa-82dd-4028-a317-e7df595bb88c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='0']/div/div/div[2]/div[2]/div[3]/div/div/select</value>
      <webElementGuid>2061d908-0078-4fa6-b79e-d1bac70bee7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/select</value>
      <webElementGuid>9f67ec66-4370-4d89-ba8a-8eb6b65ae4e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'cboBusinessType' and (text() = '--Select--Accommodation and Food ServicesAdministrative and Support Service ActivitiesAgriculture, Forestry and FishingArts, Entertainment and RecreationBanking and Financial ActivitiesCellphone, Computer and ElectronicsCompulsory Social SecurityConstructionEducationElectricity, Gas, Stream and Aircon supplyFishingFood ServicesHealth and Social Work ActivitiesHousehold Use/ Consumption ServicesInsuranceManufacturingMining and QuarryingOther Community, Social, and Personal Servicesother service activitiesProfessional, Scientific and Technical ActivitiesPublic Administration and DefenseReal Estate ActivitiesRepair of Motor Vehicles, MotorcyclesTransportation, Storage and CommunicationWater Supply, Sewerage, Waste management and Remediation SystemWholesale and Retail Trade' or . = '--Select--Accommodation and Food ServicesAdministrative and Support Service ActivitiesAgriculture, Forestry and FishingArts, Entertainment and RecreationBanking and Financial ActivitiesCellphone, Computer and ElectronicsCompulsory Social SecurityConstructionEducationElectricity, Gas, Stream and Aircon supplyFishingFood ServicesHealth and Social Work ActivitiesHousehold Use/ Consumption ServicesInsuranceManufacturingMining and QuarryingOther Community, Social, and Personal Servicesother service activitiesProfessional, Scientific and Technical ActivitiesPublic Administration and DefenseReal Estate ActivitiesRepair of Motor Vehicles, MotorcyclesTransportation, Storage and CommunicationWater Supply, Sewerage, Waste management and Remediation SystemWholesale and Retail Trade')]</value>
      <webElementGuid>f581a820-48d3-4de3-8aca-549df0a96406</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
