<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_--Select--AnnulledLive-inMarriedSepa_54a068</name>
   <tag></tag>
   <elementGuidId>23b84411-66c5-495a-b092-3726c7ecdc13</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cboCivilStatus</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='cboCivilStatus']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>90af8c64-97fb-405c-b98d-3efa0814c485</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cboCivilStatus</value>
      <webElementGuid>1bcece2b-57c3-4858-99e9-2b3ccc382ded</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>CivilStatusType();</value>
      <webElementGuid>05442545-a5d1-4d78-b696-a6eb6e992db1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control gb-border-fcs select2 font-11</value>
      <webElementGuid>b8fc8272-4f3b-4a87-b55d-a308d07c2ab7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>select2</value>
      <webElementGuid>b2005040-c922-4e08-be59-886e93f01638</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>--Select--AnnulledLive-inMarriedSeparatedSingleWidowed</value>
      <webElementGuid>25aa4f30-1d43-4520-acc6-f779b157bb04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cboCivilStatus&quot;)</value>
      <webElementGuid>a2bf463a-faed-4a3a-8005-c7f1bfe472f7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='cboCivilStatus']</value>
      <webElementGuid>815188bf-be58-4843-a830-d8cd90a2623a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='0']/div/div/div[2]/div/div/div[12]/div/div/select</value>
      <webElementGuid>96dd8564-37c5-4fee-8533-b151c4d92412</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[12]/div/div/select</value>
      <webElementGuid>b96eb7a3-30bb-4972-ab3c-f7d288cca9ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'cboCivilStatus' and (text() = '--Select--AnnulledLive-inMarriedSeparatedSingleWidowed' or . = '--Select--AnnulledLive-inMarriedSeparatedSingleWidowed')]</value>
      <webElementGuid>53cde422-cb73-4073-81ca-c50dee121aaf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
