<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_--      Select      --0 - Hindi13 - Oo</name>
   <tag></tag>
   <elementGuidId>0c1b7db6-1e8d-419e-a91c-14a54cc941c0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cboeighthQAnswer</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='cboeighthQAnswer']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>d89ffa76-a333-4945-bc78-197bda387d9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>validatelenght required gb-border-fcs form-control Ans</value>
      <webElementGuid>1b7d1a33-9290-4a5b-ab47-b98224027b5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cboeighthQAnswer</value>
      <webElementGuid>b9781db5-1e73-4094-8598-1e6db5d3981f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>--      Select      --[0] - Hindi[13] - Oo</value>
      <webElementGuid>ba2379ba-a793-48bf-9a98-e2a113cc1705</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cboeighthQAnswer&quot;)</value>
      <webElementGuid>f4a8ee5e-a91b-4b21-82d4-b4ffd6465756</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='cboeighthQAnswer']</value>
      <webElementGuid>1bc39736-83e0-4158-86e0-11aa848b8711</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='tblPPIBodyEighth']/tr/td[2]/select</value>
      <webElementGuid>1b6d69b4-cf51-42ab-948a-62df939b8813</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tbody[8]/tr/td[2]/select</value>
      <webElementGuid>bf2ffb54-d01b-4960-bbf3-52b853da67b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'cboeighthQAnswer' and (text() = '--      Select      --[0] - Hindi[13] - Oo' or . = '--      Select      --[0] - Hindi[13] - Oo')]</value>
      <webElementGuid>23e2e361-2a09-4f01-9914-dc9e0d08c7f4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
