<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Date Encoded_mdtxtDateEncoded</name>
   <tag></tag>
   <elementGuidId>bf5453ea-1c69-4ac2-90be-b2beb2a0da16</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='mdtxtDateEncoded']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mdtxtDateEncoded</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>18f75a91-8e71-4513-a7f9-be6fe1f8a4b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>230b09f6-ff56-41df-92d5-accc1d310b46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>date</value>
      <webElementGuid>57356ac0-77cd-4871-94ba-0485e26dd221</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>2999-01-01</value>
      <webElementGuid>d7622159-08a5-402e-967b-130791622ab5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control text-uppercase
											 gb-border-bottom-fcs keep-data keep-disabled</value>
      <webElementGuid>d29609b1-a242-462e-b46f-071e6e03df09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mdtxtDateEncoded</value>
      <webElementGuid>ddd1a2d8-5d4c-4da5-8b88-a9dc49c319f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mdtxtDateEncoded&quot;)</value>
      <webElementGuid>00ca9100-b04c-44cf-8a8e-6ffe2d3b626b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mdtxtDateEncoded']</value>
      <webElementGuid>5a59f14d-0af8-4df4-9d20-7e078cbf903e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='LoancreationModal']/div/div/div[3]/div/div[3]/div[2]/div[2]/div/input</value>
      <webElementGuid>b521d036-5a19-424d-a026-5b78ec8c0f3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div[2]/div/input</value>
      <webElementGuid>40b7a9bc-0eba-4bda-8b68-ca07cb3da813</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'date' and @id = 'mdtxtDateEncoded']</value>
      <webElementGuid>3ecb6032-c737-4f2a-b590-1e2b0995ef70</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
