<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Birthday_mdtxtbirthday</name>
   <tag></tag>
   <elementGuidId>bbbc6362-125a-4713-9525-b09c75f7659c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='mdtxtbirthday']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mdtxtbirthday</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3ec16e41-0e90-4aa1-9693-e08aaa508eb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>1501818f-8141-430d-baff-9182282d7afb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>date</value>
      <webElementGuid>d2d5c62a-10fb-42dd-8ccb-2adefe6ba116</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>2999-01-01</value>
      <webElementGuid>9ebe507d-6801-4500-aff2-ccda84fcc9cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mdtxtbirthday</value>
      <webElementGuid>b8a7fc0c-b044-4197-93a3-2cb042b50365</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control gb-border-bottom-fcs keep-disabled keep-data</value>
      <webElementGuid>adfb3b5a-f6a4-4931-8d5c-b36fdcf188f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-provide</name>
      <type>Main</type>
      <value>datepicker</value>
      <webElementGuid>e172df3f-7833-489a-b04d-2cddd0f2f7b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-date-autoclose</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>3d415db9-b194-4a7f-ad87-0792f3414ffa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-date-container</name>
      <type>Main</type>
      <value>#datepicker4</value>
      <webElementGuid>24f786b0-4d5e-4f65-b62c-5cfaa70c53f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mdtxtbirthday&quot;)</value>
      <webElementGuid>2108e32b-1416-4c05-a3ac-c3e771f9354e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mdtxtbirthday']</value>
      <webElementGuid>df44fabc-1e23-4e2e-95c4-38e0b6234e7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='datepicker4']/input)[2]</value>
      <webElementGuid>812f67d2-33de-43d1-ae5c-2c71c36f69e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[3]/div[2]/div/div/input</value>
      <webElementGuid>d543e91a-805a-4393-8912-6cc89b5bbc61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'date' and @id = 'mdtxtbirthday']</value>
      <webElementGuid>2ef0744c-3991-486b-8ec2-2550486000a2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
