<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Area Name_mdtxtareaName</name>
   <tag></tag>
   <elementGuidId>2a2d9262-3e1d-40e5-8cbf-7cfd619c4fa6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='mdtxtareaName']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mdtxtareaName</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>52b7b81e-01d7-4f9e-b514-40e28afd24d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>37d7fce0-2d29-492c-974e-84fad89fd9c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>50bb5003-ca7d-4062-9131-9ed050e5330e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control text-capitalize keep-data keep-disabled gb-border-bottom-fcs</value>
      <webElementGuid>84c37665-d4c2-4f7b-9728-6f55de5df24f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mdtxtareaName</value>
      <webElementGuid>6c15ab85-1e23-40f3-b56d-88f6f376070a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mdtxtareaName&quot;)</value>
      <webElementGuid>0b1f9180-e45a-42e9-863b-c6026696b191</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mdtxtareaName']</value>
      <webElementGuid>2de832c3-f3a3-45eb-bb07-a7b6316dd78f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='LoancreationModal']/div/div/div[3]/div/div[2]/div/div[2]/div/input</value>
      <webElementGuid>3a594d90-88f0-4be9-9aa9-c2d0f9cdb912</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/div/div[2]/div/input</value>
      <webElementGuid>6c628cb4-a43d-46ce-ba39-058b7136d532</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'mdtxtareaName']</value>
      <webElementGuid>1dfb3673-4a03-4951-8037-97761dbe1886</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
