<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Name_mdtxtfullname</name>
   <tag></tag>
   <elementGuidId>9f46e7d8-e3c2-424d-bc60-22b55b0c85be</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='mdtxtfullname']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mdtxtfullname</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a0afa574-1b5b-429d-8a9c-0fd09ba130e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>0ee59579-f033-4549-8f26-96834963c18b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e2ea9da5-4217-4d50-b4fb-8db717323a97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control gb-border-bottom-fcs keep-disabled keep-data</value>
      <webElementGuid>a0f2ef0e-7e3f-49fa-9e97-82380a8a2f59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mdtxtfullname</value>
      <webElementGuid>f1cec510-9460-48a6-b302-106cc30288c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mdtxtfullname&quot;)</value>
      <webElementGuid>b3ee26a4-e0fc-4768-9d1b-01e2ab54fe9b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mdtxtfullname']</value>
      <webElementGuid>b5625cb4-ab81-436c-89d0-70c14a2c61c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='LoancreationModal']/div/div/div[3]/div/div/div[2]/div[2]/div/input</value>
      <webElementGuid>6cf53d5c-0caa-4b2d-81ca-b445946ff39f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[2]/div[2]/div/input</value>
      <webElementGuid>21f3a61d-a39b-40d9-8a76-70680dff41dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'mdtxtfullname']</value>
      <webElementGuid>b2b3c340-f491-4230-878c-93b062fbf7c6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
