<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Center Name_mdtxtcenterName</name>
   <tag></tag>
   <elementGuidId>f2c22ad2-ddbf-4a97-89db-580447dc8f35</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='mdtxtcenterName']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mdtxtcenterName</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5e4e086c-f74a-4b0b-ab98-f9b36590d23d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>909b6d8f-e4e0-4f65-9bf0-622021f8fde5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6aec9d9f-afc8-4067-8cb6-8942ad3033de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control text-capitalize gb-border-bottom-fcs keep-data keep-disabled</value>
      <webElementGuid>d3e3cc60-6514-4ad6-9e5f-b78b930a0cda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mdtxtcenterName</value>
      <webElementGuid>a1ee6234-02bc-490d-aef9-5285da733329</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mdtxtcenterName&quot;)</value>
      <webElementGuid>64031b74-4cf1-4dd4-9e70-c3276681b102</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mdtxtcenterName']</value>
      <webElementGuid>e0833abf-019c-4c89-9efb-0dea74daa263</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='LoancreationModal']/div/div/div[3]/div/div[2]/div[3]/div[2]/div/input</value>
      <webElementGuid>5584f403-5318-462e-966b-abe268c83d07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/div[3]/div[2]/div/input</value>
      <webElementGuid>a3e919eb-ef34-4606-a83e-68e2ea8007d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'mdtxtcenterName']</value>
      <webElementGuid>cba9ad6d-ec1f-493e-9032-da60c35426af</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
