<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Save as draft</name>
   <tag></tag>
   <elementGuidId>e6877ddd-347f-4aee-934c-6bec5d65eb68</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btnDraft']/i/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>b075101b-db71-4da0-99eb-f54294c645e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Save as draft</value>
      <webElementGuid>6313c2c0-8e78-40d4-a347-98fe41c850f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnDraft&quot;)/i[@class=&quot;uil-download-alt&quot;]/span[1]</value>
      <webElementGuid>2695e9ec-ef22-469a-b859-cac023d76f11</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='btnDraft']/i/span</value>
      <webElementGuid>31bd3a61-66ab-4043-928c-df8afa75cd0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//i/span</value>
      <webElementGuid>123dda01-0b88-4956-a0ec-22d7dbde85fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = ' Save as draft' or . = ' Save as draft')]</value>
      <webElementGuid>6ce0caf4-7a55-4e09-b571-38065e6dee34</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
