<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>strong_Loan Creation</name>
   <tag></tag>
   <elementGuidId>313c03c3-bb5e-442c-b54f-ae9b325008c8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//h4[@id='fullWidthModalLabel']/strong</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>strong</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>strong</value>
      <webElementGuid>b774c4c7-841a-403d-b9f1-4fbd661218cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Loan Creation</value>
      <webElementGuid>4cbd23ce-71ef-4ffe-a146-1b22523609f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fullWidthModalLabel&quot;)/strong[1]</value>
      <webElementGuid>24d29198-41a9-4027-9fb0-b1ff7b761698</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//h4[@id='fullWidthModalLabel']/strong</value>
      <webElementGuid>59fa071a-fafe-47a7-8868-e85bb2a6e719</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//strong</value>
      <webElementGuid>995b09c7-f343-4b8d-bfed-ff41ed60e3a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//strong[(text() = ' Loan Creation' or . = ' Loan Creation')]</value>
      <webElementGuid>5923b0af-0ee6-47d6-98a8-118ea1e90686</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
