<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>itoggletxtPassword</name>
   <tag></tag>
   <elementGuidId>8298fcc0-d213-4e9d-b555-be6d0763aa28</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//i[@id='toggletxtPassword']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#toggletxtPassword</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>27d6142a-236e-4b75-9ce9-228acff93b0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mdi mdi-eye-off-outline</value>
      <webElementGuid>47e8e311-0d16-4ce0-992f-aedf5a6b8230</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>toggletxtPassword</value>
      <webElementGuid>57b774c6-b7e3-40dc-9b37-9d75e9aa0889</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>showPass()</value>
      <webElementGuid>a5397dbe-9d5a-49a8-b5bc-2f98ceba61f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;toggletxtPassword&quot;)</value>
      <webElementGuid>a731cc33-a660-465c-a1d5-b98ac83dfd4f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//i[@id='toggletxtPassword']</value>
      <webElementGuid>459f564a-f43a-4838-a812-d48569048cef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='body']/div/div/div/div[3]/form/div[2]/div/span/i</value>
      <webElementGuid>32a5dd51-2284-414b-8872-66b64208307f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//i</value>
      <webElementGuid>dad2409e-1599-4903-865e-4b9bd863a68d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//i[@id = 'toggletxtPassword']</value>
      <webElementGuid>f475e50a-90be-4fa9-a969-7305a8aafb57</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
