<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_LoanDisbursement</name>
   <tag></tag>
   <elementGuidId>2058b1d1-43f1-4618-b5d6-5bae7d84c102</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#LoanDisbursement</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='LoanDisbursement']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3feb2231-5d41-4fbd-8566-35f223752a19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gb-hover-side confirmation-link</value>
      <webElementGuid>30d7e31d-ce38-4a7c-aa5e-019147d8b8ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>LoanDisbursement</value>
      <webElementGuid>8d61e094-9df1-4d44-9626-98075caa26b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>LoanDisbursement</value>
      <webElementGuid>92dfd72e-7828-4c1b-914e-64f9b0b70221</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>return loadIframe('ifrm1', this.href);</value>
      <webElementGuid>89d9ff29-a5a7-4358-91e1-ef70571cebc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Loan
									Disbursement</value>
      <webElementGuid>be7eb126-4587-4d5a-b3fd-0f82eac7e757</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;LoanDisbursement&quot;)</value>
      <webElementGuid>5d18dce2-9282-4300-91e2-3c64c7c36ad0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='LoanDisbursement']</value>
      <webElementGuid>238e1d24-3f3c-45da-94a1-4ca5f9cf133e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sidebarLoan']/ul/li[3]/a</value>
      <webElementGuid>9b09106f-0ea1-49a3-ac4c-ae03747d0c4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Loan
									Disbursement')]</value>
      <webElementGuid>ec5fbe10-e7e2-4a48-a03e-2b50023b735a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'LoanDisbursement')]</value>
      <webElementGuid>97c1eda6-dedc-4f19-921e-c6b9c48cfed9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/div/ul/li[3]/a</value>
      <webElementGuid>c7798846-4f8d-445b-a3f4-6c4c0e342d32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'LoanDisbursement' and @id = 'LoanDisbursement' and (text() = 'Loan
									Disbursement' or . = 'Loan
									Disbursement')]</value>
      <webElementGuid>5fb80a57-6d23-4893-b9a7-bd7216f30841</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
