<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_NO</name>
   <tag></tag>
   <elementGuidId>0b7b6366-bdbd-4c0c-b9ef-9cb42f7a5598</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.col-6 > button.btn.btn-danger</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@id=''])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>bad8f000-f5f5-4254-8784-7aeb22eeebf3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ff048c16-27da-4598-aa2e-8ffa3e3035f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-danger</value>
      <webElementGuid>ceb8c2ae-19c4-4b8b-99db-2b5a80d3b695</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>closeReleaseLoan()</value>
      <webElementGuid>5d72f4cc-0481-40ae-ace1-ae133451b1a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>NO</value>
      <webElementGuid>d03fb404-9415-4ec4-a59a-e03077f33355</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Approvemodal&quot;)/div[@class=&quot;modal-dialog modal-dialog-centered&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-body&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-6&quot;]/button[@class=&quot;btn btn-danger&quot;]</value>
      <webElementGuid>7fa54744-7eef-46ea-a717-a74a95876631</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@id=''])[2]</value>
      <webElementGuid>d8fc9ebf-5706-485f-92c2-6cfd7b78662a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Approvemodal']/div/div/div[2]/div[2]/div[2]/button</value>
      <webElementGuid>ca97c37c-1dd9-46f2-a710-3b0c4213bc29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button</value>
      <webElementGuid>c1686320-30a1-4667-a94f-1ca0e227905e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'NO' or . = 'NO')]</value>
      <webElementGuid>501c785b-c193-457b-8097-36f6c0fa9b0f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
