<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_PostTransaction</name>
   <tag></tag>
   <elementGuidId>b3cb1c6d-ae40-404b-8844-ad9c0a7eb563</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnPostTransaction</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btnPostTransaction']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Post Transaction&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8547f50d-f52d-42e7-bc42-14231272f2e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3ec24d41-957e-4a70-baa1-a4a163250e28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-success</value>
      <webElementGuid>159d2690-909c-4ed0-a6f7-de4f45d8c448</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnPostTransaction</value>
      <webElementGuid>021b81b9-cd6b-4407-b3b6-95afedc47711</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Post
													Transaction</value>
      <webElementGuid>1035bfef-75e8-4e32-80fb-d27c75bed437</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnPostTransaction&quot;)</value>
      <webElementGuid>ecf449db-779e-4d87-b27a-fb64194edf4f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btnPostTransaction']</value>
      <webElementGuid>353fbb3e-50f8-4570-be74-d6423e18fb9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='body']/div/div[4]/div/div/div/div[2]/div[5]/div[4]/div/div/div/button</value>
      <webElementGuid>555a1b1b-c885-491e-a7be-b3f1c6ba96e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Validation:'])[1]/following::button[1]</value>
      <webElementGuid>426d0ffe-1c3a-408d-ae96-f3ea2f57f75c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='face'])[1]/preceding::button[1]</value>
      <webElementGuid>1d6938ea-9bca-4282-af27-e8ee10ededaf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/button</value>
      <webElementGuid>8fa37920-d365-49f2-a8e9-984d7236b5b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'btnPostTransaction' and (text() = 'Post
													Transaction' or . = 'Post
													Transaction')]</value>
      <webElementGuid>cfb31246-7e99-41d8-9cfb-a73a5f23f2e6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
