<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Cash on Hand_ri-add-circle-fill</name>
   <tag></tag>
   <elementGuidId>c7c7eab2-6677-4123-81ba-eb768d78973e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.ri-add-circle-fill</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='add-client-button']/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>50d8e828-a69d-4ff1-ad21-dacabf64b6fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ri-add-circle-fill</value>
      <webElementGuid>a010963a-0f9b-4c72-848c-e5f0ee1b2e56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;add-client-button&quot;)/i[@class=&quot;ri-add-circle-fill&quot;]</value>
      <webElementGuid>ad02e282-c88a-4ffa-ad5f-9767bc20bcdd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='add-client-button']/i</value>
      <webElementGuid>51aa4e31-1ba9-4dc0-be84-360d978688dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cash on Hand'])[1]/following::i[1]</value>
      <webElementGuid>4b0e41ac-4916-41f2-ad1e-0a8ae42f91a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Capital-Build Up'])[1]/following::i[1]</value>
      <webElementGuid>58c272bf-5d59-4c7a-8eb9-6527dfcafa8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add Client'])[1]/preceding::i[1]</value>
      <webElementGuid>68d17321-aae1-4df7-bc32-fca841254477</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/button/i</value>
      <webElementGuid>f0007f09-82f1-46b2-8748-fc515f678a99</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
