<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_LoanCredit_c1</name>
   <tag></tag>
   <elementGuidId>6b5c5ae4-3b3e-443f-8a66-99379613adfc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//tr[2]/td[5]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=row[name=&quot;4001-0000-00001967 SIKAP 1 0.00 0.00&quot;i] >> internal:attr=[placeholder=&quot;0.00&quot;i] >> nth=1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>21143654-983b-4bce-a5bc-a5b875ab061f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>31c8ec8a-623e-4953-b82e-8555c55c6348</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control gb-border-fcs  credit</value>
      <webElementGuid>28d079fc-9469-4fc8-ae9a-42a8896cf105</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0.00</value>
      <webElementGuid>ba90d233-f0d2-426f-ae18-63d5e0fc4391</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>4001-0000-00001967:3:992:10000324</value>
      <webElementGuid>a114e034-88e5-44bd-bc10-3f9fa5e900bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>0.00</value>
      <webElementGuid>aa0b0d68-8d5b-4509-ac27-900eb42f2834</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1/</value>
      <webElementGuid>65420e7a-49d9-4ef7-b289-899a0f5c492b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tblPaymentAdjustmentTbody1&quot;)/tr[@class=&quot;even&quot;]/td[@class=&quot;text-center&quot;]/input[@id=&quot;4001-0000-00001967:3:992:10000324&quot;]</value>
      <webElementGuid>5ba09020-2645-491b-9881-002c122eb9fc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='4001-0000-00001967:3:992:10000324'])[2]</value>
      <webElementGuid>e7eb9f38-6120-4085-9676-65a031971b68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='tblPaymentAdjustmentTbody1']/tr[2]/td[5]/input</value>
      <webElementGuid>7e58202a-73de-4793-a2cf-e378faa584f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[5]/input</value>
      <webElementGuid>2f67cd50-98c6-4f91-9c94-4caa1f166c21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = '4001-0000-00001967:3:992:10000324' and @placeholder = '0.00']</value>
      <webElementGuid>2aa31742-8a45-4718-96ac-5d96673a9c66</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
