<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputcbu_debit_c1</name>
   <tag></tag>
   <elementGuidId>4f74d91b-1520-4353-b6bd-6b22948e8a07</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//tr[3]/td[4]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=row[name=&quot;1012-0000-00003701 Capital-Build Up 0.00 0.00&quot;i] >> internal:attr=[placeholder=&quot;0.00&quot;i] >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>32ad6a10-64ac-482c-98d0-b2019f9ae98c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a4c47581-0b4f-40bf-8659-b7bcb8698a96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control  gb-border-fcs  debit</value>
      <webElementGuid>0b737097-7e85-41f9-89bc-c3457fefe351</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0.00</value>
      <webElementGuid>cf47c95f-be1a-4bd7-b061-8384a4315d2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>1012-0000-00003701:0:992:10000324</value>
      <webElementGuid>d9bb0428-9b32-458f-bb7e-644317dc483b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>0.00</value>
      <webElementGuid>90a04d8c-1429-41fe-8d0c-bd35f6d38247</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1/</value>
      <webElementGuid>30691b64-5cc1-4a58-8964-4c04c8eeca6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tblPaymentAdjustmentTbody1&quot;)/tr[@class=&quot;odd&quot;]/td[@class=&quot;text-center&quot;]/input[@id=&quot;1012-0000-00003701:0:992:10000324&quot;]</value>
      <webElementGuid>d8e17f13-e2ec-44cc-b5a4-bc53b081dedf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='1012-0000-00003701:0:992:10000324']</value>
      <webElementGuid>feab3420-5c3a-4020-86e3-8838a71b47e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='tblPaymentAdjustmentTbody1']/tr[3]/td[4]/input</value>
      <webElementGuid>3c4057b7-9d35-4cc3-baed-c4cf417105dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[4]/input</value>
      <webElementGuid>fc20cf10-440e-47b2-abbf-7f05fc399055</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = '1012-0000-00003701:0:992:10000324' and @placeholder = '0.00']</value>
      <webElementGuid>c98ed9cf-1b37-43ac-a708-59a8319fad20</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
