<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_MBA_Credit_c1</name>
   <tag></tag>
   <elementGuidId>574ed19c-0b44-43f0-b295-3e9e277aac53</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td[5]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=row[name=&quot;2043-0000-00002308 MBA PREMIUM 0.00 0.00&quot;i] >> internal:attr=[placeholder=&quot;0.00&quot;i] >> nth=1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>144a6ebb-8bb6-4fc8-bbee-9160abe579c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5efed421-19ed-41ba-82fc-a85c0fcccf8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control gb-border-fcs  credit</value>
      <webElementGuid>39c13c8e-ce79-48b8-9540-d6d161b0d50b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0.00</value>
      <webElementGuid>a86006a4-42af-432b-a2cb-1060de639065</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>2043-0000-00002308:1:992:10000324</value>
      <webElementGuid>f857862f-bb8e-4343-bd82-01f1581ffb2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>0.00</value>
      <webElementGuid>a4efd606-cd1b-4041-9a18-567b3fd86d6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1/</value>
      <webElementGuid>5f77c527-b58a-4c9f-a305-9caee91913ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tblPaymentAdjustmentTbody1&quot;)/tr[@class=&quot;odd&quot;]/td[@class=&quot;text-center&quot;]/input[@id=&quot;2043-0000-00002308:1:992:10000324&quot;]</value>
      <webElementGuid>cbafd485-1f4c-4fae-bb6c-408a119694b6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='2043-0000-00002308:1:992:10000324'])[2]</value>
      <webElementGuid>66afc191-a9e9-44b9-84db-dfaf07a2c415</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='tblPaymentAdjustmentTbody1']/tr/td[5]/input</value>
      <webElementGuid>9f70f1b1-8c11-4e5d-8bfe-6401350a4cdb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[5]/input</value>
      <webElementGuid>e4ece795-ac76-4802-8428-1ebcaab992e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = '2043-0000-00002308:1:992:10000324' and @placeholder = '0.00']</value>
      <webElementGuid>6a347f6f-a42a-44be-bbfc-1f66f2177af6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
