<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Capital-Build Up_txtCashonHand1</name>
   <tag></tag>
   <elementGuidId>cd0488ed-388d-4bbe-8015-2212d2887b4c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtCashonHand1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtCashonHand1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#txtCashonHand1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7c0a2934-f40c-4904-be7b-93bc35f837ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>ffeaaeb4-a567-4897-a822-95abf9614113</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input  gb-border-fcs</value>
      <webElementGuid>409fe26e-8fd6-446f-aae6-6b8508568517</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtCashonHand1</value>
      <webElementGuid>87244dfc-1eca-4c31-b81b-ae7b1d1396fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtCashonHand1&quot;)</value>
      <webElementGuid>f6e8b93f-ab96-4ccf-aa2e-60b9157d53d3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtCashonHand1']</value>
      <webElementGuid>ea0a04b5-c385-4620-a747-525962425a8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='tblPaymentAdjustmentTbody1']/tr[4]/td/input</value>
      <webElementGuid>f49f22ae-1591-404f-b1e3-247fea090afd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td/input</value>
      <webElementGuid>4b9a81a1-e31e-403a-8fa6-ef8a20d8c8a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'txtCashonHand1']</value>
      <webElementGuid>e63737ba-bfc5-4f8c-98e7-3a3e97c99f44</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
