<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_LoanCredit_c2</name>
   <tag></tag>
   <elementGuidId>e336cff1-fb8c-47af-943d-9dc2bd9758b6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[4]/div/div[3]/div/div/div[2]/table/tbody/tr[2]/td[5]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=row[name=&quot;4001-0000-00001967 SIKAP 1 0.00 0.00&quot;i] >> internal:attr=[placeholder=&quot;0.00&quot;i] >> nth=1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3b32c07a-efa8-459f-83c1-909a1d75ea16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6b6dcbe5-a19b-47c5-909e-ec4b4f0cd5ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control gb-border-fcs  credit</value>
      <webElementGuid>5f54f83d-63d5-41c0-8bab-1de5f538b93e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0.00</value>
      <webElementGuid>c68974c8-ef4b-447d-8d1e-bc6b164aae37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>4001-0000-00001967:3:992:10000324</value>
      <webElementGuid>872ece22-d7c6-4af6-b0f1-69e95eeeda91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>0.00</value>
      <webElementGuid>cdd90321-ab46-4b54-8103-429ee5f3242d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1/</value>
      <webElementGuid>0a796a9e-8622-4527-b7c7-50c6a28065d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tblPaymentAdjustmentTbody1&quot;)/tr[@class=&quot;even&quot;]/td[@class=&quot;text-center&quot;]/input[@id=&quot;4001-0000-00001967:3:992:10000324&quot;]</value>
      <webElementGuid>0c0107ef-cf1a-467d-8c82-a7873f842c28</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='4001-0000-00001967:3:992:10000324'])[2]</value>
      <webElementGuid>16ce1497-e3b9-4885-ad72-2f15edaf760d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='tblPaymentAdjustmentTbody1']/tr[2]/td[5]/input</value>
      <webElementGuid>688ddc7d-af20-4594-9c6e-18731a160c67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[5]/input</value>
      <webElementGuid>1078fbe8-7b47-4e08-95c6-365d320bd2d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = '4001-0000-00001967:3:992:10000324' and @placeholder = '0.00']</value>
      <webElementGuid>8ec42118-5f9b-47b3-ba33-e23bed2bb1ad</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
