<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputCashOnHand_debit_c2</name>
   <tag></tag>
   <elementGuidId>9a234cb9-07f7-429b-a133-1ef133d855d7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[4]/div/div[3]/div/div/div[2]/table/tbody/tr[3]/td[4]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=row[name=&quot;1-01-01-01-01 Cash on Hand 0.00 0.00&quot;i] >> internal:attr=[placeholder=&quot;0.00&quot;i] >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>30686139-a37d-49b1-a200-3f13408d79ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>85dbd4e7-452b-497d-a8a0-0ec670a40e89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>disabled</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>839f178e-68f3-4233-9ba3-01af86b6ed5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control  gb-border-fcs tellerDebit debit</value>
      <webElementGuid>18b61351-6c9e-418a-ad6d-fff183fea283</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0.00</value>
      <webElementGuid>cc0f9f59-ea81-49ea-aea3-2ad5447a317f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>5001-0000-00000263:4:992:10000324</value>
      <webElementGuid>3c3ff443-f669-40b8-a8d9-a4fdad6fb331</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>0.00</value>
      <webElementGuid>885e06b3-cdb0-44ad-b0c4-d32f30f2220f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1/</value>
      <webElementGuid>c6675700-ba35-4b33-826d-d3ecc057018d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tblPaymentAdjustmentTbody1&quot;)/tr[@class=&quot;even&quot;]/td[@class=&quot;text-center&quot;]/input[@id=&quot;5001-0000-00000263:4:992:10000324&quot;]</value>
      <webElementGuid>3a0f5115-403c-4b55-8531-9e3ec3a748b8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='5001-0000-00000263:4:992:10000324']</value>
      <webElementGuid>a0a56d69-b3b8-48e1-9c11-9fd20b4394dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='tblPaymentAdjustmentTbody1']/tr[4]/td[4]/input</value>
      <webElementGuid>74597127-e7fe-45ac-b97b-5b432d868652</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[4]/input</value>
      <webElementGuid>37524557-a4bd-4bd5-a091-a647ebfdd788</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = '5001-0000-00000263:4:992:10000324' and @placeholder = '0.00']</value>
      <webElementGuid>17181a9c-6b6c-4470-b9dc-ecaab85d64bc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
