<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_New client has been approved CID-10000213  ACC-1012-0000-00001531</name>
   <tag></tag>
   <elementGuidId>46e4b80e-4b74-48ff-917b-ee51c92286fa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='swal2-content']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#swal2-content</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a81e7fd7-80f2-45c6-9d44-e5d0227a5d26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>swal2-content</value>
      <webElementGuid>4d6a5db8-746e-4445-a9fb-cb296fcf439e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>New client has been approved CID-10000213 / ACC-1012-0000-00001531</value>
      <webElementGuid>3cc4f732-d10a-4acf-8e6c-aedef549ccdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;swal2-content&quot;)</value>
      <webElementGuid>8c003f14-7b9e-44d0-973b-f1d46f39ab7b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='swal2-content']</value>
      <webElementGuid>4d3249fb-8e55-4127-b632-e3d223f3d27c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div[2]/div</value>
      <webElementGuid>396d7de4-9031-4519-95ad-ae9cd5270034</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'swal2-content' and (text() = 'New client has been approved CID-10000213 / ACC-1012-0000-00001531' or . = 'New client has been approved CID-10000213 / ACC-1012-0000-00001531')]</value>
      <webElementGuid>7d10c815-c9ad-44df-9c0b-3f16c2a2a5ba</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
