<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Birthday_ri-add-circle-fill</name>
   <tag></tag>
   <elementGuidId>4e98fd6b-332a-46f5-b262-a2d74465c687</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='add-CoBrower-button']/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.ri-add-circle-fill</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>bc4880fb-237b-496e-812e-43a71036cae3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ri-add-circle-fill</value>
      <webElementGuid>fc4c22af-62b5-4f2f-9d7f-cf52630a0924</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;add-CoBrower-button&quot;)/i[@class=&quot;ri-add-circle-fill&quot;]</value>
      <webElementGuid>71bb6f2c-a3ef-4077-8de7-dcb61c78a0ca</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='add-CoBrower-button']/i</value>
      <webElementGuid>4db2b0dd-68d5-4c58-bc06-786e330128e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/button/i</value>
      <webElementGuid>8b1e5069-573e-4fc3-83c4-d042b0742bf7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
