<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_LRF_txtLRF</name>
   <tag></tag>
   <elementGuidId>80ccede9-74d0-4b3f-921c-a44de42f252b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtLRF']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#txtLRF</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1faa73e4-59ff-4f4d-843c-34c7a491d4f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>7519ce3f-1186-4fbb-ac42-546add6ce3e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>772950cc-d23e-4c86-918c-19e65d1daa30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control gb-border-fcs keep-disabled</value>
      <webElementGuid>79fc82c9-5033-4f4e-b3db-35cf90ebde1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtLRF</value>
      <webElementGuid>db6c911a-bc2a-49e1-ae7a-e2bde85a8e3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtLRF&quot;)</value>
      <webElementGuid>1e1bb4fb-4bbb-469a-b9b9-71befe8b6c3b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtLRF']</value>
      <webElementGuid>c220ccc0-3d00-40c7-8bb3-4069e91a4d37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='loaninfo']/div[5]/div[3]/div/div[2]/div/input</value>
      <webElementGuid>797919e6-b98c-4ab1-8e29-adad42126338</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[3]/div/div[2]/div/input</value>
      <webElementGuid>3a5ad923-a3f6-4f9d-9caa-7196ecf47d4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'txtLRF']</value>
      <webElementGuid>7ad6c04b-7749-4058-80f8-b42be578d957</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
