<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Start Date_txtStartDate</name>
   <tag></tag>
   <elementGuidId>3c8b11b3-b7b2-45ef-8b20-c125d70f9ad2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtStartDate']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#txtStartDate</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>16c23be6-df9c-4e49-9070-868fe952e480</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>33066be6-ae12-4fb8-8c92-eab418f904fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0c8720c6-cf0f-42bf-98cf-22f117402402</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtStartDate</value>
      <webElementGuid>97edc4dc-31ae-41f5-8ad6-f154ec62f4c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control gb-border-fcs keep-disabled</value>
      <webElementGuid>7e272ecf-aebf-4060-baee-42351cd940d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-provide</name>
      <type>Main</type>
      <value>datepicker</value>
      <webElementGuid>fc93ebae-c64a-4b18-a8e1-83edc60762ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-date-autoclose</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>35869693-aa21-4c0c-883e-3f303fa39976</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-date-container</name>
      <type>Main</type>
      <value>#datepicker4</value>
      <webElementGuid>113715ea-585f-49b3-877c-c52879b059fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtStartDate&quot;)</value>
      <webElementGuid>0b255115-708b-4c9b-8802-261506c2e64f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtStartDate']</value>
      <webElementGuid>bf6e19c1-6300-4f6c-af3a-085102828b6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='datepicker4']/input)[3]</value>
      <webElementGuid>eb3683dd-feb3-417d-af0c-5979f054716e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/div/div[2]/div/div/input</value>
      <webElementGuid>74dfda27-92f7-47a2-97a9-ca2241d654fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'txtStartDate']</value>
      <webElementGuid>fc2e16c4-5dc8-4144-96b8-7911ef5390c3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
