<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_MaturityDate_txtMaturityDate</name>
   <tag></tag>
   <elementGuidId>9a2aa2b9-1055-48e4-a95e-9745b27251a5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtMaturityDate']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#txtMaturityDate</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b3ea4e1c-214d-467e-b6fb-f647a32c3481</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>4c6cfd99-7a5e-45da-a79e-d96e4e93dbf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>647cc97d-4d41-4237-b8de-011ab8f13845</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtMaturityDate</value>
      <webElementGuid>45def397-27b1-4985-8efe-492bf98fb63f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control gb-border-fcs keep-disabled</value>
      <webElementGuid>bfeb736c-0bf3-4245-9312-7744d441ab9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-provide</name>
      <type>Main</type>
      <value>datepicker</value>
      <webElementGuid>b96123a5-ba98-4fef-b9f3-42269625a0c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-date-autoclose</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>0d2ce4c6-d077-4b9c-8139-d5c065e588f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-date-container</name>
      <type>Main</type>
      <value>#datepicker4</value>
      <webElementGuid>037131d5-2c3c-4354-86df-fc044e2b73dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtMaturityDate&quot;)</value>
      <webElementGuid>31f05ac0-b7ce-4c11-b26c-78533813cb70</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtMaturityDate']</value>
      <webElementGuid>ea4462b7-d121-49a5-a018-b389d48b2b57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='datepicker4']/input)[4]</value>
      <webElementGuid>7bfdd88c-fdf1-443a-9974-ece0a8e3e7f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[2]/div/div[2]/div/div/input</value>
      <webElementGuid>c7e86927-ecc3-47b4-bc33-90689bc0365c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'txtMaturityDate']</value>
      <webElementGuid>5acb2ef3-b816-4576-9101-74ef1ac64972</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
