<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Co-Borrower_cboCardIncClient2</name>
   <tag></tag>
   <elementGuidId>7c9ebed0-dcfe-4995-a9bd-8e35f50fa5cf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cboCardIncClient2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cboCardIncClient2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0a1a93d1-1b82-40f9-a46c-a39835083dfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>7f752f57-1f73-4233-907c-fdec595079e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>935300af-8db5-455e-a44d-df20a9780db4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input  gb-border-fcs</value>
      <webElementGuid>9866f615-657b-4ec9-b17c-722225712fcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cboCardIncClient2</value>
      <webElementGuid>aea86798-4ac1-4498-851a-320f340ebd19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cboCardIncClient2&quot;)</value>
      <webElementGuid>e7750a91-c602-4572-8fd8-dcaaa580dda0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cboCardIncClient2']</value>
      <webElementGuid>f1c0be58-ddc9-4c0b-b95c-1433e7425064</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='row2']/div/div/div/div/input</value>
      <webElementGuid>d811e1b4-fe3b-4d94-9df0-df2f73d0835b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[3]/div/div/div/div/div/input</value>
      <webElementGuid>d5b8b334-7bd0-4e63-a638-94fd1d84ab51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'cboCardIncClient2']</value>
      <webElementGuid>7c522fa8-7df5-4495-8b9b-e8b39d41d310</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
