<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Net Proceed_txtNetProcess</name>
   <tag></tag>
   <elementGuidId>2a13249d-02fa-45f0-ad7e-038ec8400be0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtNetProcess']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#txtNetProcess</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cea02c3a-f718-4207-94bf-6f6b5b83a15a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>4d32d3d9-b463-4d42-b148-42b6b8fa678d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>76979d61-e71a-4c36-b6e6-1d4e0d2702ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control gb-border-fcs keep-disabled</value>
      <webElementGuid>1a1fc01d-d6e6-44a3-9997-f97228e35391</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtNetProcess</value>
      <webElementGuid>62713bdd-52eb-433e-b8d0-7e1cb4fb86bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtNetProcess&quot;)</value>
      <webElementGuid>7681b9fe-4687-4daa-acb5-6a32c96ee1a6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtNetProcess']</value>
      <webElementGuid>39533129-d65d-4357-93e9-0df22933467a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='loaninfo']/div[6]/div[3]/div/div[2]/div/input</value>
      <webElementGuid>2eab8493-e999-41c7-95f9-dad93f3392a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[3]/div/div[2]/div/input</value>
      <webElementGuid>a9e3cf01-91da-4423-b066-681586ce541b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'txtNetProcess']</value>
      <webElementGuid>3cda5139-171d-471f-8b2c-e4d577022b82</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
