<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_-- SelectLoanType</name>
   <tag></tag>
   <elementGuidId>16b58874-f5b0-4cfb-bcf2-12ba73a682ce</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='cboLoanType']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cboLoanType</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>a8fe09f7-d4ad-4f09-9786-e28da3d8c253</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-select computeLRF required gb-border-fcs</value>
      <webElementGuid>fa26f82c-6605-42b9-bab5-5c7ab493c384</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cboLoanType</value>
      <webElementGuid>d3dc9f3b-aca1-4631-b228-594f537eb548</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-- Select --SIKAP 1SIKAP 2MF - SIKAP (GLIP)AGRI LOANHOUSING REPAIRS/IMPROVEMENTSPHILHEALTHSSS PREMIUM LOANMFST- CALAMITY LOANEDUCATIONAL LOAN - ELEMENTARYEDUCATIONAL LOAN - HIGH SCHOOLEDUCATIONAL LOAN - COLLEGEIPL - CAMIAQUICK S.M.E. LOANRPA - REGULAR AGRI LOAN OL-INSURANCE PREMIUM-MBA FAMILY SECURITY PLANMFSL - GADGET LOANMF - SIKAPSIKAP - RESTRUCTUREDOL - RESTRUCTUREDIPL RIMANSI (DAKILA)</value>
      <webElementGuid>30b56134-cae4-43f9-a5f2-35dd8f956fcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cboLoanType&quot;)</value>
      <webElementGuid>c32a9152-c462-4ae3-8a2c-fa473948997f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='cboLoanType']</value>
      <webElementGuid>63af6643-6c18-4a2d-8c75-80adf807d44b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='loaninfo']/div[2]/div/div/div[2]/div/select</value>
      <webElementGuid>bcd2094d-cf02-4c33-8f00-337ba23b4de7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/select</value>
      <webElementGuid>a8fb93cc-fec5-495e-aea0-f6291aa4bbd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'cboLoanType' and (text() = '-- Select --SIKAP 1SIKAP 2MF - SIKAP (GLIP)AGRI LOANHOUSING REPAIRS/IMPROVEMENTSPHILHEALTHSSS PREMIUM LOANMFST- CALAMITY LOANEDUCATIONAL LOAN - ELEMENTARYEDUCATIONAL LOAN - HIGH SCHOOLEDUCATIONAL LOAN - COLLEGEIPL - CAMIAQUICK S.M.E. LOANRPA - REGULAR AGRI LOAN OL-INSURANCE PREMIUM-MBA FAMILY SECURITY PLANMFSL - GADGET LOANMF - SIKAPSIKAP - RESTRUCTUREDOL - RESTRUCTUREDIPL RIMANSI (DAKILA)' or . = '-- Select --SIKAP 1SIKAP 2MF - SIKAP (GLIP)AGRI LOANHOUSING REPAIRS/IMPROVEMENTSPHILHEALTHSSS PREMIUM LOANMFST- CALAMITY LOANEDUCATIONAL LOAN - ELEMENTARYEDUCATIONAL LOAN - HIGH SCHOOLEDUCATIONAL LOAN - COLLEGEIPL - CAMIAQUICK S.M.E. LOANRPA - REGULAR AGRI LOAN OL-INSURANCE PREMIUM-MBA FAMILY SECURITY PLANMFSL - GADGET LOANMF - SIKAPSIKAP - RESTRUCTUREDOL - RESTRUCTUREDIPL RIMANSI (DAKILA)')]</value>
      <webElementGuid>a8156bdd-9ac6-4f2b-9dea-38138a239fa4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
