<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_-- Select --Negative HitsPositive HitsNot Applicable</name>
   <tag></tag>
   <elementGuidId>88800520-7d7f-4153-9058-2c14cca4178c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='cboMIDASResult']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cboMIDASResult</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>2bcd8c3b-60eb-4aa9-905c-087930187167</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-select  gb-border-fcs</value>
      <webElementGuid>054998ad-fd67-4fd6-9341-d77f3a168e27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cboMIDASResult</value>
      <webElementGuid>8e6b05d2-29eb-463b-bc9e-9c6e94669dfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-- Select --Negative HitsPositive HitsNot Applicable</value>
      <webElementGuid>9d254ad6-fec8-4473-b265-a5b3d9f3d101</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cboMIDASResult&quot;)</value>
      <webElementGuid>4b17d40f-4575-4f23-878d-75a184193703</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='cboMIDASResult']</value>
      <webElementGuid>9593e927-96b6-48e8-bf65-3a09ec45e4c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='loaninfo']/div/div[2]/div/div[2]/div/select</value>
      <webElementGuid>b83d695c-cdb8-4f2d-b1e8-3926fc6f8da6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/select</value>
      <webElementGuid>82fa8649-9a6b-44c0-8230-d9e5085b5bba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'cboMIDASResult' and (text() = '-- Select --Negative HitsPositive HitsNot Applicable' or . = '-- Select --Negative HitsPositive HitsNot Applicable')]</value>
      <webElementGuid>75838ac4-0363-4e72-987d-4fd2c692a71c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
