<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_BusinessType_cboBusinessType</name>
   <tag></tag>
   <elementGuidId>e143a06b-9909-487f-994d-08bb4147005f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='cboBusinessType']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cboBusinessType</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>24831b11-0b4e-4599-9a36-0709ff3321c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-select required gb-border-fcs</value>
      <webElementGuid>b363b750-ef36-41c8-89ed-4367fcdf9cbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cboBusinessType</value>
      <webElementGuid>438edc23-3b49-4a46-b2fe-834762f3c05e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cboBusinessType&quot;)</value>
      <webElementGuid>43c42812-e8e0-46b4-8169-7d4712993837</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='cboBusinessType']</value>
      <webElementGuid>607ecbaf-866d-4b67-b2dc-179d94ec19c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='loaninfo']/div[5]/div/div/div[2]/div/select</value>
      <webElementGuid>548ecf50-523d-4a59-9fbf-19f84b4cc2c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div[2]/div/select</value>
      <webElementGuid>f3add544-c458-41e0-bfe7-eff50a8be1e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'cboBusinessType']</value>
      <webElementGuid>e6dd9372-db8d-4099-8158-0e07ea569b73</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
