<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_LoanPurpose_cboLoanPurpose</name>
   <tag></tag>
   <elementGuidId>0f93ea12-ec3d-49a0-b6de-f19d0033f440</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='cboLoanPurpose']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cboLoanPurpose</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>3a4d8c20-3700-4160-b32a-fac9b0f30e2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-select required gb-border-fcs</value>
      <webElementGuid>3bfbfe5b-ff15-4fce-955a-c8c9c3650142</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cboLoanPurpose</value>
      <webElementGuid>53caaa10-f7df-4da9-ae02-4f9182c257a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cboLoanPurpose&quot;)</value>
      <webElementGuid>a2321f71-f6bb-4921-ba6a-ef10e1d076ce</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='cboLoanPurpose']</value>
      <webElementGuid>3df85fa1-809c-4eea-acf5-f596ad473910</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='loaninfo']/div[4]/div/div/div[2]/div/select</value>
      <webElementGuid>0989b12d-2494-4d0b-ae3c-3e6cabc47de3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div[2]/div/select</value>
      <webElementGuid>13aaed62-fcfc-420e-8386-0ab17ad693ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'cboLoanPurpose']</value>
      <webElementGuid>a92fce51-8c79-447f-83a3-d237d715d9fc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
