<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Term_cboTerm</name>
   <tag></tag>
   <elementGuidId>859cd563-f4d2-462a-a09f-dd6a8b83cab0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='cboTerm']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cboTerm</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>a8239a68-170e-4eca-8516-fb9cba5a2985</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-select computeLRF required gb-border-fcs</value>
      <webElementGuid>65b1ea6e-077c-43e9-a695-26a205bd21ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cboTerm</value>
      <webElementGuid>6bbe8e90-a808-4bf1-aa80-22bec8fa05d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cboTerm&quot;)</value>
      <webElementGuid>7e3d79ff-19e7-4503-b351-a89c30c0d0e9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='cboTerm']</value>
      <webElementGuid>cac7a764-dc4d-4860-a930-facb8fe5cabb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='loaninfo']/div[6]/div/div/div[2]/div/select</value>
      <webElementGuid>1fb20d0a-eaaf-47d1-8c2f-6007272c6314</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div[2]/div/select</value>
      <webElementGuid>80a72379-ab23-4983-91c8-23e5abe60f22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'cboTerm']</value>
      <webElementGuid>24ef39d3-a67b-48f4-8835-4f67320dc060</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
