<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_LoanFrequency_cboLoanFrequency</name>
   <tag></tag>
   <elementGuidId>d586c4ca-7054-4ddb-8a23-f38487ec3791</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='cboLoanFrequency']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cboLoanFrequency</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>4997ff79-9e31-493d-8ef1-4b5fec10b5d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-select computeLRF required gb-border-fcs</value>
      <webElementGuid>ab0c8a2a-1261-4a83-bbdb-1b92e6db87c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cboLoanFrequency</value>
      <webElementGuid>7d1d7ac2-9803-4d66-a953-68118462414d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>ComputeLRF();</value>
      <webElementGuid>4f3434d3-9f5b-495a-b5fc-033df08b91d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cboLoanFrequency&quot;)</value>
      <webElementGuid>fbf1edac-fea0-4884-8e25-3c0e55afa6f4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='cboLoanFrequency']</value>
      <webElementGuid>5d1a8c26-5cec-4501-a23c-a73bf0c7a27e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='loaninfo']/div[2]/div[3]/div/div[2]/div/select</value>
      <webElementGuid>fa91fe03-d9cf-46b0-9b4b-c4d19dcc4617</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/div/div[2]/div/select</value>
      <webElementGuid>9aab4ea6-de50-4951-83dc-fb4d2b39ed5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'cboLoanFrequency']</value>
      <webElementGuid>e8fd4e5c-06f5-4910-8c95-28b74509cba9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
