<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_-- Select --ApprovedDisapprovedNot Applicable</name>
   <tag></tag>
   <elementGuidId>ed6e135a-a29a-47f1-aa1c-68f1a900337f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='cboRemarks']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cboRemarks</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>9ff86951-c365-4fdd-8354-de6cdcb6c4c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-select gb-border-fcs</value>
      <webElementGuid>b63d88bc-4afc-4615-a9df-c493d57491e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cboRemarks</value>
      <webElementGuid>e33cd703-d3df-48ac-9d5c-4831a7a58fce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-- Select --ApprovedDisapprovedNot Applicable</value>
      <webElementGuid>b3ced11c-cd78-4ff8-b959-c0132b8f7ffe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cboRemarks&quot;)</value>
      <webElementGuid>20322ce9-f908-4ae4-9127-efcccb391f06</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='cboRemarks']</value>
      <webElementGuid>aef9ffaf-6153-4dc5-92f4-0cb14d54dbc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='loaninfo']/div/div[3]/div/div[2]/div/select</value>
      <webElementGuid>6734f45f-93ea-42bf-82f7-b63610d62bc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/div/select</value>
      <webElementGuid>c57c3160-268b-415d-b35d-f7237e162023</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'cboRemarks' and (text() = '-- Select --ApprovedDisapprovedNot Applicable' or . = '-- Select --ApprovedDisapprovedNot Applicable')]</value>
      <webElementGuid>4a1426c0-cb71-4548-8608-8b6eb2a42c72</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
