<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_-- SelectLoanCategory</name>
   <tag></tag>
   <elementGuidId>111e51d6-6dbc-4e0e-ba69-f02ad8addcfe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='cboLoanCategory']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cboLoanCategory</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>13c37f7a-8b92-43fd-bafc-743eb91ef9df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-select required gb-border-fcs</value>
      <webElementGuid>4b71337a-05a3-443d-a7d3-161c528dbf6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cboLoanCategory</value>
      <webElementGuid>9fc3ef85-a03f-4b91-acb2-692e7b29f2d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-- Select --AGRICULTURE, FORESTRY AND FISHINGACCOMODATION AND FOOD SERVICE ACTIVITIESADMINISTRATIVE AND SUPPORT SERVICE ACTIVITIESARTS, ENTERTAINMENT AND RECREATIONCONSTRUCTIONELECTRICITY, GAS, STEAM AND AIR CONDITIONING SUPPLYFINANCIAL AND INSURANCE ACTIVITIESHUMAN HEALTH AND SOCIAL WORK ACTIVITIESINFORMATION AND COMMUNICATIONMANUFACTURINGMINING AND QUARRYINGOTHER SERVICE ACTIVITIESPROFESSIONAL, SCIENTIFIC AND TECHNICAL ACTIVITIESREAL ESTATE ACTIVITIESTRANSPORTATION AND STORAGEWATER SUPPLY, SEWERAGE, WASTE MANAGEMENT AND REMEDIATION SYSTEMWHOLESALE AND RETAIL TRADE; REPAIR OF MOTOR VEHICLES AND MOTORCYCLES</value>
      <webElementGuid>d86a29d6-4a7d-46bc-b79e-9f744c18cd9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cboLoanCategory&quot;)</value>
      <webElementGuid>86269a7f-b202-45c2-a310-2cd45e56fe76</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='cboLoanCategory']</value>
      <webElementGuid>a18c53e8-0519-4c07-86ec-82302151dad4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='loaninfo']/div[3]/div/div/div[2]/div/select</value>
      <webElementGuid>bdd40f77-2c94-4ec3-8bfc-505bdaeecaf6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[2]/div/select</value>
      <webElementGuid>2846fe87-ac1a-45e5-a5e0-3064a066213e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'cboLoanCategory' and (text() = '-- Select --AGRICULTURE, FORESTRY AND FISHINGACCOMODATION AND FOOD SERVICE ACTIVITIESADMINISTRATIVE AND SUPPORT SERVICE ACTIVITIESARTS, ENTERTAINMENT AND RECREATIONCONSTRUCTIONELECTRICITY, GAS, STEAM AND AIR CONDITIONING SUPPLYFINANCIAL AND INSURANCE ACTIVITIESHUMAN HEALTH AND SOCIAL WORK ACTIVITIESINFORMATION AND COMMUNICATIONMANUFACTURINGMINING AND QUARRYINGOTHER SERVICE ACTIVITIESPROFESSIONAL, SCIENTIFIC AND TECHNICAL ACTIVITIESREAL ESTATE ACTIVITIESTRANSPORTATION AND STORAGEWATER SUPPLY, SEWERAGE, WASTE MANAGEMENT AND REMEDIATION SYSTEMWHOLESALE AND RETAIL TRADE; REPAIR OF MOTOR VEHICLES AND MOTORCYCLES' or . = '-- Select --AGRICULTURE, FORESTRY AND FISHINGACCOMODATION AND FOOD SERVICE ACTIVITIESADMINISTRATIVE AND SUPPORT SERVICE ACTIVITIESARTS, ENTERTAINMENT AND RECREATIONCONSTRUCTIONELECTRICITY, GAS, STEAM AND AIR CONDITIONING SUPPLYFINANCIAL AND INSURANCE ACTIVITIESHUMAN HEALTH AND SOCIAL WORK ACTIVITIESINFORMATION AND COMMUNICATIONMANUFACTURINGMINING AND QUARRYINGOTHER SERVICE ACTIVITIESPROFESSIONAL, SCIENTIFIC AND TECHNICAL ACTIVITIESREAL ESTATE ACTIVITIESTRANSPORTATION AND STORAGEWATER SUPPLY, SEWERAGE, WASTE MANAGEMENT AND REMEDIATION SYSTEMWHOLESALE AND RETAIL TRADE; REPAIR OF MOTOR VEHICLES AND MOTORCYCLES')]</value>
      <webElementGuid>f6fcebf6-8996-4a2b-b9de-822a0f5e5a1b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
