<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Relationship</name>
   <tag></tag>
   <elementGuidId>14185664-4afa-44be-a9d8-f77ccdabb3da</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='cboCoRelationship2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cboCoRelationship2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>f48fb0d7-5e35-45e4-8cac-34614ac2fea0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-select required gb-border-fcs</value>
      <webElementGuid>d63ff34d-0665-44d2-9efa-6467410079b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cboCoRelationship2</value>
      <webElementGuid>91f20311-b569-41e0-8eb0-a6b514d5dee2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-- Select --SpouseSonDaughterMotherFatherGrandmotherGrandfatherCousinFriendBrotherSister</value>
      <webElementGuid>e13698a6-33aa-42b5-915b-5ef08301a633</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cboCoRelationship2&quot;)</value>
      <webElementGuid>06eddb2c-680c-4b37-a429-96b819ab5798</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='cboCoRelationship2']</value>
      <webElementGuid>57b18dae-80c1-43a0-9b23-fee097f2777e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='row2']/div[2]/div/div[2]/div/select</value>
      <webElementGuid>403daa38-7877-4f88-adc3-f73b703d7b4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/div/div[2]/div/select</value>
      <webElementGuid>708b34c2-f14b-493e-bb58-c5a51a52d1f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'cboCoRelationship2' and (text() = '-- Select --SpouseSonDaughterMotherFatherGrandmotherGrandfatherCousinFriendBrotherSister' or . = '-- Select --SpouseSonDaughterMotherFatherGrandmotherGrandfatherCousinFriendBrotherSister')]</value>
      <webElementGuid>0a3af61a-e8fc-416d-a949-24102d643233</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
