<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_ClientApproval</name>
   <tag></tag>
   <elementGuidId>504c74ff-5db7-45da-9070-04b048bd8053</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ClientApproval</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='ClientApproval']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Client Approval&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f8239290-ce2c-40e8-a7f5-dd335bec9ead</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gb-hover-side confirmation-link</value>
      <webElementGuid>b6d149a8-e748-49f0-8c95-1d4f0b38634a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>ClientApproval</value>
      <webElementGuid>e14b5075-e80b-487b-9016-f4e311e5c20e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ClientApproval</value>
      <webElementGuid>077c5ce0-df85-422c-bbe3-468394d6d685</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>return loadIframe('ifrm1', this.href);</value>
      <webElementGuid>13df3f08-df37-4858-88c2-4b38b3f69712</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Client
									Approval </value>
      <webElementGuid>ca279099-088c-4de3-8941-4997018ec638</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ClientApproval&quot;)</value>
      <webElementGuid>19d858e3-3d4e-445a-abcb-8a7fd4ce889e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='ClientApproval']</value>
      <webElementGuid>66a4c5de-99be-4e95-b255-2d16d26680fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sidebarCustomer']/ul/li[4]/a</value>
      <webElementGuid>4ce97dc0-ac30-44b2-aec5-a6d2118ce6eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Client
									Approval')]</value>
      <webElementGuid>4d015c64-c6ed-41df-b72d-1e54f88be3d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Payment'])[1]/preceding::a[2]</value>
      <webElementGuid>3e952cd2-baa5-4632-a7fe-bd32b99337d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'ClientApproval')]</value>
      <webElementGuid>10d12945-da8f-4352-a992-59b765b5d724</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/div/ul/li[4]/a</value>
      <webElementGuid>9100b7fc-005b-4155-b173-2e35cf8307f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'ClientApproval' and @id = 'ClientApproval' and (text() = ' Client
									Approval ' or . = ' Client
									Approval ')]</value>
      <webElementGuid>ecded835-995c-4c19-904b-6ddfa5758c22</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
