<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Amendment</name>
   <tag></tag>
   <elementGuidId>7210335e-45ec-4626-8145-3e7bde98323e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Amendmenttab > span.d-none.d-md-block</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='Amendmenttab']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=tab[name=&quot;Amendment&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>b5262899-19c4-4e81-ae95-a742eb9ce6a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>d-none d-md-block</value>
      <webElementGuid>7b348987-1b6b-4132-a442-b42565e18222</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Amendment</value>
      <webElementGuid>4d299267-07e4-4980-b438-cc05fa6784fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Amendmenttab&quot;)/span[@class=&quot;d-none d-md-block&quot;]</value>
      <webElementGuid>f8477c90-e4e3-4a93-8653-829c01e02694</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='Amendmenttab']/span</value>
      <webElementGuid>5af31bd8-9d4b-4d6b-802c-e5f338dbcecb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New Client'])[1]/following::span[1]</value>
      <webElementGuid>6f861744-eae9-4ae0-abc2-9c5622dad7bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Client Approval'])[2]/following::span[2]</value>
      <webElementGuid>b4fedae9-01ab-43e0-b8f4-6f8896d154da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reactivation'])[1]/preceding::span[1]</value>
      <webElementGuid>2862d6a0-e013-49fc-bc1b-ec0c629886c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Closing'])[1]/preceding::span[2]</value>
      <webElementGuid>23164507-07da-4ad7-b482-ac752703d668</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Amendment']/parent::*</value>
      <webElementGuid>6ab42a72-e963-4fc6-89cf-973e59dd6059</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/ul/li[2]/a/span</value>
      <webElementGuid>346fc474-8840-41e0-a1e4-5443f558ea2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Amendment' or . = 'Amendment')]</value>
      <webElementGuid>b7540e7c-94b0-4b35-a77f-111dcf3c6f6b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
