<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Remarks_beneRow1</name>
   <tag></tag>
   <elementGuidId>d49231a7-e05a-4690-87c5-cb1379654699</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//i[@id='beneRow1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#beneRow1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>c3fd461e-99f9-4efe-9e60-d5db6e0ac115</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>beneRow1</value>
      <webElementGuid>208f6898-71dc-44d6-ac56-b3774deeb850</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ri-add-circle-fill</value>
      <webElementGuid>fbfbad00-2a9b-41e4-8ee7-ada724f28af8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;beneRow1&quot;)</value>
      <webElementGuid>311a3cc5-ce14-46ff-8c80-8da90d102639</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//i[@id='beneRow1']</value>
      <webElementGuid>a8d319ed-3ca2-447e-bc1e-4370a44ec8dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='add-benerow-button']/i</value>
      <webElementGuid>74531a3e-0803-4d7f-b46f-f8a7b8752cc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div[7]/div/button/i</value>
      <webElementGuid>daa2418b-620e-4f4b-b151-1dbd78ad8257</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//i[@id = 'beneRow1']</value>
      <webElementGuid>9024722f-5b32-4b46-896f-074de2c392ee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
