<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_HouseholdMonthly Expense_txtMonthlyExpense</name>
   <tag></tag>
   <elementGuidId>954b89b3-1f50-405c-97c6-6a0fded00969</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtMonthlyExpense']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#txtMonthlyExpense</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#txtMonthlyExpense</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>22a914e9-335d-4c1c-b7e8-dc8dd2a043d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>e31b3f7a-805d-4c60-ae18-d262a5e41eae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4d225350-5fb1-4796-b9e4-9d8fad02b069</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control gb-border-fcs font-11</value>
      <webElementGuid>f3bb3c7a-7373-4900-b0d2-0a66f594a688</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtMonthlyExpense</value>
      <webElementGuid>b0403163-85e0-4fb5-a6f8-e2e2c991ae6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtMonthlyExpense&quot;)</value>
      <webElementGuid>027cd839-3e04-422b-8fc3-f4b47dab0cce</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtMonthlyExpense']</value>
      <webElementGuid>6f1e1e85-9578-4e73-af49-c1f6bed87f60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='7']/div/div/div/div[6]/div/input</value>
      <webElementGuid>01a27178-5629-4080-b183-379ed96e54bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div/div/div[6]/div/input</value>
      <webElementGuid>b985573a-9456-4cb0-82f3-240480e6733d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'txtMonthlyExpense']</value>
      <webElementGuid>2e5ffff1-6f10-418a-8212-9fcaf37aa642</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
