<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_--Select--BrotherBrother-in-LawCousi_e1fca2</name>
   <tag></tag>
   <elementGuidId>e7b7fd56-8330-437c-b26c-9a5e1dca3551</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='cboBenRelType2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cboBenRelType2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#cboBenRelType2</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>20c5b66e-1245-4389-89ae-f611be58b07a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cboBenRelType2</value>
      <webElementGuid>261cd3b8-89cb-4a69-a96f-a3b7d0e7f49f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>6cde0897-2ed7-4cd8-a911-c21b083e9e1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> form-select required gb-border-fcs font-9</value>
      <webElementGuid>1967df78-7897-450c-8167-0d826d61b7d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>--Select--BrotherBrother-in-LawCousinDaughterFatherFather-in-LawMotherMother-in-LawOther relativesSisterSister-in-LawSonSpouse</value>
      <webElementGuid>31da984f-dfb0-4d0a-9a73-21670267a29d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cboBenRelType2&quot;)</value>
      <webElementGuid>c92c5378-21b2-432b-91df-f3f8db552a0f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='cboBenRelType2']</value>
      <webElementGuid>95d8b801-89b3-497a-b9f6-b042f4ea9b29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='row2']/div/div[3]/div/div/select</value>
      <webElementGuid>d4b49b96-7680-480b-b4c8-e65c96c7136a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remarks:'])[1]/following::select[8]</value>
      <webElementGuid>b4e2e99f-98e1-4c8b-8d3b-75e893f96923</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Additional Beneficiary If any'])[1]/preceding::select[7]</value>
      <webElementGuid>2228dad9-f517-4157-a03a-68bb0030a9d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Client Risk Assessment'])[2]/preceding::select[7]</value>
      <webElementGuid>8313b7e5-80b0-45ff-8ab4-e9919e4d2fb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div[3]/div/div/select</value>
      <webElementGuid>71e89163-1668-420e-b0eb-07a30c6b8e6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'cboBenRelType2' and (text() = '--Select--BrotherBrother-in-LawCousinDaughterFatherFather-in-LawMotherMother-in-LawOther relativesSisterSister-in-LawSonSpouse' or . = '--Select--BrotherBrother-in-LawCousinDaughterFatherFather-in-LawMotherMother-in-LawOther relativesSisterSister-in-LawSonSpouse')]</value>
      <webElementGuid>c0a33418-f584-41dd-95f5-ce2437022ea4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
