<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select      51015_1</name>
   <tag></tag>
   <elementGuidId>3363d6fa-ff09-426f-b849-2db2361fa61c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='cbosixthRiskAnswer']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cbosixthRiskAnswer</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#cbosixthRiskAnswer</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>40235ec3-60e3-436d-874c-c14bd1cf0147</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-center gb-border-fcs Ans6</value>
      <webElementGuid>e42827de-60d1-4056-9e2d-76840a4a9355</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cbosixthRiskAnswer</value>
      <webElementGuid>44627e95-8442-4179-8360-69fe1c8f1ff8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>     Select      51015</value>
      <webElementGuid>bb4572ec-7934-4657-9f24-91cf7d4fbb99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cbosixthRiskAnswer&quot;)</value>
      <webElementGuid>5caa3e3d-b542-4744-ada6-fdb1de64cf28</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='cbosixthRiskAnswer']</value>
      <webElementGuid>9bbc4cf4-18de-48d9-b55c-54f935990d58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='tblRiskclassSixBody']/tr/td[9]/select</value>
      <webElementGuid>291cbe38-4c2d-40a2-a1e8-edd20d73df89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Casino, gaming, broker-dealers'])[1]/following::select[1]</value>
      <webElementGuid>4ab2b1f1-20e2-4da1-8c18-01bae4f01629</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All other business other than mentioned in high risk'])[1]/following::select[1]</value>
      <webElementGuid>650ad7fe-c37f-4d90-bd7b-8c192a5393ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Types of service / products to be availed of'])[1]/preceding::select[1]</value>
      <webElementGuid>cf10f8d7-2962-49df-90c6-ec0023776455</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CBU/Micro-savings/ Micro-insurance/Microloans'])[1]/preceding::select[1]</value>
      <webElementGuid>bb302e33-2e38-4203-8d43-9bc71493c52a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tbody[6]/tr/td[9]/select</value>
      <webElementGuid>e5c9cbb7-aff2-4c7a-b086-99d0d851348a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'cbosixthRiskAnswer' and (text() = '     Select      51015' or . = '     Select      51015')]</value>
      <webElementGuid>8f46fd99-b85c-4edb-8c8d-c88ff7eabd44</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
