<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_--Select--AnnulledLive-inMarriedSepa_54a068</name>
   <tag></tag>
   <elementGuidId>98eaa54d-adfe-40c7-8ce1-d10ac9d00a81</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='cboCivilStatus']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cboCivilStatus</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#cboCivilStatus</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>16e594fc-640f-4d6c-ad6f-c66342ca417a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cboCivilStatus</value>
      <webElementGuid>4bd808fa-7b64-4590-88e5-7b27a1db46ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>CivilStatusType();</value>
      <webElementGuid>586c478f-5574-4c61-917c-0574ad0607af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-select gb-border-fcs select2 font-11</value>
      <webElementGuid>84d6a602-d759-452c-86f8-a88fdb9f048a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>select2</value>
      <webElementGuid>d43d56a3-cf02-4ec7-8918-322a42c42c50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>--Select--AnnulledLive-inMarriedSeparatedSingleWidowed</value>
      <webElementGuid>148331bb-1ab5-4646-bdd4-11e12f1c95de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cboCivilStatus&quot;)</value>
      <webElementGuid>e013d9a5-f32e-47d0-972c-65311d12b206</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='cboCivilStatus']</value>
      <webElementGuid>a900a352-eaa6-4662-b861-77b53ab08ced</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='myform']/div/div/div[12]/div/div/select</value>
      <webElementGuid>63d97a7b-2a9d-42ef-8f2e-9a2ca9aa9e26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[12]/div/div/select</value>
      <webElementGuid>a143bfea-8505-4556-a84f-5060cb944e98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'cboCivilStatus' and (text() = '--Select--AnnulledLive-inMarriedSeparatedSingleWidowed' or . = '--Select--AnnulledLive-inMarriedSeparatedSingleWidowed')]</value>
      <webElementGuid>7c63c40e-5819-4b99-8706-2b4206f0cef6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
