<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_--Select--YESNO_1</name>
   <tag></tag>
   <elementGuidId>89e4f5b2-45bf-4cec-b1a0-3a3d577a492f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='cboCardMRIScho2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cboCardMRIScho2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#cboCardMRIScho2</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>aee5b0f3-21a3-478a-ab94-dbc0d95495ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cboCardMRIScho2</value>
      <webElementGuid>254c456f-ab14-4941-9623-e2e79702876d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>1d73ea35-7561-491d-91ee-d85d35b4d5ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> form-select required gb-border-fcs font-9</value>
      <webElementGuid>35df99dc-8bd2-468e-8270-0dc2eb984e1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
					--Select--
					YES
					NO
				</value>
      <webElementGuid>2da5d494-aa30-4f09-a0ef-4b33fb2f8ada</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cboCardMRIScho2&quot;)</value>
      <webElementGuid>e59d1a3f-51e9-4701-84d6-e60b4458e27d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='cboCardMRIScho2']</value>
      <webElementGuid>2d239b2c-b643-4919-a29f-97f7958c3287</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='row2']/div/div[9]/div/div/select</value>
      <webElementGuid>96085624-ed7b-4cac-939a-f4ad597100f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remarks:'])[1]/following::select[13]</value>
      <webElementGuid>6d9bdd01-b5e7-42eb-bdde-eeade8b6f3a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Additional Beneficiary If any'])[1]/preceding::select[2]</value>
      <webElementGuid>44a90c55-c963-413f-b0e7-3664dd82b93f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Client Risk Assessment'])[2]/preceding::select[2]</value>
      <webElementGuid>93502cc0-7518-4a45-8f4d-55159c243c05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div[9]/div/div/select</value>
      <webElementGuid>b54d34ab-74d5-4029-8141-c4bd4898a7a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'cboCardMRIScho2' and (text() = '
					--Select--
					YES
					NO
				' or . = '
					--Select--
					YES
					NO
				')]</value>
      <webElementGuid>b5410e88-d81c-4887-aa83-8ed4228cee6c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
