<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select      51015</name>
   <tag></tag>
   <elementGuidId>80231215-786f-472a-8a01-951a10c9bc86</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='cboRiskAnswerList']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cboRiskAnswerList</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#cboRiskAnswerList</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>d852c0bb-34ad-4eec-ae03-8459e18591fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-center gb-border-fcs Ans1</value>
      <webElementGuid>f6e97ca0-7d00-408a-9f5d-1df87dba4153</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cboRiskAnswerList</value>
      <webElementGuid>8693d99f-a40c-4908-8ca0-c8868a92d825</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>     Select      51015</value>
      <webElementGuid>4877d222-6fb2-444e-a008-419586887025</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cboRiskAnswerList&quot;)</value>
      <webElementGuid>bf6bc402-5917-4b8e-87fb-485326a5b6e8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='cboRiskAnswerList']</value>
      <webElementGuid>a047d538-c073-4071-a41a-c950b8c55dfa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='tblRiskclassPriBody']/tr/td[9]/select</value>
      <webElementGuid>b29a8686-8de1-4428-8f7b-b39a8d68de4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Business/es (other than those mentioned under high risks).'])[1]/following::select[1]</value>
      <webElementGuid>8459d369-4565-4e29-830c-175251dfc482</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Salary / Employment / Micro-enterprises (including small sari-sari store).'])[1]/following::select[1]</value>
      <webElementGuid>52e45f85-63bd-44b7-917e-a0e1df8590a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Country of Origin / Residence'])[1]/preceding::select[1]</value>
      <webElementGuid>fafed93b-76f6-4836-a5e9-b712895f65e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Philippines within the area where the bank is operating.'])[1]/preceding::select[1]</value>
      <webElementGuid>47cdcfbb-62b8-4bf0-aa2b-a4888cb256b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[9]/select</value>
      <webElementGuid>26146447-3a0f-423c-b7c0-a438be61dee3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'cboRiskAnswerList' and (text() = '     Select      51015' or . = '     Select      51015')]</value>
      <webElementGuid>aa148f7f-5329-47cc-977e-0161dd1546ac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
