<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_--      Select      --0 - Hindi13 - Oo</name>
   <tag></tag>
   <elementGuidId>83f7821f-4335-41e1-a1a8-d7f762fca75d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='cboeighthQAnswer']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cboeighthQAnswer</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#cboeighthQAnswer</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>6f1d4c38-87ce-4e2d-a01e-f343151870cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>validatelenght required gb-border-fcs form-select  Ans</value>
      <webElementGuid>920a2af2-a9f2-4976-8271-26bb6e08472b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cboeighthQAnswer</value>
      <webElementGuid>a904a6db-e6de-4fe9-9eb8-b29849892764</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>--      Select      --[0] - Hindi[13] - Oo</value>
      <webElementGuid>d4f9ef8b-d7dd-4d6c-8acf-4a0c88a33e1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cboeighthQAnswer&quot;)</value>
      <webElementGuid>fe82f524-6a0d-42b1-a892-2a2fe61cd40b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='cboeighthQAnswer']</value>
      <webElementGuid>ca119b88-9fbe-484a-b253-d100d4d1d5d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='tblPPIBodyEighth']/tr/td[2]/select</value>
      <webElementGuid>027e3a46-ec5e-46db-923f-67d57efcc30d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mga Indikasyon/Indicators'])[1]/preceding::select[3]</value>
      <webElementGuid>481551f6-c8b7-49ed-8cd6-a5c67f8d10c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Puntos'])[1]/preceding::select[3]</value>
      <webElementGuid>488283d9-a8d1-4aa7-8606-8e834c4036b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tbody[8]/tr/td[2]/select</value>
      <webElementGuid>3bf56126-7bd2-46aa-84f3-3826720333ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'cboeighthQAnswer' and (text() = '--      Select      --[0] - Hindi[13] - Oo' or . = '--      Select      --[0] - Hindi[13] - Oo')]</value>
      <webElementGuid>a0e91967-223c-48da-b486-e52efedf56a3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
