<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_--      Select      --0 - Hindi8 - Oo</name>
   <tag></tag>
   <elementGuidId>d8ed65b2-7089-4a4c-a9c6-3fd2f8af6295</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='cbotenthQAnswer']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cbotenthQAnswer</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#cbotenthQAnswer</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>a4584f91-ee14-428c-b9fc-9e72defd9d09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>validatelenght required gb-border-fcs form-select  Ans</value>
      <webElementGuid>70adeeba-db85-4e04-9d4f-4058d1e2f6db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cbotenthQAnswer</value>
      <webElementGuid>50363c32-8baa-4b46-bb16-2b2752591eef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>--      Select      --[0] - Hindi[8] - Oo</value>
      <webElementGuid>adc4c825-cbb2-4187-9251-510afdf3269f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cbotenthQAnswer&quot;)</value>
      <webElementGuid>9b4024fe-3d3b-487d-af45-5c600f99fc3f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='cbotenthQAnswer']</value>
      <webElementGuid>f4384a5a-eb69-4e13-a0e2-7bbbd1f21b32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='tblPPIBodyTenth']/tr/td[2]/select</value>
      <webElementGuid>79037d15-be70-4ca7-aaf0-ee0aeb45bc1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mga Indikasyon/Indicators'])[1]/preceding::select[1]</value>
      <webElementGuid>d8c26be3-6d7b-417e-bd52-af3cb1a74a5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Puntos'])[1]/preceding::select[1]</value>
      <webElementGuid>9f3e52b1-d175-4d8c-b91e-62451215e334</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tbody[10]/tr/td[2]/select</value>
      <webElementGuid>d63381fb-85c9-46f6-8e57-5d6016f569b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'cbotenthQAnswer' and (text() = '--      Select      --[0] - Hindi[8] - Oo' or . = '--      Select      --[0] - Hindi[8] - Oo')]</value>
      <webElementGuid>7c9bc158-4da4-468c-9b17-f8fed2da13cf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
