<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_--Select--FemaleMale</name>
   <tag></tag>
   <elementGuidId>a4830699-cb64-4700-9ddf-1f3e4e465f75</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='cboSpouseGender']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cboSpouseGender</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#cboSpouseGender</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>8c43d94c-d186-425f-899e-f0e8e8be41dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cboSpouseGender</value>
      <webElementGuid>b374ffdc-cdf4-4295-8535-0e32f3adfbf1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>cb00a604-3e43-4dbe-970a-7e9466e6236b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-select gb-border-fcs font-11</value>
      <webElementGuid>cd1e8c07-c088-49ca-9c02-98f0f29051df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>--Select--FemaleMale</value>
      <webElementGuid>dfce5c4f-86cc-43f5-9b7f-96c59badddd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cboSpouseGender&quot;)</value>
      <webElementGuid>c430f766-4aa5-4a28-b627-ad3d22468c88</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='cboSpouseGender']</value>
      <webElementGuid>3b04473e-748e-4ca2-9478-34c157fb7a99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='5']/div/div/div[2]/div/div/div[7]/div/div/select</value>
      <webElementGuid>531e5808-f821-43d8-abad-4d573171c33f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[7]/div/div/select</value>
      <webElementGuid>5a3804ae-b955-460c-b0a6-44968c5b570e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'cboSpouseGender' and (text() = '--Select--FemaleMale' or . = '--Select--FemaleMale')]</value>
      <webElementGuid>adef71b1-0572-4374-86b3-be27e3234ee8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
