<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select      51020</name>
   <tag></tag>
   <elementGuidId>75b777ab-d0ff-45e6-ad30-cdbda951f4fd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='cbothirdRiskAnswer']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cbothirdRiskAnswer</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#cbothirdRiskAnswer</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>bd405486-fcb8-44ab-9900-3e31a78a30bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-center gb-border-fcs Ans3</value>
      <webElementGuid>750ed62b-1024-434b-90f2-a63f1358370e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cbothirdRiskAnswer</value>
      <webElementGuid>18d2edfd-d596-49f3-af02-a25a2590e9fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>     Select      51020</value>
      <webElementGuid>4e182029-d03d-4dae-8a9a-cc9fba1ded3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cbothirdRiskAnswer&quot;)</value>
      <webElementGuid>a5478686-8da5-4e21-8e83-cb99cadeb432</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='cbothirdRiskAnswer']</value>
      <webElementGuid>300a2c80-10a6-45a2-acdd-a5ace59c14ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='tblRiskclassThirdBody']/tr/td[9]/select</value>
      <webElementGuid>bec1c02e-8b6f-4b8d-b145-2322abe7ebb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Incumbent Politician'])[1]/following::select[1]</value>
      <webElementGuid>8192a8ce-aa92-422d-b66d-0b321a1b6192</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rank and file/retired'])[1]/following::select[1]</value>
      <webElementGuid>95017d48-a64e-41be-8b71-256eaf6c434c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='With Materially Link Accounts'])[1]/preceding::select[1]</value>
      <webElementGuid>2402c379-cbe7-40f5-b56b-e1d04f16e94d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='None'])[5]/preceding::select[1]</value>
      <webElementGuid>44178b69-6358-42d0-af5e-b3790cf7e3ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tbody[3]/tr/td[9]/select</value>
      <webElementGuid>441e03a7-bf09-4d38-84bf-9192009e5642</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'cbothirdRiskAnswer' and (text() = '     Select      51020' or . = '     Select      51020')]</value>
      <webElementGuid>2824cd5a-c5d9-409f-8710-02af2a5c2e70</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
