<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_--Select--EmploymentSalariesIncome f_b99596</name>
   <tag></tag>
   <elementGuidId>766e647e-e080-4c36-940d-595cd0289772</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='cboSourceOfIncome']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cboSourceOfIncome</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#cboSourceOfIncome</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>bee04b38-7622-434e-9af5-79fd9dcdd449</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cboSourceOfIncome</value>
      <webElementGuid>f98e36ee-f28c-4350-860b-9f64a8322881</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>dbc3020c-4e66-4586-b70d-7174503ff644</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>checksourceOfFund();</value>
      <webElementGuid>c32ad88a-0ee1-4d9a-b202-29316a23774c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-select gb-border-fcs font-11</value>
      <webElementGuid>6c62fd48-1072-4458-9478-00c007227489</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>--Select--Employment/SalariesIncome from businessInheritanceOthersProceeds from investmentRemittancesRetirement/Pension</value>
      <webElementGuid>4842f6c0-9cb2-4ef8-9667-a1032e7a3ae6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cboSourceOfIncome&quot;)</value>
      <webElementGuid>343e5bc8-421b-499a-b54c-befd25c7e883</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='cboSourceOfIncome']</value>
      <webElementGuid>17986d1e-bfaf-41a8-83df-928f72117f03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='5']/div/div/div[2]/div[2]/div/div[4]/div/div/select</value>
      <webElementGuid>fd628038-4a6f-4735-86b5-5fa8ac2251b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div[4]/div/div/select</value>
      <webElementGuid>b44fbb70-ee3d-4b79-852d-1895f544284d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'cboSourceOfIncome' and (text() = '--Select--Employment/SalariesIncome from businessInheritanceOthersProceeds from investmentRemittancesRetirement/Pension' or . = '--Select--Employment/SalariesIncome from businessInheritanceOthersProceeds from investmentRemittancesRetirement/Pension')]</value>
      <webElementGuid>d5950146-d39e-45d3-b0f1-33bcf5b07af8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
