<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Post</name>
   <tag></tag>
   <elementGuidId>d4b7e837-c4a2-49e4-829f-2c6da2f14b6f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btnPost']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btnPost</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d278b9c3-92eb-4bf6-b792-d77fda4554ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>30f5c84f-4a9b-4ce5-a9ce-25ed09e475ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-success</value>
      <webElementGuid>d48de098-92a4-459f-b05e-486dd23697f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnPost</value>
      <webElementGuid>7ffed764-2ecc-45fd-a2a1-0224c4b0216b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Post</value>
      <webElementGuid>d7ee6fff-fa73-4bbd-b299-e8af1509e2d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnPost&quot;)</value>
      <webElementGuid>c555275b-41de-4ff7-add6-9dcf0b24b98d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btnPost']</value>
      <webElementGuid>51d4ce9b-dd6f-4094-946b-4521ef7bf4aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='body']/div/div[4]/div/div/div/div[2]/div[4]/div/div[2]/div/div/button</value>
      <webElementGuid>e91750c8-5c3e-48d5-9454-d6c8831c2a3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/button</value>
      <webElementGuid>559d5188-4853-4cf0-9a86-c453d5278940</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'btnPost' and (text() = 'Post' or . = 'Post')]</value>
      <webElementGuid>5d1bc390-fa4b-4db3-8aba-1b59e1b3141f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
