<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Net, Ether_inputPaid10000220</name>
   <tag></tag>
   <elementGuidId>89468f6a-663a-457b-8fcd-0edfad458142</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tbody[@id='tblBodyClientList']/tr[2]/td[11]/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#inputPaid10000220</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1ff69b95-18b4-47fb-9e25-331d9f1cd681</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f361906b-909e-4a52-8f81-f482840bf35a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control pay gb-border-fcs</value>
      <webElementGuid>7fc69039-ca5f-41b6-a143-0b73702bf8d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0.00</value>
      <webElementGuid>bec05331-6d29-424c-96d7-09125fba9eac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inputPaid10000220</value>
      <webElementGuid>162b1208-0dc0-40ee-be84-3335a8419594</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inputPaid10000220&quot;)</value>
      <webElementGuid>0a4d7d15-7e23-430c-8bb5-d222462600c8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='inputPaid10000220']</value>
      <webElementGuid>f51286cd-c09b-444d-8a47-43c275b14992</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='tblBodyClientList']/tr[2]/td[12]/input</value>
      <webElementGuid>876ca6de-4f3f-4c1e-987a-6a9cb683e851</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[12]/input</value>
      <webElementGuid>d08c18c9-f0f0-43ac-ab85-1e9b5fdbf55f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'inputPaid10000220']</value>
      <webElementGuid>a78e668f-b10b-4da7-b958-6f5cac5f4d54</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
