<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Net, Ether_inputPai_c2</name>
   <tag></tag>
   <elementGuidId>75a28607-dd6c-4723-86f9-0ac100c64912</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tbody[@id='tblBodyClientList']/tr[3]/td[11]/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#inputPaid10000220</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4e071804-7932-4762-8ff8-d5b9cb02a2c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>bada8f08-601f-4ad6-b52e-018616a90d7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control pay gb-border-fcs</value>
      <webElementGuid>7d5b4424-ff3b-4a0c-8ab9-ce487bcd04f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0.00</value>
      <webElementGuid>edb6b5c1-ee22-478a-8436-d20fe3f322ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inputPaid10000220</value>
      <webElementGuid>afd12128-c892-43a5-816b-c572c08cc9ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inputPaid10000220&quot;)</value>
      <webElementGuid>77602a29-ee32-4ed4-8400-a06c3cde9dbd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='inputPaid10000220']</value>
      <webElementGuid>16228a97-496c-4f62-96b6-700addeb7f98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='tblBodyClientList']/tr[3]/td[12]/input</value>
      <webElementGuid>658d1b6b-65ff-4068-b602-e748ebbc776f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[12]/input</value>
      <webElementGuid>0c91c564-cf0d-4b3e-b7a6-c1ea39c21cfb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'inputPaid10000220']</value>
      <webElementGuid>014ccee3-22d5-41c5-9ca6-0c620892743c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
