<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Total_txtTotalSingleDetails</name>
   <tag></tag>
   <elementGuidId>47cca083-3d55-4738-904d-dd95a715d92b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtTotalSingleDetails']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#txtTotalSingleDetails</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f89958e1-9dbe-49f3-8b38-4f229c339978</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>cea83764-9a96-407c-a72e-5aaec8024099</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b8dca81f-615d-43f1-91b4-ee9dfb9a0283</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>d2b86995-f453-4d4a-baa0-de6401d90a2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtTotalSingleDetails</value>
      <webElementGuid>082c8e6b-0317-44a3-b2a8-1b9c61873cb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtTotalSingleDetails&quot;)</value>
      <webElementGuid>78074d53-8987-4447-a42c-e10b2ac28e4b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtTotalSingleDetails']</value>
      <webElementGuid>cf6bec87-14be-4cab-b4ce-aa8b287e1d64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modalPaymentDetials']/div/div/div[2]/div[2]/div/div/div/div/div[3]/input</value>
      <webElementGuid>170f0aeb-fe08-4bc4-834a-f3a02602ba3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div[3]/input</value>
      <webElementGuid>e0da30b9-e181-41f0-a5e7-861821bac66a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'txtTotalSingleDetails']</value>
      <webElementGuid>77ad2bc0-3843-4bda-8f82-8b8a7db91c0a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
