<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Net, Ether_inputPaid10000220</name>
   <tag></tag>
   <elementGuidId>89468f6a-663a-457b-8fcd-0edfad458142</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tbody[@id='tblBodyClientList']/tr[2]/td[12]/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#inputPaid10000220</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6ce16331-4614-40e3-8568-14f52250541c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>633f0c63-86c9-4523-a36b-c49d967ce676</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control pay gb-border-fcs</value>
      <webElementGuid>5dc54438-b981-4c31-bb9a-ef3ea98175be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0.00</value>
      <webElementGuid>ebd1b20e-0561-446b-9b5f-09bc6dfcbb71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inputPaid10000220</value>
      <webElementGuid>3b12a8fe-f4e6-4e60-bdc2-34cdec44eec8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inputPaid10000220&quot;)</value>
      <webElementGuid>ac844b93-4c34-461f-99bc-ba0a946ffe34</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='inputPaid10000220']</value>
      <webElementGuid>d88f5903-040d-4289-8f50-c6076a51155c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='tblBodyClientList']/tr[2]/td[12]/input</value>
      <webElementGuid>a4079fe0-8c96-4ad1-a077-7d9ea4ab0045</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[12]/input</value>
      <webElementGuid>fe3efa97-39ce-4169-9866-a6aff92f2a75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'inputPaid10000220']</value>
      <webElementGuid>49eb03b1-a432-4c18-8c68-978304bd39d7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
