<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_2,045.00_ttldue_second_row</name>
   <tag></tag>
   <elementGuidId>13483da6-251a-4aa7-bbef-b508075feeff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tbody[@id='tblBodyClientList']/tr[3]/td[7]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>td.text-center.font-11.td-num.totalDue</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>f6f64098-5cb4-413f-8c4f-1298bf25d772</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>colspan</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>e86263a9-867c-411a-95c1-faa915380f5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-center font-11 td-num totalDue</value>
      <webElementGuid>5b021605-2e91-4036-aa79-08e06d281d13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>2,045.00</value>
      <webElementGuid>a4ff19fa-6c81-456e-89ff-33806eed5fb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tblBodyClientList&quot;)/tr[2]/td[@class=&quot;text-center font-11 td-num totalDue&quot;]</value>
      <webElementGuid>294a7057-fe1c-4903-a0b7-3eba69f5cbca</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='tblBodyClientList']/tr[3]/td[7]</value>
      <webElementGuid>58b158b5-5c37-44c8-8a1c-cc3deda77f1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[7]</value>
      <webElementGuid>269a74cd-78f0-46ae-8f7a-d860506ed835</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = '2,045.00' or . = '2,045.00')]</value>
      <webElementGuid>f695a548-5474-4041-ad66-6e34379213d1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
