<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_20.00_amor_first_row</name>
   <tag></tag>
   <elementGuidId>8af8c45c-4e0c-42ff-883a-e187df13b803</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tbody[@id='tblBodyClientList']/tr[2]/td[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>c2dddfb4-e835-4f7f-9275-d24a26f95e85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>colspan</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>9953ae7d-01ae-4043-a1ba-99a9f6a43bb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-center font-11 td-num </value>
      <webElementGuid>13938f0a-51f5-4f47-84e5-039f579f338a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>20.00</value>
      <webElementGuid>0f41901c-129c-42fa-8df1-26204f1b0b9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tblBodyClientList&quot;)/tr[2]/td[@class=&quot;text-center font-11 td-num&quot;]</value>
      <webElementGuid>f786abff-c5d1-4ed7-b576-3a406747c34c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='tblBodyClientList']/tr[2]/td[3]</value>
      <webElementGuid>cef75831-d9e9-4cbe-b19f-d39cd615df2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]</value>
      <webElementGuid>117580a8-ea16-4ea0-8b4a-568c121f6ab3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = '20.00' or . = '20.00')]</value>
      <webElementGuid>6950eb5b-96f8-4248-92db-553709027d72</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
