<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_2,045.00_ttldue_first_row</name>
   <tag></tag>
   <elementGuidId>95a265b6-f385-438a-9a51-bf123704d9f6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tbody[@id='tblBodyClientList']/tr[2]/td[7]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>td.text-center.font-11.td-num.totalDue</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>e2722b89-5d17-4d5f-9e97-f2c8de4f7354</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>colspan</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>9ca96266-4f9d-432a-bee8-dabf5e3ed9f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-center font-11 td-num totalDue</value>
      <webElementGuid>7ef55d30-70f6-4cae-9ed9-5565fb71763b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>2,045.00</value>
      <webElementGuid>3991e640-6cc8-4277-98fc-2d774eb6bd60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tblBodyClientList&quot;)/tr[2]/td[@class=&quot;text-center font-11 td-num totalDue&quot;]</value>
      <webElementGuid>fa9e214c-110e-4202-814e-f67e61674e1b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='tblBodyClientList']/tr[2]/td[7]</value>
      <webElementGuid>5bdec0c5-0138-4009-9e2d-25b80c8312d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[7]</value>
      <webElementGuid>e90e9d20-03f5-478b-af31-88a337403414</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = '2,045.00' or . = '2,045.00')]</value>
      <webElementGuid>5a8ec400-7c3d-41ca-a574-8e88c6c8f878</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
