<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_AGRI LOAN_ri-close-circle-fill</name>
   <tag></tag>
   <elementGuidId>e83eee74-9fd4-42aa-8779-600e2b0e5a1f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tbody[@id='LoanDisbursmentTbody']/tr/td[11]/a[2]/span/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.ri-close-circle-fill</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=row[name=&quot;Web 03/25/2024 10000376 Sahefijujik, Hami Roliceta AGRI LOAN 4016-0000-00000566 5,100.00 408.00 5,080.00 3  &quot;i] >> internal:attr=[title=&quot;Delete Loan&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>a4f1ee59-6fa3-4825-9cb8-d22906aa8a0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ri-close-circle-fill</value>
      <webElementGuid>c0163e97-51d6-453a-9f90-c715daa0d9f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;LoanDisbursmentTbody&quot;)/tr[@class=&quot;odd&quot;]/td[@class=&quot;td-actions&quot;]/a[@class=&quot;action-icon btn&quot;]/span[@class=&quot;icon text-gray-700 ml-auto&quot;]/i[@class=&quot;ri-close-circle-fill&quot;]</value>
      <webElementGuid>fb742fc5-9eb6-45b0-a550-bb8a2445e5ae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='LoanDisbursmentTbody']/tr/td[11]/a[2]/span/i</value>
      <webElementGuid>13abcde5-f264-4381-a5df-3709c20e105d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]/span/i</value>
      <webElementGuid>3ad2ed1b-724d-4723-9254-6d896f79209e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
