<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Post_1</name>
   <tag></tag>
   <elementGuidId>049c10eb-91c1-40a9-9d21-fac07e85fbf8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnPostWithdraw</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btnPostWithdraw']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e40bf4c5-dbd4-49fd-a074-b6441ce37bd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ffdd2ea0-6198-4f11-8e7f-a1ce4bce8fdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-success</value>
      <webElementGuid>e469141b-d1d2-4fa6-bf82-4eb7fb5dd2bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>postTransaction('2')</value>
      <webElementGuid>afbf5ec6-78e1-4b25-9eb0-36dceefbb213</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnPostWithdraw</value>
      <webElementGuid>d5bae261-5171-478b-b4df-339b9df906d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Post</value>
      <webElementGuid>0e6a5dfb-0b65-42e3-a2cd-3c4b9da353fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnPostWithdraw&quot;)</value>
      <webElementGuid>926e4381-9f24-4152-8c74-fcf13c493484</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btnPostWithdraw']</value>
      <webElementGuid>5ba525c6-0bcb-4d24-8579-4477a46f0d43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='withdraw']/div/div[3]/div[2]/button</value>
      <webElementGuid>34460bac-58c7-409e-96c7-6f61e70483ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[3]/div[2]/button</value>
      <webElementGuid>cbcfed1b-a557-4ba6-b03c-fa873c856a3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'btnPostWithdraw' and (text() = 'Post' or . = 'Post')]</value>
      <webElementGuid>9e5d2450-8c6c-4e70-83c7-3f7015c184c1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
