<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Close Account</name>
   <tag></tag>
   <elementGuidId>1fcff745-54f6-43de-995c-1a0ca9dbd07a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnCloseAccount</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btnCloseAccount']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>77e002bc-3029-4e6a-8a26-dd5301a243d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>22edbd0a-eb47-4764-8d35-39b834e8c426</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-danger</value>
      <webElementGuid>fa9ae222-1a3f-4279-8ac5-9bc46969c81f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>postTransaction('1783')</value>
      <webElementGuid>adfa8bc2-00ec-4307-944a-901e01e17234</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnCloseAccount</value>
      <webElementGuid>ebe525a0-9f14-477e-a977-cafe8be2283f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Close Account</value>
      <webElementGuid>60dfef9c-66b7-4b51-8783-0c55c64e62de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnCloseAccount&quot;)</value>
      <webElementGuid>f68f01a2-7ba1-4b42-a815-6a18ff7da922</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btnCloseAccount']</value>
      <webElementGuid>105cf1b2-b3b7-4e88-9c80-0ce39bbaaddc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='closed']/div/div[2]/div/button</value>
      <webElementGuid>16b5c793-0c3b-41a3-8a4d-908316681394</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/button</value>
      <webElementGuid>0ea1c8b9-62fc-4937-b751-54dd59328c87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'btnCloseAccount' and (text() = 'Close Account' or . = 'Close Account')]</value>
      <webElementGuid>e5b8e7c9-6ac6-481d-9d45-f124ea5a0e53</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
