<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Post</name>
   <tag></tag>
   <elementGuidId>9fc52552-14b2-4739-804b-8730571418b2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnPostDeposit</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btnPostDeposit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>93941946-1c3b-43aa-8f28-a7e9b548417f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a55757bf-9c62-4d80-91e9-17277bb4348e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-success</value>
      <webElementGuid>e7fc8186-25b7-44f5-82e8-f7127c4210d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>postTransaction('1')</value>
      <webElementGuid>3096a5b7-ed48-48b1-a32e-b21c93926fc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnPostDeposit</value>
      <webElementGuid>257f5fcd-8532-43b5-b39a-3afdf905d553</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Post</value>
      <webElementGuid>4d46ac23-eab2-4491-9879-10b1416cf45f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnPostDeposit&quot;)</value>
      <webElementGuid>7f3f887e-737c-48b7-a8db-702205667210</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btnPostDeposit']</value>
      <webElementGuid>51cd166d-6b0e-4791-964e-131b37cf92cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='deposit']/div/div[3]/div[2]/button</value>
      <webElementGuid>a216430a-5043-4026-b5b7-9ee481d55ccd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button</value>
      <webElementGuid>fc2d9a34-d4bf-4719-bc19-d77a82b72cb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'btnPostDeposit' and (text() = 'Post' or . = 'Post')]</value>
      <webElementGuid>6dcbc20b-24b9-426a-af4f-80d24d50b6c6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
