<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputtxtWithdrawAmount</name>
   <tag></tag>
   <elementGuidId>d0d797cb-b05a-46fe-817f-7b3f5d3ae24e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtWithdrawAmount</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtWithdrawAmount']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>804eb321-d7bb-4462-b070-2f53b8aac398</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>3f02d1f6-6152-46a9-b243-b5d1a9de180c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8f94faf3-1765-4252-9b02-f707b2cd83e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control text-center errors</value>
      <webElementGuid>7a6a4b6c-c016-4cec-8c16-e1a860918640</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtWithdrawAmount</value>
      <webElementGuid>d68c379a-4459-4456-8fd1-84c8bf2dcc0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtWithdrawAmount&quot;)</value>
      <webElementGuid>ffb95afe-8a40-4c9b-a121-8fc949278fab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtWithdrawAmount']</value>
      <webElementGuid>24365b94-4499-45f1-b9f1-f09b22ac1a60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='withdraw']/div/div[2]/div[4]/div/input</value>
      <webElementGuid>a4018077-e9b6-486b-a0af-dfda617dbfde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div[4]/div/input</value>
      <webElementGuid>315fc021-451b-4e90-be95-de5fe5bcd5f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'txtWithdrawAmount']</value>
      <webElementGuid>15fef570-2a75-4a02-bbd5-cab56f0780c2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
