<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputtxtDepositAmount</name>
   <tag></tag>
   <elementGuidId>305e1acf-9c3d-47f1-88e4-5ef22bb2945e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtDepositAmount</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtDepositAmount']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b09801e0-f72c-4370-8c97-99522744ed3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>9afbbb6d-ac46-47ad-a5fb-cc0c854772cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8312fca7-1cf6-44ff-abd3-f3dcb0d6500c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control text-center errors</value>
      <webElementGuid>2219ea1d-5b5f-4474-b1de-c632b66b8bc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtDepositAmount</value>
      <webElementGuid>8f88c4f3-8de5-4202-b25b-6f03df2f706d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtDepositAmount&quot;)</value>
      <webElementGuid>3bd7f42c-b345-4023-ac4b-b1605646a8a4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtDepositAmount']</value>
      <webElementGuid>4b65c54c-6e06-41d1-a67f-23c67f69361d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='deposit']/div/div[2]/div[3]/div/input</value>
      <webElementGuid>440e0531-2aee-4f05-9f73-77a1e825a36a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>ecad5286-252d-4adf-b99d-9f466c61e3b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'txtDepositAmount']</value>
      <webElementGuid>b0376943-6c68-4910-a661-55321c031e2c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
