<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_undefined_txtDepositEndBal</name>
   <tag></tag>
   <elementGuidId>5cf45817-e0b6-4027-bf0f-e68764dc2870</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtDepositEndBal']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#txtDepositEndBal</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ae33da3d-dae2-4186-b883-aeee4ed95ec0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>68c1aa3d-13d5-4fc2-9150-1f08ceb49c28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>87b11424-3b90-4aee-89e1-90cc9f745389</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control text-center</value>
      <webElementGuid>a023241a-be4c-4ce5-b57e-8823b917f010</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtDepositEndBal</value>
      <webElementGuid>050cef19-2dcf-4d5a-9434-52850a88587f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtDepositEndBal&quot;)</value>
      <webElementGuid>364f5627-e12b-4fcd-8c73-ba1a2d093592</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtDepositEndBal']</value>
      <webElementGuid>062f75fd-2c4a-45ad-8aa6-da95f5630baa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='deposit']/div/div[2]/div[4]/div/input</value>
      <webElementGuid>dfe66121-dc72-41f6-ab2c-27b97d12d806</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div[2]/div[4]/div/input</value>
      <webElementGuid>692f6fbe-e35a-4d99-bbc0-953a58be26e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'txtDepositEndBal']</value>
      <webElementGuid>cfb50c89-918c-4bcb-adf1-68d289572b5e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
