<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Date End_dtMEnd</name>
   <tag></tag>
   <elementGuidId>d9266ff4-3de4-4961-a41a-62d7aaf788fc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dtMEnd</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dtMEnd']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>dadf3c25-4fb3-48e0-89fa-554a5509b9c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>6bfdea94-1a8b-4919-9f06-e004e46bc55f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>date</value>
      <webElementGuid>c604fd4a-c40a-4143-8663-2f41663e6382</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>2999-01-01</value>
      <webElementGuid>dc2a7022-aaec-490e-8031-28fa114334f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control text-uppercase datepicker gb-border-bottom-fcs</value>
      <webElementGuid>6d8e5988-44b9-466c-90ad-5ba8a5ed6373</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dtMEnd</value>
      <webElementGuid>312da62c-4881-499e-ad61-fa0f5f6f337e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dtMEnd&quot;)</value>
      <webElementGuid>47f08750-352d-490e-a456-cacdaec67bd6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dtMEnd']</value>
      <webElementGuid>d95f286a-4e1d-45af-8384-da3712073d33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='datepicker4']/input)[3]</value>
      <webElementGuid>7b31dbb4-8788-43fe-9cf7-f43eddb787af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[4]/div/input</value>
      <webElementGuid>e67b7cdb-fb6b-46d7-9d7e-7f273f5e2536</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'date' and @id = 'dtMEnd']</value>
      <webElementGuid>4e5c4005-0662-4030-a826-e1b9a1976d1e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
