<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Date Start_dtMStart</name>
   <tag></tag>
   <elementGuidId>b45b8637-eaf6-4139-8086-84c965f46c22</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dtMStart</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dtMStart']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>446bcbaf-c668-4d03-9422-b1751bb30801</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>a7bc585a-8d99-4684-a036-1b127a8f1a63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>date</value>
      <webElementGuid>16058034-a927-43ef-b8bd-fc7f4d6811e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>2999-01-01</value>
      <webElementGuid>cf1e98e4-1dfc-431e-8599-d69b702a4bef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control text-uppercase datepicker gb-border-bottom-fcs</value>
      <webElementGuid>6dc3e0e1-e5ca-49d0-b5cb-62885acddd4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dtMStart</value>
      <webElementGuid>f54fcfea-2d66-473a-82e9-56af647a71c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dtMStart&quot;)</value>
      <webElementGuid>68dde882-a6ef-4c39-8787-f3df96444748</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dtMStart']</value>
      <webElementGuid>45550246-a680-4b3c-ba68-24c7295b3a59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='datepicker4']/input)[2]</value>
      <webElementGuid>d19121fb-ece4-4b82-a536-165b55987891</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[2]/div/input</value>
      <webElementGuid>0c2faba2-11d8-477f-bdd5-c5b7f266ddb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'date' and @id = 'dtMStart']</value>
      <webElementGuid>c9af247d-d290-404e-8e8d-13a861e921de</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
