<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Date Start_txtDTStartTranHistory</name>
   <tag></tag>
   <elementGuidId>46971cdb-8914-4cbf-9f83-f3e8ee62fc4e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtDTStartTranHistory</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtDTStartTranHistory']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#txtDTStartTranHistory</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5e0d5969-6d16-4024-aae2-a3760c4563aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>f19d1518-3377-4391-9156-112a52734807</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>date</value>
      <webElementGuid>c8fdadfb-a2c8-4c5b-a223-7d24d8eb507c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>2999-01-01</value>
      <webElementGuid>f511ef37-4b44-40df-8078-91e35397fcbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control text-uppercase datepicker gb-border-bottom-fcs</value>
      <webElementGuid>6e580ffb-cd3c-4ace-87e2-7a8c11e8c4a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtDTStartTranHistory</value>
      <webElementGuid>374c144b-cdb3-4485-a537-4e98ed7f964c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtDTStartTranHistory&quot;)</value>
      <webElementGuid>12286ea8-0bdc-4d3d-9380-fbe4823eaa7b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtDTStartTranHistory']</value>
      <webElementGuid>450afcbb-8e9b-476d-baf8-54f0fdfc7a36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='datepicker4']/input)[5]</value>
      <webElementGuid>436df890-6284-4d35-8707-54cf089e8942</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/div/div/div[2]/div/div[2]/div/input</value>
      <webElementGuid>39bf4956-80ae-41f8-9d77-5b62f748b4a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'date' and @id = 'txtDTStartTranHistory']</value>
      <webElementGuid>4e773739-413e-417c-8985-4d5698b02e53</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
