<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Date End_txtDTEndTranHistory</name>
   <tag></tag>
   <elementGuidId>b1dc85a4-22cb-43e5-abe7-6ccd9c8c45e6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtDTEndTranHistory</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtDTEndTranHistory']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#txtDTEndTranHistory</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0ee3c683-eed1-4235-b388-38ba7eb36c01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>6ef04138-376c-45a5-820a-fdb92b102c97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>date</value>
      <webElementGuid>94cb1fba-351d-44dc-bde5-90927c5607ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>2999-01-01</value>
      <webElementGuid>8ac3b962-5a3d-4bb7-849a-bac76c6468ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control text-uppercase datepicker gb-border-bottom-fcs</value>
      <webElementGuid>4fe20ba7-b448-4467-8dab-64183a7a1ea8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtDTEndTranHistory</value>
      <webElementGuid>a1296129-86c7-4a17-9f1e-57e13ca28724</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtDTEndTranHistory&quot;)</value>
      <webElementGuid>0f664589-8403-457c-85f0-f43c47bc905d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtDTEndTranHistory']</value>
      <webElementGuid>35b1211a-e537-49ed-879b-e3c5b61182dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='datepicker4']/input)[6]</value>
      <webElementGuid>009e6eb6-f017-4f69-963b-b70999fb048f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/div/div/div[3]/div/div[2]/div/input</value>
      <webElementGuid>e878f1f0-a81c-43df-ba6d-94a510774aa6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'date' and @id = 'txtDTEndTranHistory']</value>
      <webElementGuid>1ed8c5e1-ffc0-4c80-b649-2716c9153a38</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
