<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_LoanManagement</name>
   <tag></tag>
   <elementGuidId>05c5f539-4541-4f0f-8b57-fe6e9b95147e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='LoanManagement']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#LoanManagement</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3cee1014-7f6b-4e85-be16-3daf376fa3d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gb-hover-side confirmation-link</value>
      <webElementGuid>29afdcb1-6f98-45ec-9a5c-7739ce1cc7e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>LoanManagement</value>
      <webElementGuid>3b5e6537-04c5-4461-9534-424fd954d60f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>LoanManagement</value>
      <webElementGuid>6a9d4991-4f6b-46f7-9c8e-7c9cc84cef15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>return loadIframe('ifrm1', this.href);</value>
      <webElementGuid>47aea8f0-b30e-4b5f-8496-bf9d2582d0aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Loan
									Management</value>
      <webElementGuid>66da2a91-edff-483a-ab38-12043f7afdd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;LoanManagement&quot;)</value>
      <webElementGuid>eedfe800-1832-461e-94bf-8c699a06cb68</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='LoanManagement']</value>
      <webElementGuid>f8d94a7c-1d3f-4eed-acea-79ad5ce1f08d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sidebarLoan']/ul/li/a</value>
      <webElementGuid>e094460b-6151-46f0-8fb3-3fe4de436ad9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Loan
									Management')]</value>
      <webElementGuid>4afee8a3-4064-4b4d-8042-16604b543805</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'LoanManagement')]</value>
      <webElementGuid>5ab72228-82d0-4cbc-a0dc-f40161082fd2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/div/ul/li/a</value>
      <webElementGuid>3ccd84e5-42f5-49d3-8ff4-22939538a0d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'LoanManagement' and @id = 'LoanManagement' and (text() = 'Loan
									Management' or . = 'Loan
									Management')]</value>
      <webElementGuid>2480d61d-3443-4f8e-963a-bd25fe4b8e75</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
