<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_This Record is Rejected</name>
   <tag></tag>
   <elementGuidId>498798a2-94bc-4e11-9a30-47341fc34952</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#swal2-content</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='swal2-content']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;This Record is Rejected!&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>fd4ad016-705f-4b91-9a57-0b702371bb92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>swal2-content</value>
      <webElementGuid>0fb2905f-955e-4659-832b-023ac4dbec34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>This Record is Rejected!</value>
      <webElementGuid>a1269558-85a3-4171-b007-58d6c6785650</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;swal2-content&quot;)</value>
      <webElementGuid>e65aee4e-56a6-487e-8921-e2cc082afab6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='swal2-content']</value>
      <webElementGuid>01f05eb1-16f2-40a9-98d3-9aef6218c585</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[1]/following::div[2]</value>
      <webElementGuid>f1724ad9-2ac8-4a95-a6eb-3c4ad5703c00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Message'])[1]/following::div[2]</value>
      <webElementGuid>d08dd8bd-4729-44ac-b07f-4c487ed4750d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OK'])[1]/preceding::div[4]</value>
      <webElementGuid>7c5bc4f3-03be-45d5-b02e-b1345ad0b208</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[2]/preceding::div[4]</value>
      <webElementGuid>ead5767a-096f-40c6-9d3e-bd811b91933a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='This Record is Rejected!']/parent::*</value>
      <webElementGuid>e74e5a6f-ac19-48ab-8417-d5f3469d4dc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div[2]/div</value>
      <webElementGuid>b0b1e1a4-add4-4475-98a5-a4e986b04e82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'swal2-content' and (text() = 'This Record is Rejected!' or . = 'This Record is Rejected!')]</value>
      <webElementGuid>d1cf0841-e819-4bbe-81cc-631742bbb5d2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
