<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Expense_txtrowExpenseAmount3</name>
   <tag></tag>
   <elementGuidId>dcb46866-4f4e-4741-9839-2a382c63f7a2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtrowExpenseAmount3']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#txtrowExpenseAmount3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#txtrowExpenseAmount3</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>46cbb8f8-6214-4d9d-b70f-1bd220ee1dbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>78afd927-427c-4b5a-9b23-0431f90cb542</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b508549f-fab5-4bf4-bdd6-a835d314ca70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control required gb-border-fcs</value>
      <webElementGuid>8f83ac96-9c21-49a0-8b90-c041a1fca57a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtrowExpenseAmount3</value>
      <webElementGuid>2e40a205-581a-4ec2-8295-3e9097cfb7a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtrowExpenseAmount3&quot;)</value>
      <webElementGuid>27a2c05c-670c-41ad-9b22-3ccd3f606073</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtrowExpenseAmount3']</value>
      <webElementGuid>69dde050-0910-4650-8b54-690fa1a3db2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='inputRow2']/div[2]/div/div/input)[2]</value>
      <webElementGuid>96aa35a6-5adf-40fe-b285-edb0eed5020a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div[5]/div[2]/div/div[2]/div/div/input</value>
      <webElementGuid>acda61c1-9362-41a4-a906-ad92e4aa82a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'txtrowExpenseAmount3']</value>
      <webElementGuid>aada9a24-72ce-4851-802f-f47ecc8d73c4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
