<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_-- Select --EmploymentSalariesIncome from businessInheritanceOthersProceeds from investmentRemittancesRetirementPension</name>
   <tag></tag>
   <elementGuidId>0e2bd1a7-1c9d-4e8b-be51-06a7a1a458e1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='cboincome2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cboincome2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#cboincome2</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>d8de3cb0-54c0-49e3-8b66-2ebf516558a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-select required gb-border-fcs</value>
      <webElementGuid>391c2d52-46bb-4c01-b118-7475e74b5851</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cboincome2</value>
      <webElementGuid>f344439b-146f-450f-801d-ca750d03ea44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-- Select --Employment/SalariesIncome from businessInheritanceOthersProceeds from investmentRemittancesRetirement/Pension</value>
      <webElementGuid>a30c1f44-dcd2-40e2-9737-6dbc32aed671</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cboincome2&quot;)</value>
      <webElementGuid>f29c2aa2-fc04-484a-8e5f-46bd415ceaf8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='cboincome2']</value>
      <webElementGuid>02836282-3280-4cb9-9922-a07dfbb9b0bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='inputRow']/div/div/select)[2]</value>
      <webElementGuid>5e890c62-0cd5-4732-bc6f-9921a7012009</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Income:'])[1]/following::select[2]</value>
      <webElementGuid>5f63f3ad-44d4-4966-b316-1c07d9a3d6e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Working Capital:'])[1]/following::select[2]</value>
      <webElementGuid>763e3e92-1987-4895-bc7d-d59e69d71101</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total:'])[1]/preceding::select[1]</value>
      <webElementGuid>b6269c7c-fd84-4ecc-b835-a4df8095aeec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div/select</value>
      <webElementGuid>ff6889c2-c3ee-496b-806f-af03cfea9ed8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'cboincome2' and (text() = '-- Select --Employment/SalariesIncome from businessInheritanceOthersProceeds from investmentRemittancesRetirement/Pension' or . = '-- Select --Employment/SalariesIncome from businessInheritanceOthersProceeds from investmentRemittancesRetirement/Pension')]</value>
      <webElementGuid>76955c96-010a-4334-9a8c-d5bf3bea165e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
