<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Select --FoodWaterElectricityEducationTuitionSalary</name>
   <tag></tag>
   <elementGuidId>80bd2d59-1c3a-435a-8d16-7ceed9fcab56</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='cborowExpense4']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cborowExpense4</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#cborowExpense4</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>1d83dd9b-9553-4546-94ae-62cfdcab0feb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-select required gb-border-fcs</value>
      <webElementGuid>1ca23044-53c1-4f1d-983d-b38775047621</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cborowExpense4</value>
      <webElementGuid>55c38869-891b-412b-ab9d-936c591a51a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-- Select --FoodWaterElectricityEducation/TuitionSalary of  WorkersAllowances and TransportationTransportation/GasolineClothingEntertainment/RecreationMedical ExpensesAmortization of  other loansHouse rentalOthers</value>
      <webElementGuid>961a3cf4-6ba5-4ab5-8567-a88badcaaa0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cborowExpense4&quot;)</value>
      <webElementGuid>f5f3e417-12be-4e68-8f9e-36fe07fb37a8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='cborowExpense4']</value>
      <webElementGuid>3817b760-0a43-45f4-8382-7ff9a4b6b7a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='inputRow2']/div/div/select)[3]</value>
      <webElementGuid>858d8155-a39e-4a0f-b401-93f8cd6f34d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Expense:'])[1]/following::select[3]</value>
      <webElementGuid>33f75830-ee21-4142-ab8c-a6bbb3dd8475</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total:'])[1]/following::select[3]</value>
      <webElementGuid>8cc654de-a0a1-4fcb-9b08-acefc2575cb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total:'])[2]/preceding::select[1]</value>
      <webElementGuid>eefa539f-e980-454a-bb96-d76919e962d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[3]/div/div/div/select</value>
      <webElementGuid>dd3f5065-0fdf-406e-b06b-45a9b1029d66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'cborowExpense4' and (text() = '-- Select --FoodWaterElectricityEducation/TuitionSalary of  WorkersAllowances and TransportationTransportation/GasolineClothingEntertainment/RecreationMedical ExpensesAmortization of  other loansHouse rentalOthers' or . = '-- Select --FoodWaterElectricityEducation/TuitionSalary of  WorkersAllowances and TransportationTransportation/GasolineClothingEntertainment/RecreationMedical ExpensesAmortization of  other loansHouse rentalOthers')]</value>
      <webElementGuid>8c3df9ea-8e59-4d83-b91a-b61568cc4bea</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
