<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Draft_mdi mdi-pencil-outline</name>
   <tag></tag>
   <elementGuidId>5dcd0110-8610-4156-b557-4f0ca2838057</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tbody[@id='tblDraftBody']/tr/td[6]/a/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.mdi.mdi-pencil-outline</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=row[name=&quot;785 Test Draft 03/20/2024 zcresurrecion Draft 󰲶 󰆴&quot;i] >> internal:attr=[title=&quot;Continue encoding&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>743f1065-cc63-4a4a-b0b8-0e1ce0e2f895</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mdi mdi-pencil-outline</value>
      <webElementGuid>a57e4527-5f36-4e7b-b90a-96f554cbf6eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tblDraftBody&quot;)/tr[@class=&quot;odd&quot;]/td[@class=&quot;td-actions&quot;]/a[@class=&quot;action-icon btn&quot;]/i[@class=&quot;mdi mdi-pencil-outline&quot;]</value>
      <webElementGuid>0829c3c0-fe91-45bf-8ab8-ab02b9742f13</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='tblDraftBody']/tr/td[6]/a/i</value>
      <webElementGuid>fdefc3fe-71ab-41ca-aa2c-0b855b4afb48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[6]/a/i</value>
      <webElementGuid>8dd4f0c8-85a3-488f-a92e-09b0b6c7ee83</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
