<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_UserManagement</name>
   <tag></tag>
   <elementGuidId>f0b7530c-fee2-4f05-90f1-fc1108b88a37</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Usermanagement</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='Usermanagement']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;User Management&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>57a96127-4f87-41a1-a575-615102971f9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gb-hover-side confirmation-link</value>
      <webElementGuid>41c19a33-3145-4cc5-b62e-3c6977c21905</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>Usermanagement</value>
      <webElementGuid>ac67403c-f222-4ae4-8101-9853a33bf653</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Usermanagement</value>
      <webElementGuid>5b7f09a5-a448-4b9b-a394-4a9aaf8b7305</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>return loadIframe('ifrm1', this.href);</value>
      <webElementGuid>e3063e33-999d-4866-9574-e31ecb315483</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>User
									Management</value>
      <webElementGuid>59267776-9d7d-4c53-9d0a-179eb38220f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Usermanagement&quot;)</value>
      <webElementGuid>56d6109f-94dd-407d-b626-498e88e3cba4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='Usermanagement']</value>
      <webElementGuid>68ff1b95-83f7-4894-9ada-77bf685d6648</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sidebarAdmin']/ul/li/a</value>
      <webElementGuid>3d7a0ed6-0c40-4e7c-8a8c-105efd2f189e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'User
									Management')]</value>
      <webElementGuid>c2eba645-cd00-4a74-ae85-caed31d0dc4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Admin'])[1]/following::a[1]</value>
      <webElementGuid>fc73a5ca-1108-4a2a-bb12-af09ae941347</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'Usermanagement')]</value>
      <webElementGuid>26e194c6-a5e2-497b-a49d-e3598f4749d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[12]/div/ul/li/a</value>
      <webElementGuid>4a0666f9-8d38-4638-ab7d-d984d0805c43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'Usermanagement' and @id = 'Usermanagement' and (text() = 'User
									Management' or . = 'User
									Management')]</value>
      <webElementGuid>d6fd53a5-7035-4583-b026-06a462075ce7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
