<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_--      Select      --Account Office_5f278f</name>
   <tag></tag>
   <elementGuidId>2e8276e7-8f24-44d7-a215-68c00cd69285</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cboAccessRole</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='cboAccessRole']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#cboAccessRole</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>486d0b09-ee5c-42c3-a500-aa9a5ecaf61a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-select</value>
      <webElementGuid>42fe1524-3906-4b07-9baa-8b2953e0a28e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cboAccessRole</value>
      <webElementGuid>af8259dd-1be7-4e95-a1a6-21a1418b48c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>--      Select      --Account OfficerAdministratorAgent SupervisorApps AdminArea ManagerAuditBookkeeperCashier-in-ChargeCluster AccountantCluster HeadCluster IT HeadCMIT OperatorInformation Security OfficerIT ManagerRegional AccountantRegional DirectorRegional ITResignedSecurity AdminSr. Operation DirectorTellerUnit Manager</value>
      <webElementGuid>99313014-03cf-47f1-b818-9f15604369c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cboAccessRole&quot;)</value>
      <webElementGuid>38116d56-5d6a-4c51-b9c2-d96452a397be</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='cboAccessRole']</value>
      <webElementGuid>2dc760eb-9b60-469d-af93-8c6dfcc4c563</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmUserInfo']/div[10]/div[2]/select</value>
      <webElementGuid>1378adbc-88d0-4578-95bc-f0ac8d8b7c9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Access Role'])[1]/following::select[1]</value>
      <webElementGuid>da92f9b5-9360-4b06-b80f-014fd323980c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Office'])[2]/following::select[2]</value>
      <webElementGuid>ad459d08-8356-483b-a5e4-797af9b8f0c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status'])[3]/preceding::select[1]</value>
      <webElementGuid>8e73d8cf-f0f8-4fd5-b3d9-5a5e46218e0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Close'])[1]/preceding::select[1]</value>
      <webElementGuid>e0c3a616-cf0a-459c-b24b-3d4d2f8c0349</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/select</value>
      <webElementGuid>96088c50-15cd-4a19-a6f9-eb72451aabe9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'cboAccessRole' and (text() = '--      Select      --Account OfficerAdministratorAgent SupervisorApps AdminArea ManagerAuditBookkeeperCashier-in-ChargeCluster AccountantCluster HeadCluster IT HeadCMIT OperatorInformation Security OfficerIT ManagerRegional AccountantRegional DirectorRegional ITResignedSecurity AdminSr. Operation DirectorTellerUnit Manager' or . = '--      Select      --Account OfficerAdministratorAgent SupervisorApps AdminArea ManagerAuditBookkeeperCashier-in-ChargeCluster AccountantCluster HeadCluster IT HeadCMIT OperatorInformation Security OfficerIT ManagerRegional AccountantRegional DirectorRegional ITResignedSecurity AdminSr. Operation DirectorTellerUnit Manager')]</value>
      <webElementGuid>2d673421-c668-4809-a4f9-43de8b0516ec</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
