<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_-- Select --Area One 505Batangas 1Bg_d2c5c8</name>
   <tag></tag>
   <elementGuidId>601c6ff3-3510-4b52-b55e-4fd2dd743c7c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cboBranch</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='cboBranch']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#cboBranch</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>b6dfe516-7f75-4fae-82d9-aa154d4c7705</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cboBranch</value>
      <webElementGuid>2332de8d-6ae3-419f-bd62-8a1d6faba025</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-select</value>
      <webElementGuid>6486c181-805c-457d-bbcd-3ed9bb0bf7c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-- Select --Area One 505Batangas 1BgcBukidCandelaria 1Cavite 1Cavite 2Ilocos 1Ilocos 3Laguna 1Laguna 2Laguna 3Ncr 1Tarlac</value>
      <webElementGuid>f0243445-5c13-4346-8f14-ee7560e86ed9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cboBranch&quot;)</value>
      <webElementGuid>9f618a6f-161a-4a3f-979b-dd179742ba09</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='cboBranch']</value>
      <webElementGuid>9559c504-c560-422e-9d00-fddb3dc1662c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmUserInfo']/div[8]/div/select</value>
      <webElementGuid>c1f9bf5a-cd88-44bf-8a59-9c43dc0c77ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Office'])[2]/following::select[1]</value>
      <webElementGuid>30771e7a-06b2-4376-b265-3c945f682f3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact'])[1]/following::select[1]</value>
      <webElementGuid>30ab4923-8ea3-4349-bf2c-97bb35e669eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Access Role'])[1]/preceding::select[1]</value>
      <webElementGuid>7336b2f7-f64e-4bd1-8eae-b8d44fc5542d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status'])[3]/preceding::select[2]</value>
      <webElementGuid>bbb108c2-048e-4df2-880a-c69f0e48e601</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/select</value>
      <webElementGuid>282ec278-e3fe-4bc2-80ae-94d25831891a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'cboBranch' and (text() = '-- Select --Area One 505Batangas 1BgcBukidCandelaria 1Cavite 1Cavite 2Ilocos 1Ilocos 3Laguna 1Laguna 2Laguna 3Ncr 1Tarlac' or . = '-- Select --Area One 505Batangas 1BgcBukidCandelaria 1Cavite 1Cavite 2Ilocos 1Ilocos 3Laguna 1Laguna 2Laguna 3Ncr 1Tarlac')]</value>
      <webElementGuid>16293ed6-56e3-4526-833d-1f6e5217d5f0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
