<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Dayap 1_ri-close-line</name>
   <tag></tag>
   <elementGuidId>c6e791f0-d160-418d-b592-ff585fdc925b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tbody[@id='tblBodyAmendmentList']/tr/td[7]/a[2]/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#tblBodyAmendmentList > tr.odd > td.text-center > a.action-icon > i.ri-close-line</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[title=&quot;Disapprove Amendment &quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>d34839ee-c261-4cc4-b690-b1012c295f95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ri-close-line </value>
      <webElementGuid>2af75dec-b2a5-4bd8-865c-b701bd5fbc75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tblBodyAmendmentList&quot;)/tr[@class=&quot;odd&quot;]/td[@class=&quot;text-center&quot;]/a[@class=&quot;action-icon&quot;]/i[@class=&quot;ri-close-line&quot;]</value>
      <webElementGuid>3bbd69de-9f62-4130-98a2-4e4be23fba73</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='tblBodyAmendmentList']/tr/td[7]/a[2]/i</value>
      <webElementGuid>53407244-8aa8-4cd2-ae76-ee275f0649f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[7]/a[2]/i</value>
      <webElementGuid>6f306e27-9620-421d-80ed-54d0983c3500</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
