<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Please Enterthe PR Number_txtPRno</name>
   <tag></tag>
   <elementGuidId>fcd5ed5b-458d-4df2-97fe-059bbb57480f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtPRno</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtPRno']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#txtPRno</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ad9d9355-b4ce-4330-b1e0-d3141db16bac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>74a18e58-d8b9-4387-a34b-bd72716268a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9147e1f4-49dc-4b6d-b201-bf72f8251dfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>7385365f-166d-4bb4-8e83-d225f8ee3a53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtPRno</value>
      <webElementGuid>d061fe4b-6aec-40d2-b14d-8fc956bcbf96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtPRno&quot;)</value>
      <webElementGuid>5c3152f3-bac8-4607-9448-a1b4feee52b6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtPRno']</value>
      <webElementGuid>477f3cd2-37a7-4c00-878f-eda07ab9e376</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='PRNOmodal']/div/div/div[2]/div/div/div/input</value>
      <webElementGuid>b03e59d1-9942-4e80-8c03-8fd0fecab29f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/div/div/input</value>
      <webElementGuid>0c1c2133-77da-4cd7-bab6-c1ede2653a66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'txtPRno']</value>
      <webElementGuid>a7275f62-347e-4463-9649-60888928b083</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
