<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputtxtCoName2</name>
   <tag></tag>
   <elementGuidId>8018a74d-ab8b-40e0-9d05-8b60efe0f81c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtCoName2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#txtCoName2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>91c0e2e8-d82b-49ca-a1c6-9cbcdcbc9174</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>f45155f8-1461-46ce-b446-b49817fd4d9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>627573a6-e158-43f1-b949-b2f55b4a3ebc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control required text-capitalize gb-border-fcs</value>
      <webElementGuid>4e01690c-65cb-4c1f-8576-751fbcd9bda4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtCoName2</value>
      <webElementGuid>703859d8-4430-41e7-8a2b-3734e7cc5d47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtCoName2&quot;)</value>
      <webElementGuid>0a91c9ca-e31e-4b30-ba9f-0846b49e0b9e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtCoName2']</value>
      <webElementGuid>32437104-aaf6-4cbd-bb77-5d046a5c8465</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='row2']/div/div/div[5]/div/input</value>
      <webElementGuid>ecb4112b-f9ac-4f20-bb87-3cc0098db021</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/input</value>
      <webElementGuid>36d07b0e-5de4-4dad-b5c4-80cae6642178</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'txtCoName2']</value>
      <webElementGuid>343c71ab-d788-4f6a-bab9-890b08dc583c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
