<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputtxtTotalExpense</name>
   <tag></tag>
   <elementGuidId>1925e2d1-45b7-45fd-96d5-5fca2a7f27c8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtTotalExpense']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#txtTotalExpense</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>db3caafc-4d86-463a-a3e4-2f2abd455cae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>c5353e73-efb2-43eb-83bb-d5c0d7db0552</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5fa94c37-a91e-4f09-970e-4bcf27641472</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control computeCashflow gb-border-fcs keep-disabled font-12</value>
      <webElementGuid>54e969d0-c0a2-468f-a307-270f9da1f955</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtTotalExpense</value>
      <webElementGuid>6d3d329f-1556-4a14-9595-8e6e6ba72197</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtTotalExpense&quot;)</value>
      <webElementGuid>4ae03711-0b6e-443c-9cb6-f1395d23a188</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtTotalExpense']</value>
      <webElementGuid>7e55d4ad-77be-4716-a35f-3ca3657c93cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cashflow1']/div/div/div[3]/div/div[2]/div/div/div/div/div[6]/div[3]/div/input</value>
      <webElementGuid>5328397a-a60d-4cc0-80d7-727c007130ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[3]/div/input</value>
      <webElementGuid>ca261d21-cfc7-4b28-950d-17e6869c512d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'txtTotalExpense']</value>
      <webElementGuid>832e0689-7afc-4ad2-981e-ccee3451b473</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
