<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputtxtCurrentLoan</name>
   <tag></tag>
   <elementGuidId>8a4022fc-959f-4076-ad14-8f893af13012</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtCurrentLoan']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#txtCurrentLoan</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0ef7911f-ab35-464e-ae02-44593eb32447</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>fefe9168-9a20-420a-9fc5-fb403d76e181</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e83cffb5-bf07-4d55-8fe0-71b69a2c218d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control keep-disabled</value>
      <webElementGuid>3d366d19-c9fa-4607-9de9-e58fe947eb62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtCurrentLoan</value>
      <webElementGuid>9a3f3f3c-923c-4067-967c-7307c52ea84a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtCurrentLoan&quot;)</value>
      <webElementGuid>34327957-3288-41bd-9e00-c8fbc6e18912</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtCurrentLoan']</value>
      <webElementGuid>1a37f6dd-f9f8-4ab7-9a73-90a7ba448902</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cashflow1']/div/div[3]/div[5]/div[2]/div/input</value>
      <webElementGuid>fb074a68-50ac-43a8-af7f-f6e4afa0ebd2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[5]/div[2]/div/input</value>
      <webElementGuid>8e241c76-0d7c-4333-8173-6f552978f98b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'txtCurrentLoan']</value>
      <webElementGuid>2515c891-518c-4e69-95bd-8148f6b4116b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
