<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_-- Select --SpouseSonDaughterMotherF_ba9097</name>
   <tag></tag>
   <elementGuidId>de93e592-0c44-4b99-a0f0-1c33f9ebfa1b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='cboCoRelationship2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cboCoRelationship2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>f42aacc3-fc02-4877-a30a-c4d528a9f689</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-select required gb-border-fcs</value>
      <webElementGuid>5efa28d8-3db5-4f8d-b8d8-5c675359e658</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cboCoRelationship2</value>
      <webElementGuid>820b8007-ef35-4af9-8f13-65e4834a2f69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-- Select --SpouseSonDaughterMotherFatherGrandmotherGrandfatherCousinFriendBrotherSister</value>
      <webElementGuid>92cdaa82-e292-4a29-8a65-61637fca22b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cboCoRelationship2&quot;)</value>
      <webElementGuid>0c2b1fe9-d72b-4806-a8e1-50ecac38519d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='cboCoRelationship2']</value>
      <webElementGuid>bb5d2d5c-d55b-4dab-a3bf-f6c555e4ffb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='row2']/div[2]/div/div[2]/div/select</value>
      <webElementGuid>0abf9008-c7eb-4811-93f0-2d12c4c07918</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/div/div[2]/div/select</value>
      <webElementGuid>6d98aae5-2665-4c38-a447-a65acbb045f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'cboCoRelationship2' and (text() = '-- Select --SpouseSonDaughterMotherFatherGrandmotherGrandfatherCousinFriendBrotherSister' or . = '-- Select --SpouseSonDaughterMotherFatherGrandmotherGrandfatherCousinFriendBrotherSister')]</value>
      <webElementGuid>d3ae056d-d2b0-4973-a164-e03b2985bd43</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
