<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_-- Select --EmploymentSalariesIncome_ce4e89_1</name>
   <tag></tag>
   <elementGuidId>a2325f3c-20c1-47e1-8d5f-36b15c76ef75</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='cboincome2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cboincome2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>2c01a429-5ce5-4837-8c88-9f656df4020e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-select required gb-border-fcs</value>
      <webElementGuid>b1d36561-7efc-4de3-86c7-4c64705f84e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cboincome2</value>
      <webElementGuid>7687de74-5298-44c8-ab8d-e66cf5b51de1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-- Select --Employment/SalariesIncome from businessInheritanceOthersProceeds from investmentRemittancesRetirement/Pension</value>
      <webElementGuid>3224e94d-6eb4-4b99-ac64-9f2443b59ece</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cboincome2&quot;)</value>
      <webElementGuid>91443fd9-b3f6-4f94-bc57-d31ca29839b9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='cboincome2']</value>
      <webElementGuid>846e6681-8f0f-41a9-8a81-10b6f5ba1c84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='inputRow']/div/div/select)[2]</value>
      <webElementGuid>b3d54490-e388-41ef-b96f-a63bc0689729</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div/select</value>
      <webElementGuid>f1fe9e81-e36a-4da8-93c8-70fe435c628b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'cboincome2' and (text() = '-- Select --Employment/SalariesIncome from businessInheritanceOthersProceeds from investmentRemittancesRetirement/Pension' or . = '-- Select --Employment/SalariesIncome from businessInheritanceOthersProceeds from investmentRemittancesRetirement/Pension')]</value>
      <webElementGuid>3f94c797-10e0-45bc-8e48-5cb4057f472d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
