<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Capital-Build Up_inputField_3</name>
   <tag></tag>
   <elementGuidId>e91f0d22-5f44-4e14-ac45-c8b7d0f20524</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#inputField_3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='inputField_3']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>46b73126-e632-4bbd-a1b2-b25ebebd1aca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5c06162d-7219-44af-9f53-a2d3cfa899f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control gb-border-fcs sum</value>
      <webElementGuid>5e4ba3da-67ee-4764-873b-4a54ebda2223</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>d6355196-6304-482e-8553-135f472b4443</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inputField_3</value>
      <webElementGuid>7cb399f2-771e-4aca-89e0-08788ebb43dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>bdb3dcb2-bd17-4f90-8af6-2336ecd43cfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inputField_3&quot;)</value>
      <webElementGuid>39f7080d-8369-40d3-bb0b-b55b01d4c967</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='inputField_3']</value>
      <webElementGuid>d3dbe5fd-16b7-4c8d-a39f-d4252c12f3b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='PaymentDetailsTbody']/tr[3]/td[10]/input</value>
      <webElementGuid>73cf802e-8687-4cf8-8deb-52744b2c65f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[10]/input</value>
      <webElementGuid>7efbeb65-4ae2-4f6a-b858-27cf9d9ab94c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'inputField_3']</value>
      <webElementGuid>528388b3-52bf-4507-b4fc-8748af882cb8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
