<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_AGRI LOAN_inputField_2</name>
   <tag></tag>
   <elementGuidId>481c573e-bf0a-4885-9f41-dfaf0a6eb7be</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#inputField_2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='inputField_2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e42caaa4-8627-44b3-b5c3-37eeace12874</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3e22370f-1ea1-40d8-a418-b459081ceeaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control gb-border-fcs sum</value>
      <webElementGuid>b0859447-fe6e-46c4-b795-c96cc4aff86f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>2ad09295-7335-4060-a0ba-4dee315314c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inputField_2</value>
      <webElementGuid>83d92ae1-ccc8-4f4e-8fa4-c2dfd77d2fef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>79d25c8d-f9e1-4552-834a-f52d9f87e4a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inputField_2&quot;)</value>
      <webElementGuid>08e3137b-d3b1-42bf-8a42-70c08909c97f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='inputField_2']</value>
      <webElementGuid>ec99c9ad-4e40-4dca-ba52-71938f4e0364</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='PaymentDetailsTbody']/tr[2]/td[10]/input</value>
      <webElementGuid>f565e7b9-392d-4676-8f0e-5334040485ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[10]/input</value>
      <webElementGuid>5ea7c068-0cbe-4c28-8934-689cf4b03fcc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'inputField_2']</value>
      <webElementGuid>fe369579-2e2f-4c17-811d-900372d41140</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
