<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Total Due_txtTotalDue</name>
   <tag></tag>
   <elementGuidId>33ad0871-1bd9-4387-b8e6-449b9c519c88</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtTotalDue']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#txtTotalDue</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e1eef694-cfe2-4fd4-abf8-51ff1a232ed0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>99ad49bf-5458-4a9a-b87f-09e298c162ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d8694aea-2271-4a52-8c2b-f2e59e0e494a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control gb-border-bottom-fcs</value>
      <webElementGuid>aba42136-7918-4b86-b1e3-847256837593</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtTotalDue</value>
      <webElementGuid>e396e556-00ff-40a8-8031-a452877b499f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtTotalDue&quot;)</value>
      <webElementGuid>8bc3624c-0e34-4e0a-afe1-f5c9879199cd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtTotalDue']</value>
      <webElementGuid>389d0d40-03f9-453b-8433-19949457c844</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='body']/div/div[4]/div/div/div/div[2]/div[2]/div[2]/div[2]/div/div/div/div[2]/input</value>
      <webElementGuid>196d8219-612b-4a28-b54f-c7ddf4795208</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>4392ae1a-e575-47c8-b3ac-718cdcaa65fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'txtTotalDue']</value>
      <webElementGuid>c5d76ea1-1ce3-4fa9-821e-3e4e0ef11f67</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
