<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_MBA PREMIUM_inputField_1</name>
   <tag></tag>
   <elementGuidId>0912c592-6e80-4437-9607-5690fe378a05</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#inputField_1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='inputField_1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c6b27d11-c84e-4fc0-ae95-fd91338ed21b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>132bd667-10f4-4498-92f3-3e2b36ca0ed8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control gb-border-fcs sum</value>
      <webElementGuid>a945a25f-3b82-4acc-a6ad-aa5915098063</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>f98a04c5-2c09-477e-8a21-b80c07b53042</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inputField_1</value>
      <webElementGuid>e0c61f06-7b13-46a2-ac64-c4d3d4bf145f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>6965eea0-0866-42c2-9616-cf70f1432151</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inputField_1&quot;)</value>
      <webElementGuid>915ee0b7-ae83-4a74-842e-904882c54d0c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='inputField_1']</value>
      <webElementGuid>09e32ac7-8812-4be8-ba74-7278d7ad5388</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='PaymentDetailsTbody']/tr/td[10]/input</value>
      <webElementGuid>765c3640-359b-4442-af8d-0760b74e711f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/table/tbody/tr/td[10]/input</value>
      <webElementGuid>03fc2ade-6b9a-4661-a891-5ab8d43ca2b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'inputField_1']</value>
      <webElementGuid>d3581607-49dc-41a8-bc2d-ef166aed86e6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
