<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Total_txtTotalSingleDetails</name>
   <tag></tag>
   <elementGuidId>3a3b2536-f981-4739-a590-c691e28e0748</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtTotalSingleDetails</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtTotalSingleDetails']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>391a0bf7-aa88-4a0d-8a2b-4313a4a7015d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>fa186759-2d53-49d2-964f-5018dfa43993</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b4250a86-c15b-4669-a961-2dd85415e54a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>0c7637e5-e0d2-4607-9f41-8fddcbab15e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtTotalSingleDetails</value>
      <webElementGuid>7cb9933c-2407-4ce6-a0ef-01ab60c89318</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtTotalSingleDetails&quot;)</value>
      <webElementGuid>48865a2c-c3f0-426b-aa21-1f8d2a1095e3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtTotalSingleDetails']</value>
      <webElementGuid>f27913f0-556d-4cbc-b697-cb7d3ab1686b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modalPaymentDetials']/div/div/div[2]/div[2]/div/div/div/div/div[3]/input</value>
      <webElementGuid>7a2704d7-4afd-4e10-b7f5-c3a4a1977540</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div[3]/input</value>
      <webElementGuid>d2548ddd-571a-4b68-95f3-5f6f58fdad58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'txtTotalSingleDetails']</value>
      <webElementGuid>1179c42d-ca65-44cc-b2d8-1619b4d87b28</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
