<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Contact Number_txtcontactNo</name>
   <tag></tag>
   <elementGuidId>9376a45a-d3ff-4a1c-b6b5-2b5bbb00476e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtcontactNo']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#txtcontactNo</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>17c2822f-eea3-48e2-951f-7fddd07fd5f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>815f3daa-134e-437d-81d7-0c5ef5a5adf3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1380f923-5d44-40df-b3df-fa99f144846b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control gb-border-bottom-fcs font-11</value>
      <webElementGuid>049199a1-1b71-47bd-a269-896b2354cd88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtcontactNo</value>
      <webElementGuid>53a2725c-2646-4faf-b590-15448e908f60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtcontactNo&quot;)</value>
      <webElementGuid>567c8acb-1533-4c62-a1d3-03da365617ac</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtcontactNo']</value>
      <webElementGuid>e594da61-acf9-470f-b2a7-1b4f2eac7844</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='body']/div/div[4]/div/div/div/div[2]/div/div/div[4]/div[2]/div/input</value>
      <webElementGuid>6c2ecfd8-b5a6-4507-97db-d4c140d9f319</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div/input</value>
      <webElementGuid>30e55d9a-24b9-4332-9057-2a0305548998</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'txtcontactNo']</value>
      <webElementGuid>7fcad633-32e0-4763-b83c-75ced175665a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
