<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_No data available in table</name>
   <tag></tag>
   <elementGuidId>1c8ce432-24ea-42b3-8943-87cc19361461</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tbody[@id='LoanManagementBody']/tr/td</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>td.dataTables_empty</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>0c6dfa6b-7713-4866-80d0-f70a22f1ed3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>valign</name>
      <type>Main</type>
      <value>top</value>
      <webElementGuid>bab8edab-7127-4ffd-90e6-2ef36b2fdeb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>colspan</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>039deb4e-3c24-4bcb-8c13-48ac29a3ed48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dataTables_empty</value>
      <webElementGuid>9bdcff2b-ef06-4e52-80cf-56e6ac58ad2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>No data available in table</value>
      <webElementGuid>418ce7ad-c857-4cd3-b20f-857621f00bf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;LoanManagementBody&quot;)/tr[@class=&quot;odd&quot;]/td[@class=&quot;dataTables_empty&quot;]</value>
      <webElementGuid>026b66d5-4837-4901-aa63-567c2f570257</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='LoanManagementBody']/tr/td</value>
      <webElementGuid>2cb1e5f9-63a7-4275-bc74-aaa634e19904</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td</value>
      <webElementGuid>9d651e58-96a7-43fe-9349-6a02de9101be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'No data available in table' or . = 'No data available in table')]</value>
      <webElementGuid>5d63467d-f3e5-42ea-a3f5-18a31a20391e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
