<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Approval_view_btn</name>
   <tag></tag>
   <elementGuidId>abc0430d-9187-4be7-801f-8929867a5e85</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tbody[@id='tblBodyNewClientList']/tr/td[8]/a[2]/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.mdi.mdi-open-in-new</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[title=&quot;Display Client Details&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>f9244153-501d-48e3-8c68-76ba817701c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mdi mdi-open-in-new</value>
      <webElementGuid>cfdd50cf-508e-45be-9a62-7d78ec5b0816</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tblBodyNewClientList&quot;)/tr[@class=&quot;odd&quot;]/td[@class=&quot;text-center&quot;]/a[@class=&quot;action-icon&quot;]/i[@class=&quot;mdi mdi-open-in-new&quot;]</value>
      <webElementGuid>360c40a7-0ef2-4a95-a355-60588c373db0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='tblBodyNewClientList']/tr/td[8]/a[2]/i</value>
      <webElementGuid>c111683a-fcf4-4986-8417-8345c7a5aa29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[8]/a[2]/i</value>
      <webElementGuid>52b5a8f0-d83e-4dba-9157-f1f1058644b1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
