<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_LoanApproval</name>
   <tag></tag>
   <elementGuidId>ccd7ddd5-e807-426a-9ac4-e04109256b01</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='LoanApproval']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#LoanApproval</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f08fe266-77ba-4686-bce0-415082ce7de1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gb-hover-side confirmation-link</value>
      <webElementGuid>d27184b3-3520-49f1-ad1e-ca6e20d2b5f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>LoanApproval</value>
      <webElementGuid>f08bd18d-2090-44b2-b816-aea3c5cf31fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>LoanApproval</value>
      <webElementGuid>2f1a37c5-c64c-478f-baac-57024b02f62b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>return loadIframe('ifrm1', this.href);</value>
      <webElementGuid>3f46e2c1-0b2a-4b7b-8b88-01fb46c344a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Loan
									Approval</value>
      <webElementGuid>456db015-b9c6-47c3-b02a-0e852e09a758</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;LoanApproval&quot;)</value>
      <webElementGuid>43e5d35f-cfed-4327-9b39-0dcec7baa889</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='LoanApproval']</value>
      <webElementGuid>96dbe69c-89c8-498a-b9dc-efa322c55e90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sidebarLoan']/ul/li[2]/a</value>
      <webElementGuid>936271d4-dbc6-4290-bf09-c64120503906</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Loan
									Approval')]</value>
      <webElementGuid>dc9fe1c2-524d-4a0d-aa6c-0167994925e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'LoanApproval')]</value>
      <webElementGuid>d64ed8dc-95ca-4696-bef3-f60cde7dcf02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/div/ul/li[2]/a</value>
      <webElementGuid>1726bcbe-2708-46c5-9a46-3af8ea234bda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'LoanApproval' and @id = 'LoanApproval' and (text() = 'Loan
									Approval' or . = 'Loan
									Approval')]</value>
      <webElementGuid>81aa57a2-be06-4e77-9929-68121f4ec68d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
