<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Approve</name>
   <tag></tag>
   <elementGuidId>91976f97-d3e1-48bf-818c-5933fc122491</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btnApprove']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.col-6 > #btnApprove</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>eb0647ec-0bf7-4d18-bff0-74676ae32fcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d07a99db-adb9-450a-a49f-9581ba01731d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn keep-enabled btn-success</value>
      <webElementGuid>79f8ffce-deed-4e8d-8bf2-bf891ee68f53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>approveLoan();</value>
      <webElementGuid>d82e5e34-19f0-4388-9ef9-712e6f665057</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnApprove</value>
      <webElementGuid>2eb2a270-41ff-43cf-9d95-5706ea72d7ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Approve</value>
      <webElementGuid>dcec9c76-9539-4ca0-a22c-166312dd63b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;LoancreationModal&quot;)/div[@class=&quot;modal-dialog modal-full-width&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-body&quot;]/div[@class=&quot;tab-content&quot;]/div[@id=&quot;btnApprove&quot;]/div[@class=&quot;col-6&quot;]/button[@id=&quot;btnApprove&quot;]</value>
      <webElementGuid>b7eb2f34-142b-4fac-8b41-6e238359d8c8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btnApprove']</value>
      <webElementGuid>53f88366-3b6d-4ade-a18f-1d70524c3f3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='btnApprove']/div[2]/button</value>
      <webElementGuid>99ab45d5-0de1-4572-82c9-f7c3d19e29a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div[2]/button</value>
      <webElementGuid>d3c40efb-8d9f-4bcf-871c-eda7bc09a01d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'btnApprove' and (text() = 'Approve' or . = 'Approve')]</value>
      <webElementGuid>e5fb1494-05fe-4aca-bd9d-52a58d9e405f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
