<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_SIKAP 1_ri-checkbox-circle-fill</name>
   <tag></tag>
   <elementGuidId>bf971216-4af9-406b-af85-e4e6bb93bffb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tbody[@id='LoanApprovalTbody']/tr/td[10]/a[2]/span/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.ri-checkbox-circle-fill</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>8071509e-f8a2-4056-ad65-c9e4924f59e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ri-checkbox-circle-fill</value>
      <webElementGuid>630ef845-8ac4-46bb-ae78-4c42a1dc5414</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;LoanApprovalTbody&quot;)/tr[@class=&quot;odd&quot;]/td[@class=&quot;td-actions&quot;]/a[@class=&quot;action-icon btn&quot;]/span[@class=&quot;icon text-gray-700 ml-auto&quot;]/i[@class=&quot;ri-checkbox-circle-fill&quot;]</value>
      <webElementGuid>0d9d1a27-09fc-45e1-b7a1-de3f1b4e65ea</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='LoanApprovalTbody']/tr/td[10]/a[2]/span/i</value>
      <webElementGuid>ba01176d-6c94-451a-80e2-bd3987d040aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]/span/i</value>
      <webElementGuid>0eee49cc-46aa-4fe1-b755-97b083452c56</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
